apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
  - name: ehrbase-creds
    literals:
      - username=user2
      - password=foobar2
  - name: ehrbase-admin-creds
    literals:
      - username=admin2
      - password=admin2
  - name: ehrbase-db-admin-creds
    literals:
      - username=ehrbase2
      - password=ehrbase2
  - name: ehrbase-db-creds
    literals:
      - username=ehrbase_restricted2
      - password=ehrbase_restricted2
  - name: portal-creds
    literals:
      - username=demo@zio.nl
      - password=foobar
  - name: federation-key
    literals:
      - key=key2
  - name: federation-break-the-glass-key
    literals:
      - key=btgkey2
  - name: ehrbase-db-postgres-creds
    literals:
      - username=postgres
      - password=postgres
  - name: transform-creds
    literals:
      - username=transform2
      - password=transform2
