apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
  - name: envida-ehrbase-creds
    literals:
      - username=user3
      - password=foobar3
  - name: envida-ehrbase-admin-creds
    literals:
      - username=admin3
      - password=admin3
  - name: envida-ehrbase-db-admin-creds
    literals:
      - username=ehrbase3
      - password=ehrbase3
  - name: envida-ehrbase-db-creds
    literals:
      - username=ehrbase_restricted3
      - password=ehrbase_restricted3
  - name: envida-portal-creds
    literals:
      - username=demo@envida.nl
      - password=foobar
  - name: envida-federation-key   
    literals:
      - key=key3
  - name: envida-federation-break-the-glass-key   
    literals:
      - key=btgkey3
  - name: envida-ehrbase-db-postgres-creds   
    literals:
      - username=postgres
      - password=postgres
  - name: envida-transform-creds   
    literals:
      - username=transform3
      - password=transform3
