apiVersion: v1
kind: ConfigMap
metadata:
  name: etl-config-node
data:
  NODENAME: envida
  DATASET_FOLDER_NAME: envida-demo-data
  SOURCE_SYSTEM_ID: "Nedap Ons"
  INPUT_FORMAT: "fhir"
  LOGGER_FILENAME: logs/envida/etl-zib.log
  NEDAP_CERT_BASE_URL: https://api-development.ons.io
  NEDAP_NUMBER_PATIENT_MAX: "20"
  WRITE_COMPOSITION: "True"
  # If SUBJECT_IDS is empty, extract subject_ids from dataset:
  SUBJECT_IDS: |
    []
  TEMPLATE_IDS: |
    [
      "DataHub-Bloeddruk-2024",
      "DataHub-Lichaamsgewicht-2024",
      "DataHub-Lichaamslengte-2024",
      "DataHub-Patient-2024"
    ]
