apiVersion: v1
kind: Service
metadata:
  name: vitala-etl-zib-rest
spec:
  type: ClusterIP
  ports:
    - port: 8040
      targetPort: 8040
      protocol: TCP
  selector:
    app: vitala-etl-zib-rest
