apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ehrbase-ingress.yaml
  - etl-zib-rest-ingress.yaml
  - openehrtool-ingress.yaml
  - portal-ingress.yaml
  - transform-rest-ingress.yaml
  - federation-rest-ingress.yaml

secretGenerator:
  - name: mumc-ehrbase-creds
    namespace: dh-health
    literals:
      - username=user1
      - password=foobar1
  - name: mumc-ehrbase-admin-creds
    namespace: dh-health
    literals:
      - username=admin1
      - password=admin1
  - name: mumc-ehrbase-db-admin-creds
    namespace: dh-health
    literals:
      - username=ehrbase1
      - password=ehrbase1
  - name: mumc-ehrbase-db-creds
    namespace: dh-health
    literals:
      - username=ehrbase_restricted1
      - password=ehrbase_restricted1
  - name: mumc-portal-creds
    namespace: dh-health
    literals:
      - username=demo@mumc.nl
      - password=foobar
  - name: mumc-federation-key
    namespace: dh-health
    literals:
      - key=key1
  - name: mumc-federation-break-the-glass-key
    namespace: dh-health
    literals:
      - key=btgkey1
  - name: mumc-ehrbase-db-postgres-creds
    namespace: dh-health
    literals:
      - username=postgres
      - password=postgres
  - name: mumc-transform-creds
    namespace: dh-health
    options:
      labels:
        ehrnode: mumc-node
    literals:
      - username=transform1
      - password=transform1
