apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
- name: test-ehrdb-config
  namespace: dh-health
  envs:
  - ehrdb.env