apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
- name: env-config
  namespace: dh-health
  literals:
  - RIT_ENV=prod
  - ENV_TAG=main
  - ENV_REGISTRY_HOST=registry.prod.dh.unimaas.nl
  behavior: merge
