apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: ingress-patches.yaml

- target:
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets
      value:
      - name: regcred