apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pv-mumc
  namespace: dh-health-mumc
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: log-pvc-mumc
    namespace: dh-health-mumc
  hostPath:
    path: /usr/share/logs/mumc
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pvc-mumc
  namespace: dh-health-mumc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: output-pv-mumc
  namespace: dh-health-mumc
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: output-pvc-mumc
    namespace: dh-health-mumc
  hostPath:
    path: /usr/share/outputs/mumc
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-pvc-mumc
  namespace: dh-health-mumc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data-pv-mumc
  namespace: dh-health-mumc
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: postgresql-data-pvc-mumc
    namespace: dh-health-mumc
  hostPath:
    path: /usr/share/postgresql_data/mumc
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data-pvc-mumc
  namespace: dh-health-mumc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi