apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: mumc-federation-rest-gateway
  namespace: dh-health
spec:
  gatewayClassName: traefik
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      hostname: federation.mumc.local.dh.unimaas.nl
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      port: 8443
      protocol: HTTPS
      hostname: federation.mumc.local.dh.unimaas.nl
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: mumc-mtls-federation
        options:
          clientValidation:
            caCertificateRefs:
              - kind: Secret
                name: mumc-mtls-ca
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mumc-federation-rest-route-http
  namespace: dh-health
spec:
  parentRefs:
    - name: mumc-federation-rest-gateway
      sectionName: http
  hostnames:
    - federation.mumc.local.dh.unimaas.nl
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mumc-federation-rest-route-https
  namespace: dh-health
spec:
  parentRefs:
    - name: mumc-federation-rest-gateway
      sectionName: https
  hostnames:
    - federation.mumc.local.dh.unimaas.nl
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: mumc-federation-rest
          port: 8000
