apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: mumc-federation-rest-gateway 
spec:
  gatewayClassName: traefik
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      hostname: federation.mumc.local.dh.unimaas.nl
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mumc-federation-rest-route
spec:
  parentRefs:
    - name: mumc-federation-rest-gateway
  hostnames:
    - federation.mumc.local.dh.unimaas.nl
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: federation-rest
          port: 8000
