apiVersion: batch/v1
kind: Job
metadata:
  name: test-single-node
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      initContainers:
        # The Terminology server proxy is a service dependency for both EHRbase and Transform-rest, so it is placed
        # as the first init container.
        # Note: It is an indirect check. If necessary, the service orchestration could be improved by placing
        # the wait-terminology-proxy check directly in the deployment.yaml of EHRbase and Transform-rest.
        - name: wait-terminology-proxy
          image: registry.prod.dh.unimaas.nl/docker-health/init-container:latest
          imagePullPolicy: IfNotPresent
          command:
            - "/wait-for-service.sh"
            - "http://terminology-server-proxy:8080/management/health"
            - "Terminology server proxy"
        - name: wait-ehrbase
          image: registry.prod.dh.unimaas.nl/docker-health/init-container:latest
          imagePullPolicy: IfNotPresent
          command:
            - "/wait-for-service.sh"
            - "http://ehrbase:8080/ehrbase/management/health"
            - "EHRbase"
        - name: wait-transform-rest
          image: registry.prod.dh.unimaas.nl/docker-health/init-container:latest
          imagePullPolicy: IfNotPresent
          command:
            - "/wait-for-service.sh"
            - "http://transform-rest:8080/management/health"
            - "Transform REST"
      containers:
        - name: test-single-node-runner
          image: registry.prod.dh.unimaas.nl/docker-health/etl-zib-test:latest
          # Uncomment and replace the following lines to overwrite the Test Docker image command, and execute the test with different
          # options of your choice and/or execute only one test file.
          #        command: ["pytest"]
          #        args:
          #          - -s
          #          - -o
          #          - log_cli=true
          #          - --log-cli-level=INFO
          #          - --verbose
          #          - /code/tests/demo_data/test_vermogen_tot_zich_kleden.py
          envFrom:
            - configMapRef:
                name: dry-run-config
            - configMapRef:
                name: timezone-config
            - configMapRef:
                name: zib-templates-config
            - configMapRef:
                name: etl-config-base
            - configMapRef:
                name: etl-config-node
          env:
            - name: DATA_ENCRYPTION_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: etl-data-encryption-passphrase
                  key: passphrase
            - name: EHRBASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ehrbase-creds
                  key: username
            - name: EHRBASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ehrbase-creds
                  key: password
            - name: EHRBASE_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ehrbase-admin-creds
                  key: username
            - name: EHRBASE_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ehrbase-admin-creds
                  key: password
            - name: TRANSFORM_SPRING_USERNAME
              valueFrom:
                secretKeyRef:
                  name: transform-creds
                  key: username
            - name: TRANSFORM_SPRING_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: transform-creds
                  key: password
            - name: NEDAP_CERT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nedap-cert-pass
                  key: password
          volumeMounts:
            - name: data
              mountPath: /code/data/test-demo-data
            - name: etl-logs
              mountPath: /code/logs/test
              subPath: test/etl-test-single-node
            - name: nedap-cert
              mountPath: /etc/nedap
              readOnly: true
      volumes:
        - name: data
          hostPath:
            path: /mnt/demo-data/data/test-demo-data
            type: Directory
        - name: etl-logs
          persistentVolumeClaim:
            claimName: log-pvc-test
        - name: nedap-cert
          secret:
            secretName: nedap-cert
