apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dh-health

resources:
- secrets.yaml
- test-secrets.yaml
- job.yaml
#- registry-secret.yaml
- ../../../base/common
- ../../../base/terminology-server-proxy
## TEST-node
- ../../../base/openehr-nodes/test/ehrbase
- ../../../base/openehr-nodes/test/ehrdb
- ../../../base/openehr-nodes/test/etl-config
- ../../../base/openehr-nodes/test/transform-rest

images:
- name: registry.prod.dh.unimaas.nl/docker-health/etl-zib-test
  newTag: '2024.1.4'
- name: registry.prod.dh.unimaas.nl/docker-health/transform-rest
  newTag: '2024.1.4'
- name: registry.prod.dh.unimaas.nl/docker-health/terminology-server-proxy
  newTag: '2024.1.4'

patches:
# imagePullPolicy patches
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: IfNotPresent
- target:
    kind: Job
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: IfNotPresent

# Image pull secret
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/imagePullSecrets
      value:
      - name: registry-credentials
- target:
    kind: Job
  patch: |-
    - op: replace
      path: /spec/template/spec/imagePullSecrets
      value:
      - name: registry-credentials

# Storage class patches
- target:
    kind: PersistentVolume
  patch: |-
    - op: replace
      path: /spec/storageClassName
      value: local-path
- target:
    kind: PersistentVolumeClaim
  patch: |-
    - op: replace
      path: /spec/storageClassName
      value: local-path

# Proxy patches
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: http_proxy
        value: "http://proxy.unimaas.nl:3128"
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: https_proxy
        value: "http://proxy.unimaas.nl:3128"
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: no_proxy
        value: "localhost,.dh.local,.dh-health,.unimaas.nl,.datahubmaastricht.nl,137.120.31.0/16,.cluster.local,10.42.0.0/12,10.43.0.1,10.43.0.10"

# Individual ingress host patches
## Transform
- path: patches/ingress/common/transform.yaml
## TEST-node
- path: patches/ingress/test/ehrbase.yaml

# Set ADMIN_API_ACTIVE: "true" and ADMIN_BASE_URL for development purposes while running the tests teardown.
configMapGenerator:
- name: test-ehrbase-config
  namespace: dh-health
  behavior: merge
  literals:
    - ADMIN_API_ACTIVE=true
- name: test-etl-config
  namespace: dh-health
  behavior: merge
  literals:
    - EHRBASE_ADMIN_BASE_URL=http://test-ehrbase:8080/ehrbase/rest/admin
