apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jupyter-zib-creds
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: jupyter-zib-creds
    template:
      engineVersion: v2
      data:
        SERVER_APP_TOKEN: "{{ .SERVER_APP_TOKEN }}"
  dataFrom:
    - extract:
        key: hdp-env/jupyter-zib-creds
