apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-ehrbase-creds
  namespace: dh-health
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: SecretStore
  target:
    name: test-ehrbase-creds
    template:
      engineVersion: v2
      data:
        username: "user0"
        password: "{{ .test_ehrbase_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/test
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-ehrbase-admin-creds
  namespace: dh-health
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: SecretStore
  target:
    name: test-ehrbase-admin-creds
    template:
      engineVersion: v2
      data:
        username: "admin0"
        password: "{{ .test_ehrbase_admin_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/test
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-ehrbase-db-admin-creds
  namespace: dh-health
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: SecretStore
  target:
    name: test-ehrbase-db-admin-creds
    template:
      engineVersion: v2
      data:
        username: "ehrbase0"
        password: "{{ .test_ehrbase_db_admin_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/test
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-ehrbase-db-creds
  namespace: dh-health
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: SecretStore
  target:
    name: test-ehrbase-db-creds
    template:
      engineVersion: v2
      data:
        username: "ehrbase_restricted0"
        password: "{{ .test_ehrbase_db_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/test
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-ehrbase-db-postgres-creds
  namespace: dh-health
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: SecretStore
  target:
    name: test-ehrbase-db-postgres-creds
    template:
      engineVersion: v2
      data:
        username: "postgres"
        password: "{{ .test_ehrbase_db_postgres_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/test
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-transform-creds
  namespace: dh-health
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: SecretStore
  target:
    name: test-transform-creds
    template:
      engineVersion: v2
      data:
        username: "transform0"
        password: "{{ .test_transform_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/test