apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-log-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: log-pvc-test
    namespace: dh-health-test-single
  storageClassName: local-storage
  hostPath:
    path: /usr/share/logs-test
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pvc-test
  namespace: dh-health-test-single
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi

