apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pv-test
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: log-pvc-test
    namespace: dh-health-test-single-node

  hostPath:
    path: /usr/share/logs/test
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pvc-test
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 10Gi
