apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- ehrbase-deployment.yaml
- ehrbase-service.yaml
- ehrbase-ingress.yaml
- ehrdb-deployment.yaml
- ehrdb-service.yaml
- etl-zib-deployment.yaml
- openehrtool-deployment.yaml
- openehrtool-service.yaml
- openehrtool-ingress.yaml
- portal-deployment.yaml
- portal-service.yaml
- portal-ingress.yaml

configMapGenerator:
- name: mumc-ehrbase-config
  namespace: dh-health
  envs:
  - mumc/ehrbase.env

- name: mumc-ehrdb-config
  namespace: dh-health
  envs:
  - mumc/ehrdb.env

- name: mumc-etl-config
  namespace: dh-health
  envs:
  - mumc/etl.env

- name: mumc-portal-config
  namespace: dh-health
  envs:
  - mumc/portal.env

- name: mumc-openehrtool-config
  namespace: dh-health
  literals:
    - EHRBASESERVER_hostname=mumc-ehrbase.dh-health
