# Using an older version so that there are no compatibility issues between an older elk version
FROM docker.elastic.co/beats/filebeat:7.13.2
COPY --chown=root:filebeat filebeat.yml /usr/share/filebeat/filebeat.yml