filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/logs/transform-rest/transform-rest.log
    tags: ["TRANSFORM_REST"]

  - type: log
    enabled: true
    paths:
      - /usr/share/logs/mumc/etl-zib/etl-zib.log
    tags: ["MUMC_ETL_ZIB"]

  - type: log
    enabled: true
    paths:
      - /usr/share/logs/gp/etl-zib/etl-zib.log
    tags: [ "GP_ETL_ZIB" ]

  - type: log
    enabled: true
    paths:
      - /usr/share/logs/mumc/ehrbase/ehrbase.log
    tags: ["MUMC_EHRBASE"]

  - type: log
    enabled: true
    paths:
      - /usr/share/logs/gp/ehrbase/ehrbase.log
    tags: ["GP_EHRBASE"]

  - type: log
    enabled: true
    paths:
      - /usr/share/logs/mumc/ehrdb/postgresql.log
    tags: ["MUMC_EHRDB"]

  - type: log
    enabled: true
    paths:
      - /usr/share/logs/gp/ehrdb/postgresql.log
    tags: [ "GP_EHRDB" ]

# Unused at the moment:
#  - type: log
#    enabled: true
#    paths:
#      - /usr/share/logs/federation-api/federation-api.log
#      - /usr/share/logs/
#    tags: ["FEDERATION_API"]

# Disable filebeat monitoring
logging.metrics.enabled: false

output.logstash:
  hosts: ["elk.dh.local:5044"]
  ssl.certificate_authorities: ["/etc/certs/ca.crt"]
  ssl.certificate: "/etc/certs/filebeat.dh.local.crt"
  ssl.key: "/etc/certs/filebeat.dh.local.key"
