filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/logs/etl-demo/etl-demo.log
      - /usr/share/logs/transform-rest/transform-rest.log

    #Tags
    tags: ["ETL_DEMO", "TRANSFORM_REST"]

# Disable filebeat monitoring
logging.metrics.enabled: false

output.logstash:
  hosts: ["elk.dh.local:5044"]
