filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/logs/transform-rest/transform-rest.log
    tags: ["TRANSFORM_REST"]

  - type: log
    enabled: true
    paths:
      - /usr/share/logs/test/etl-zib/etl-zib.log
    multiline:
      pattern: '^\[\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}\]\[' # corresponds to '[datetime]['
      negate: true
      match: after
    tags: ["TEST_ETL_ZIB"]

  - type: log
    enabled: true
    paths:
      - /usr/share/logs/mumc/etl-zib/etl-zib.log
    multiline:
      pattern: '^\[\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}\]\[' # corresponds to '[datetime]['
      negate: true
      match: after
    tags: [ "MUMC_ETL_ZIB" ]

  - type: log
    enabled: true
    paths:
      - /usr/share/logs/zio/etl-zib/etl-zib.log
    multiline:
      pattern: '^\[\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}\]\[' # corresponds to '[datetime]['
      negate: true
      match: after
    tags: [ "ZIO_ETL_ZIB" ]

  - type: log
    enabled: true
    paths:
      - /usr/share/logs/envida/etl-zib/etl-zib.log
    multiline:
      pattern: '^\[\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}\]\[' # corresponds to '[datetime]['
      negate: true
      match: after
    tags: [ "ENVIDA_ETL_ZIB" ]

  - type: log
    enabled: true
    paths:
      - /usr/share/logs/test/ehrbase/ehrbase.log
    tags: ["TEST_EHRBASE"]

  - type: log
    enabled: true
    paths:
      - /usr/share/logs/mumc/ehrbase/ehrbase.log
    tags: ["MUMC_EHRBASE"]
    
  - type: log
    enabled: true
    paths:
      - /usr/share/logs/zio/ehrbase/ehrbase.log
    tags: ["ZIO_EHRBASE"]

  - type: log
    enabled: true
    paths:
      - /usr/share/logs/envida/ehrbase/ehrbase.log
    tags: ["ENVIDA_EHRBASE"]

  - type: log
    enabled: true
    paths:
      - /usr/share/logs/test/ehrdb/postgresql.log
    tags: ["TEST_EHRDB"]

  - type: log
    enabled: true
    paths:
      - /usr/share/logs/mumc/ehrdb/postgresql.log
    tags: ["MUMC_EHRDB"]

  - type: log
    enabled: true
    paths:
      - /usr/share/logs/zio/ehrdb/postgresql.log
    tags: [ "ZIO_EHRDB" ]

  - type: log
    enabled: true
    paths:
      - /usr/share/logs/envida/ehrdb/postgresql.log
    tags: [ "ENVIDA_EHRDB" ]

# Unused at the moment:
#  - type: log
#    enabled: true
#    paths:
#      - /usr/share/logs/federation-api/federation-api.log
#      - /usr/share/logs/
#    tags: ["FEDERATION_API"]

# Disable filebeat monitoring
logging.metrics.enabled: false

output.logstash:
  hosts: ["elk.dh.local:5044"]
  ssl.certificate_authorities: ["/etc/certs/ca.crt"]
  ssl.certificate: "/etc/certs/filebeat.dh.local.crt"
  ssl.key: "/etc/certs/filebeat.dh.local.key"
