filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/logs/etl-demo/etl-demo.log

    #Tags
    tags: ["ETL_DEMO"]

  - type: log
    enabled: true
    paths:
      - /usr/share/logs/transform-rest/transform-rest.log

    #Tags
    tags: ["TRANSFORM_REST"]

  - type: log
    enabled: true
    paths:
      - /usr/share/logs/ehrbase/ehrbase.log

    #Tags
    tags: [ "EHRBASE" ]

# Disable filebeat monitoring
logging.metrics.enabled: false

output.logstash:
  hosts: ["elk.dh.local:5044"]
