apiVersion: apps/v1
kind: Deployment
metadata:
  name: zio-terminology-server-proxy
  labels:
    app: zio-terminology-server-proxy
spec:
  selector:
    matchLabels:
      app: zio-terminology-server-proxy
  template:
    metadata:
      labels:
        app: zio-terminology-server-proxy
    spec:
      containers:
      - name: zio-terminology-server-proxy
        image: registry.prod.dh.unimaas.nl/docker-health/terminology-server-proxy:latest
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: zio-terminology-server-proxy-config
          - configMapRef:
              name: terminology-server-proxy-config
          - configMapRef:
              name: dry-run-config
          - configMapRef:
              name: timezone-config
        env:
          - name: TERMINOLOGY_USERNAME
            valueFrom:
              secretKeyRef:
                name: terminology-server-proxy-creds
                key: username
          - name: TERMINOLOGY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: terminology-server-proxy-creds
                key: password
        volumeMounts:
          - name: terminology-logs
            mountPath: /opt/app/logs/zio
            subPath: zio/terminology
      volumes:
        - name: terminology-logs
          persistentVolumeClaim:
            claimName: log-pvc-zio