---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pv-mumc
  namespace: dh-health-mumc
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nfs-mumc-logs
    volumeAttributes:
      server: fhml-srv017.unimaas.nl
      share: /bkp/tst-k3s/logs/mumc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pvc-mumc
  namespace: dh-health-mumc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi
  volumeName: log-pv-mumc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: output-pv-mumc
  namespace: dh-health-mumc
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nfs-mumc-outputs
    volumeAttributes:
      server: fhml-srv017.unimaas.nl
      share: /bkp/tst-k3s/outputs/mumc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-pvc-mumc
  namespace: dh-health-mumc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi
  volumeName: output-pv-mumc