apiVersion: v1
kind: ConfigMap
metadata:
  name: mumc-etl-config
  namespace: dh-health
data:
  NODENAME: mumc
  DATASET_FOLDER_NAME: mumc-demo-data
  SOURCE_SYSTEM_ID: SAP
  LOGGER_FILENAME: logs/mumc/etl-zib.log
  EHRBASE_BASE_URL: http://mumc-ehrbase.dh-health:8080/ehrbase/rest/openehr/v1
  WRITE_COMPOSITION: "true"
  # Specify the SUBJECT_IDS for MUMC manually as a control.
  SUBJECT_IDS: '["001645201","083197102","339055303"]'
  TEMPLATE_IDS: |
    [
      "DataHub-AlcoholGebruik-2024",
      "DataHub-Bloeddruk-2024",
      "DataHub-BurgerlijkeStaat-2024",
      "DataHub-Contactpersoon-2024",
      "DataHub-FunctieHoren-2024",
      "DataHub-Gezinssituatie-2024",
      "DataHub-InformedConsent",
      "DataHub-Lichaamsgewicht-2024",
      "DataHub-Lichaamslengte-2024",
      "DataHub-Patient-2024",
      "DataHub-TabakGebruik-2024",
      "DataHub-VermogenTotZichWassen-2024",
      "DataHub-VermogenTotZichKleden-2024",
      "DataHub-VermogenTotUiterlijkeVerzorging-2024",
      "DataHub-VermogenTotZelfstandigMedicatiegebruik-2024",
      "DataHub-VermogenTotDrinken-2024",
      "DataHub-VermogenTotEten-2024",
      "DataHub-VermogenTotMondverzorging-2024",
      "DataHub-VermogenTotToiletgang-2024",
      "DataHub-Woonsituatie-2024"
    ]
