apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-zib
  namespace: dh-health
spec:
  template:
    spec:
      containers:
        - name: jupyter-zib
          volumeMounts:
          - name: demo-data
            mountPath: /home/jovyan/data
            subPath: src/data
      volumes:
        - name: demo-data
          persistentVolumeClaim:
            claimName: git-repo-pvc