include:
  - docker-compose.mumc-node.yml
  - docker-compose.gp-node.yml
services:
  proxy:
    image: jwilder/nginx-proxy:${ENV_TAG_PROXY}
    env_file:
      - ./env_files/timezone.env
    volumes:
      - /etc/ssl/certs:/etc/nginx/certs/
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - hdp-dh-mumc-net
      - hdp-dh-gp-net
  transform-rest:
    build:
      context: ./externals/dh-hdp-transform-rest
      dockerfile: Dockerfile
      args:
        - MAVEN_VERSION=${MAVEN_VERSION}
      additional_contexts:
        hdp_templates: ./externals/dh-hdp-zib-templates
    image: ${ENV_REGISTRY_HOST}/docker-health/transform-rest:${ENV_TAG}
    depends_on:
      - proxy
      - filebeat
    volumes:
      - ./filebeat/logs/transform-rest:/var/log
    #      - ./externals/dh-hdp-transform-rest/src/:/code/src
    env_file:
      - ./env_files/timezone.env
      - ./env_files/transform_server.env
      - ./env_files/zib-templates.env
    environment:
      LOGSTASH_TAGS: TRANSFORM_REST
      VIRTUAL_HOST: transform.${RIT_ENV}.dh.unimaas.nl
    ports:
      - "8082:8080"
    networks:
      hdp-dh-mumc-net:
        aliases:
          - transform.dh.local
      hdp-dh-gp-net:
        aliases:
          - transform.dh.local
  federation-api:
    build:
      context: ./externals/dh-hdp-federation-api
      dockerfile: Dockerfile
    image: ${ENV_REGISTRY_HOST}/docker-health/federation-api:${ENV_TAG}
    depends_on:
      proxy:
        condition: service_started
      filebeat:
        condition: service_started
      mumc-etl-zib:
        condition: service_started
      gp-etl-zib:
        condition: service_started
    volumes:
      - ./filebeat/logs/federation-api:/var/log
    env_file:
      - ./env_files/timezone.env
    environment:
#      LOGSTASH_TAGS: FEDERATION_API
      VIRTUAL_HOST: federation.${RIT_ENV}.dh.unimaas.nl
      MUMC__EHRBASE_USERNAME: ${EHRBASE_USERNAME_MUMC_NODE}
      MUMC__EHRBASE_PASSWORD: ${EHRBASE_PASSWORD_MUMC_NODE}
      MUMC__EHRBASE_BASE_URL: ${EHRBASE_BASE_URL_MUMC_NODE}
      GP__EHRBASE_USERNAME: ${EHRBASE_USERNAME_GP_NODE}
      GP__EHRBASE_PASSWORD: ${EHRBASE_PASSWORD_GP_NODE}
      GP__EHRBASE_BASE_URL: ${EHRBASE_BASE_URL_GP_NODE}
    ports:
      - "8000:8000"
    networks:
      hdp-dh-mumc-net:
        aliases:
          - federation.dh.local
      hdp-dh-gp-net:
        aliases:
          - federation.dh.local
  filebeat:
    build:
      context: ./filebeat
      dockerfile: Dockerfile
    env_file:
      - ./env_files/timezone.env
    volumes:
      - ./filebeat/filebeat.yml:/etc/filebeat/filebeat.yml:ro
      - ./filebeat/logs:/usr/share/logs/
      - ./filebeat/certs:/etc/certs:ro
    networks:
      hdp-dh-mumc-net:
        aliases:
          - filebeat.dh.local
      hdp-dh-gp-net:
        aliases:
          - filebeat.dh.local
  jupyter-zib:
    build:
      context: ./externals/dh-hdp-notebooks
      dockerfile: Dockerfile
      args:
        - DATA=zib
      additional_contexts:
        hdp_templates: ./externals/dh-hdp-zib-templates
    image: ${ENV_REGISTRY_HOST}/docker-health/jupyter-zib:${ENV_TAG}
    command: "start-notebook.sh --ServerApp.token=${SERVER_APP_TOKEN}"
    depends_on:
      transform-rest:
        condition: service_started
    env_file:
      - ./env_files/timezone.env
      - ./env_files/transform_server.env
      - ./env_files/zib-templates.env
      - ./env_files/mumc/etl.env
    environment:
      VIRTUAL_HOST: jupyter.${RIT_ENV}.dh.unimaas.nl
      # Update the env depending on the node:
      EHRBASE_USERNAME: ${EHRBASE_USERNAME_MUMC_NODE}
      EHRBASE_PASSWORD: ${EHRBASE_PASSWORD_MUMC_NODE}
      EHRBASE_BASE_URL: ${EHRBASE_BASE_URL_MUMC_NODE}
    volumes:
      - ./data/mumc-demo-data:/home/jovyan/data/mumc-demo-data
      - ./data/gp-demo-data:/home/jovyan/data/gp-demo-data
      # Volume binds to auto-reload the code inside the container
      - ./externals/dh-hdp-etl/etl.py:/home/jovyan/etl.py
      - ./externals/dh-hdp-etl/requirements.txt:/home/jovyan/requirements.txt
      - ./externals/dh-hdp-etl/src:/home/jovyan/src
      # Volume binds to auto-reload the code inside the container
      - ./externals/dh-hdp-notebooks/:/home/jovyan/notebooks
    ports:
      - "8888:8888"
    networks:
      hdp-dh-mumc-net:
        aliases:
          - jupyter-zib.dh.local
      hdp-dh-gp-net:
        aliases:
          - jupyter-zib.dh.local
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server  /redis.conf
    volumes:
      - ./openEHR-tool/redis.conf:/redis.conf
    networks:
      hdp-dh-mumc-net:
        aliases:
          - redis.dh.local
      hdp-dh-gp-net:
        aliases:
          - redis.dh.local
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123456
    command: server /data --console-address ":9001"
    networks:
      - hdp-dh-mumc-net
      - hdp-dh-gp-net
  #  fhir-bridge:
  #    ## BUILD option 1: Using a pre-build docker image
  #    # image: ehrbase/fhir-bridge:1.5.5
  #    ## BUILD option 2: Using a Dockerfile FAILED:
  #    # build:
  #    #   context: ./externals/dh-hdp-fhir-bridge
  #    #   # additional_contexts:
  #    #   #   - hdp_transform_rest=./externals/dh-hdp-transform-rest
  #    #   dockerfile: Dockerfile
  #    #   args:
  #    #     - MAVEN_VERSION=${MAVEN_VERSION}
  #    #     - FHIR_BRIDGE_VERSION=${FHIR_BRIDGE_VERSION}
  #    #     - HDP_ZIB_TEMPLATES_IMAGE_NAME=${HDP_ZIB_TEMPLATES_IMAGE_NAME}
  #    # # image: ${ENV_REGISTRY_HOST}/docker-health/fhir-bridge:${ENV_TAG}
  #    ## BUILD option 3: Build the image using `mvn clean spring-boot:build-image`
  #    image: hdp-ehrbase/fhir-bridge:${ENV_TAG}
  #    depends_on:
  #      ehrbase:
  #        condition: service_healthy
  #    env_file:
  #      - ./env_files/fhir-bridge.env
  #    environment:
  #      VIRTUAL_HOST: fhir-bridge.${RIT_ENV}.dh.unimaas.nl
  #    ports:
  #      - "8887:8888"
  #    networks:
  #      hdp-dh-mumc-net:
  #        aliases:
  #          - fhir-bridge.dh.local
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.30.1.0/24"
  hdp-dh-mumc-net:
    ipam:
      driver: default
      config:
        - subnet: "172.31.1.0/24"
  hdp-dh-gp-net:
    ipam:
      driver: default
      config:
        - subnet: "172.32.1.0/24"
