version: '3.6'
services:
  proxy:
    image: jwilder/nginx-proxy:0.9.3
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - hdp-dh-net
  demo-data:
    build:
      context: ./externals/dh-demodata
      dockerfile: Dockerfile
    image: demo_data
    volumes:
      - ./demo_data:/opt/output
  etl-demo:
    build:
      context: ./ETL
      dockerfile: Dockerfile
    image: etl_demo
    volumes:
      - ./externals/hdp-models/templates:/code/data/templates
      - ./demo_data/csv:/code/data/synthea_csv
      - ./ETL/data/plot:/code/data/plot
    environment:
      EHRBASE_USERRNAME: user
      EHRBASE_PASSWORD: foobar
      EHRBASE_BASE_URL: "http://ehrbase.dh.local:8080/ehrbase/rest/openehr/v1"
    networks:
      - hdp-dh-net
  flatehr-demo:
    build:
      context: ./flatehr
      dockerfile: Dockerfile
    image: flatehr_demo
    volumes:
      - ./externals/hdp-models/templates:/code/data/templates
      - ./demo_data/:/code/data/synthea
      - ./flatehr/data/conf_files:/code/data/conf_files
    environment:
      EHRBASE_USERRNAME: user
      EHRBASE_PASSWORD: foobar
      EHRBASE_BASE_URL: "http://ehrbase.dh.local:8080/ehrbase/rest/openehr/v1"
      ECIS_BASE_URL: "http://ehrbase.dh.local:8080/ehrbase/rest/ecis/v1"
    networks:
      - hdp-dh-net
  data-exploration:
    image: quay.io/jupyter/datascience-notebook:2023-10-31
    command: "start-notebook.sh --ServerApp.token="
    environment:
      VIRTUAL_HOST: jupyter.local.dh.unimaas.nl
    ports:
      - 8888:8888
    volumes:
      - ./demo_data/csv:/home/jovyan/data
      - ./notebooks/:/home/jovyan/notebooks
    networks:
      hdp-dh-net:
        aliases:
          - jupyter.dh.local
  ehrbase:
    image: ehrbase/ehrbase:0.31.0
    depends_on:
      - ehrdb
    ports:
      - 8080:8080
    networks:
      hdp-dh-net:
        aliases:
          - ehrbase.dh.local
    env_file:
      - ehrbase/.env.ehrbase
    restart: on-failure
  ehrdb:
    image: ehrbase/ehrbase-postgres:13.4.v2
    ports:
      - 5432:5432
    networks:
      - hdp-dh-net
    volumes:
      - ./ehrbase/.pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      EHRBASE_USER_ADMIN: ehrbase
      EHRBASE_PASSWORD_ADMIN: ehrbase
      EHRBASE_USER: ehrbase_restricted
      EHRBASE_PASSWORD: ehrbase_restricted
networks:
  hdp-dh-net: {}
