services:
  ehrbase2:
    image: ehrbase/ehrbase:2.6.0
    depends_on:
      ehrdb2:
        condition: service_healthy
      # The depends_on property only works for services defined within the same compose.yaml file.
      # We would need to implement custom retry logic in your application to handle dependencies gracefully.
      # You need to make sure yourself that proxy and filebeat from main compose file are started.
      # proxy:
      #   condition: service_started
      # filebeat:
      #   condition: service_started
    env_file:
      - ./env_files/timezone.env
      - ./env_files/ehrbase2.env
    environment:
      VIRTUAL_HOST: ehrbase2.${RIT_ENV}.dh.unimaas.nl
      VIRTUAL_PORT: 8081
    healthcheck:
      test: "wget -T5 -qO- -Y off localhost:8081/ehrbase/management/health | grep UP || exit 1"
      interval: 5s
      timeout: 3s
      retries: 10
    #     start_period: 10s
    ports:
      - "8081:8081"
    networks:
      dev-hdp_hdp-dh-net:
        aliases:
          - ehrbase2.dh.local
    entrypoint:
      - java
      - -jar
      - -Dspring.profiles.active=docker
      - -Dlogging.file.name=/tmp/ehrbaselog/ehrbase.log
      - ehrbase.jar
    volumes:
      - ./filebeat/logs/ehrbase2:/tmp/ehrbaselog
    restart: on-failure
  ehrdb2:
    image: ehrbase/ehrbase-v2-postgres:16.2
    environment:
      - PGPORT=5433
    command:
      [
        "postgres",
        "-p",
        "5433",
        "-c",
        "logging_collector=on",
        "-c",
        "log_directory=/tmp/postgreslog/",
        "-c",
        "log_filename=postgresql.log",
        "-c",
        "log_statement=none",
        "-c",
        "log_file_mode=0777",
        "-c",
        "log_rotation_age=0",
        "-c",
        "log_rotation_size=0",
      ]
    # https://www.postgresql.org/docs/current/runtime-config-logging.html#RUNTIME-CONFIG-LOGGING-WHAT
    volumes:
      - ./filebeat/logs/ehrdb2:/tmp/postgreslog
    env_file:
      - ./env_files/timezone.env
      - ./env_files/ehrdb.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 12

    ports:
      - "5433:5433"
    networks:
      - dev-hdp_hdp-dh-net
  openehrtool2:
    image: surfercrs4/openehrtool:latest
    volumes:
      - ./openEHR-tool/openehrtool-second-node.cfg:/code/config/openehrtool.cfg
    env_file:
      - ./openEHR-tool/.env
    depends_on:
      # - redis
      - ehrbase2
      # - proxy
    ports:
      - 9001:9001
    command: ["flask", "run", "--host=0.0.0.0", "--port=9001"]
    environment:
      VIRTUAL_HOST: openehrtool2.${RIT_ENV}.dh.unimaas.nl
      FLASK_RUN_PORT: 9001
    networks:
      dev-hdp_hdp-dh-net:
        aliases:
          - openehrtool2.dh.local
# This config now relies on the main compose file that the network has already been created
networks:
  dev-hdp_hdp-dh-net:
    external: true
