services:
  transform-rest:
    build:
      context: ./externals/dh-hdp-transform-rest
      dockerfile: Dockerfile
      args:
        - MAVEN_VERSION=${MAVEN_VERSION}
      additional_contexts:
        hdp_templates: ./externals/dh-hdp-zib-templates
    image: docker-health/transform-rest:${ENV_TAG}
    
  federation-api:
    build:
      context: ./externals/dh-hdp-federation-api
      dockerfile: Dockerfile
      additional_contexts:
        src_etl: ./externals/dh-hdp-etl
    image: docker-health/federation-api:${ENV_TAG}

  filebeat:
    build:
      context: ./filebeat
      dockerfile: Dockerfile
    image: docker-health/filebeat:${ENV_TAG}
    
  jupyter-zib:
    build:
      context: ./externals/dh-hdp-notebooks
      dockerfile: Dockerfile
      args:
        - DATA=zib
      additional_contexts:
        hdp_templates: ./externals/dh-hdp-zib-templates
    image: docker-health/jupyter-zib:${ENV_TAG}
    
  etl-zib:
    build:
      context: ./externals/dh-hdp-etl
      dockerfile: Dockerfile
      args:
        - SRC_SUBPROJECT=zib
      additional_contexts:
        hdp_templates: ./externals/dh-hdp-zib-templates
    image: docker-health/etl-zib:${ENV_TAG}

  portal:
    build:
      context: externals/dh-hdp-portal/
      dockerfile: Dockerfile
      target: development
    image: docker-health/portal:${ENV_TAG}