version: "3.6"
services:
  proxy:
    image: jwilder/nginx-proxy:${ENV_TAG_PROXY}
    environment:
      TZ: Europe/Amsterdam
    volumes:
      - /etc/ssl/certs:/etc/nginx/certs/
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - hdp-dh-net
  ehrbase:
    image: ehrbase/ehrbase:0.32.0
    environment:
      TZ: Europe/Amsterdam
    depends_on:
      - ehrdb
    ports:
      - "8080:8080"
    networks:
      hdp-dh-net:
        aliases:
          - ehrbase.dh.local
    env_file:
      - ./ehrbase/.env.ehrbase
    entrypoint:
      - java
      - -jar
      - -Dspring.profiles.active=docker
      - -Dlogging.file.name=/var/log/ehrbase.log
      - ehrbase.jar
    volumes:
      - ./filebeat/logs/ehrbase:/var/log
    restart: on-failure
  ehrdb:
    image: ehrbase/ehrbase-postgres:13.4.v2
    command: ["postgres", "-c", "logging_collector=on", "-c", "log_directory=/tmp/postgreslog/", "-c", "log_filename=postgresql.log", "-c", "log_statement=none", "-c", "log_file_mode=0777", "-c", "log_rotation_age=0", "-c", "log_rotation_size=0"]
    #https://www.postgresql.org/docs/current/runtime-config-logging.html#RUNTIME-CONFIG-LOGGING-WHAT
    volumes:
      - ./filebeat/logs/ehrdb:/tmp/postgreslog
    ports:
      - "5432:5432"
    networks:
      - hdp-dh-net
    environment:
      TZ: Europe/Amsterdam
      LOGSTASH_TAGS: EHR_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      EHRBASE_USER_ADMIN: ehrbase
      EHRBASE_PASSWORD_ADMIN: ehrbase
      EHRBASE_USER: ehrbase_restricted
      EHRBASE_PASSWORD: ehrbase_restricted
  transform-rest:
    build:
      context: ./externals/dh-hdp-transform-rest
      dockerfile: Dockerfile
      args:
        - HDP_TEMPLATES_IMAGE_NAME
    image: ${ENV_REGISTRY_HOST}/docker-health/transform-rest:${ENV_TAG}
    volumes:
      - ./filebeat/logs/transform-rest:/var/log
    #      - ./externals/dh-hdp-transform-rest/src:/code/src
    environment:
      TZ: Europe/Amsterdam
      VIRTUAL_HOST: transform.${RIT_ENV}.dh.unimaas.nl
      LOGSTASH_TAGS: TRANSFORM_REST
      DIAGNOSIS_SEM_VER: 0.4.0
      PATIENT_SEM_VER: 0.2.0
      VITAL_SIGNS_SEM_VER: 0.2.0
      SPRING_SECURITY_USERNAME: user
      SPRING_SECURITY_PASSWORD: foobar
    ports:
      - "8081:8080"
    networks:
      hdp-dh-net:
        aliases:
          - transform.dh.local
  etl-demo:
    build:
      context: ./externals/dh-hdp-etl
      dockerfile: Dockerfile
      args:
        - HDP_TEMPLATES_IMAGE_NAME
    image: ${ENV_REGISTRY_HOST}/docker-health/etl-demo:${ENV_TAG}
    volumes:
      - ./demo_data:/code/data/synthea
      - ./externals/dh-hdp-etl/outputs:/code/outputs
      # Volume binds to auto-reload the code inside the container
      - ./externals/dh-hdp-etl/etl.py:/code/etl.py
      - ./externals/dh-hdp-etl/src:/code/src
      - ./filebeat/logs/etl-demo:/code/logs
    environment:
      TZ: Europe/Amsterdam
      LOGSTASH_TAGS: ETL_DEMO
      EHRBASE_USERNAME: user
      EHRBASE_PASSWORD: foobar
      EHRBASE_BASE_URL: "http://ehrbase.dh.local:8080/ehrbase/rest/openehr/v1"
      TRANSFORM_SPRING_BASE_URL: "http://transform.dh.local:8080"
      TRANSFORM_SPRING_USERNAME: user
      TRANSFORM_SPRING_PASSWORD: foobar
      DIAGNOSIS_SEM_VER: 0.4.0
      PATIENT_SEM_VER: 0.2.0
      VITAL_SIGNS_SEM_VER: 0.2.0
    networks:
      - hdp-dh-net
  demo-data:
    build:
      context: ./externals/dh-hdp-demodata
      dockerfile: Dockerfile
    image: ${ENV_REGISTRY_HOST}/docker-health/demo-data:${ENV_TAG}
    volumes:
      - ./demo_data:/opt/output
  data-exploration:
    build:
      context: ./externals/dh-hdp-notebooks
      dockerfile: Dockerfile
    image: ${ENV_REGISTRY_HOST}/docker-health/data-exploration:${ENV_TAG}
    command: "start-notebook.sh --ServerApp.token=${SERVER_APP_TOKEN}"
    environment:
      TZ: Europe/Amsterdam
      VIRTUAL_HOST: jupyter.${RIT_ENV}.dh.unimaas.nl
    ports:
      - "8888:8888"
    volumes:
      - ./demo_data/csv:/home/jovyan/data
      # Volume binds to auto-reload the code inside the container
      - ./externals/dh-hdp-notebooks/:/home/jovyan/notebooks
    networks:
      hdp-dh-net:
        aliases:
          - jupyter.dh.local
  filebeat:
    build:
      context: ./filebeat
      dockerfile: Dockerfile
    environment:
      TZ: Europe/Amsterdam
    volumes:
      - ./filebeat/filebeat.yml:/etc/filebeat/filebeat.yml:ro
      - ./filebeat/logs:/usr/share/logs/
      - ./filebeat/certs:/etc/certs:ro
    networks:
      hdp-dh-net:
        aliases:
          - filebeat.dh.local

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.30.1.0/24"
  hdp-dh-net:
   ipam:
      driver: default
      config:
        - subnet: "172.31.1.0/24"
