apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: federation-service-creds
spec:
  refreshInterval: 168h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: federation-service-creds
    template:
      engineVersion: v2
      data:
        key: "{{ .secret }}"
  dataFrom:
    - extract:
        key: hdp-env/federation-service-creds