apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vitala-federation-key
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: vitala-federation-key
    template:
      engineVersion: v2
      data:
        key: "{{ .vitala_federation_key }}"
  dataFrom:
    - extract:
        key: hdp-env/vitala
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vitala-federation-break-the-glass-key
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: vitala-federation-break-the-glass-key
    template:
      engineVersion: v2
      data:
        key: "{{ .vitala_federation_break_the_glass_key }}"
  dataFrom:
    - extract:
        key: hdp-env/vitala
