---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-logs
  namespace: dh-health
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nfs-logs
    volumeAttributes:
      server: fhml-srv017.unimaas.nl
      share:  /bkp/tst-k3s/logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pvc
  namespace: dh-health
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-csi
  volumeName: pv-logs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-outputs
  namespace: dh-health
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nfs-outputs
    volumeAttributes:
      server: fhml-srv017.unimaas.nl
      share:  /bkp/tst-k3s/outputs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-pvc
  namespace: dh-health
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi
  volumeName: pv-outputs
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: postgresql-data-pvc
#  namespace: dh-health
#spec:
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 10Gi
#  storageClassName: longhorn-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notebooks-pvc
  namespace: dh-health
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-retain
  resources:
    requests:
      storage: 1Gi
