apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pvc
  namespace: dh-health
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-pvc
  namespace: dh-health
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data-pvc
  namespace: dh-health
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notebooks-pvc
  namespace: dh-health
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-retain
  resources:
    requests:
      storage: 1Gi
