apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pv-vitala
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
     name: log-pvc-vitala
 
  hostPath:
    path: /usr/share/logs/vitala
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pvc-vitala
spec:
  accessModes:
    - ReadWriteOnce
 
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: output-pv-vitala
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
     name: output-pvc-vitala
 
  hostPath:
    path: /usr/share/outputs/vitala
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-pvc-vitala
spec:
  accessModes:
    - ReadWriteOnce
 
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data-pv-vitala
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
     name: postgresql-data-pvc-vitala
 
  hostPath:
    path: /usr/share/postgresql_data/vitala
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data-pvc-vitala
spec:
  accessModes:
    - ReadWriteOnce
 
  resources:
    requests:
      storage: 10Gi