apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - ehrbase-ingress
  - etl-zib-rest-ingress
  - federation-rest-ingress
  - openehrtool-ingress
  - portal-ingress
  - transform-rest-ingress
  - secrets
