apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - ehrbase-gateway
  - etl-zib-rest-gateway
  - federation-rest-gateway
  - openehrtool-gateway
  - portal-gateway
  - terminology-server-proxy-gateway
  - transform-rest-gateway
  - secrets
