apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
- name: redis-config
  namespace: dh-health
  files:
  - redis.conf=config/redis.conf