apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: envida-ehrdb-pvc
  namespace: dh-health
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  selector:
    matchLabels:
      app: envida-ehrdb
  volumeName: envida-ehrdb-pv