apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- common/envida-etl-config.yaml
- ehrbase
- ehrdb
- etl-zib
- etl-zib-rest
- openehrtool
- portal


