apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- ehrbase
- ehrdb-deployment.yaml
- ehrdb-service.yaml
- etl-zib-deployment.yaml
- etl-zib-rest-deployment.yaml
- etl-zib-rest-service.yaml
- etl-zib-rest-ingress.yaml
- openehrtool
- portal

configMapGenerator:  
- name: envida-ehrdb-config
  namespace: dh-health
  envs:
  - envida/ehrdb.env

- name: envida-etl-config
  namespace: dh-health
  envs:
  - envida/etl.env

