apiVersion: apps/v1
kind: Deployment
metadata:
  name: envida-portal
  namespace: dh-health
  labels:
    app: envida-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envida-portal
  template:
    metadata:
      labels:
        app: envida-portal
    spec:
      containers:
      - name: envida-portal
        image: registry.prod.dh.unimaas.nl/docker-health/portal:latest
        ports:
        - containerPort: 3000
        env:
          - name: AUTH_USER
            valueFrom:
              secretKeyRef:
                name: envida-portal-creds
                key: username
          - name: AUTH_PASS
            valueFrom:
              secretKeyRef:
                name: envida-portal-creds
                key: password
        envFrom:
        - configMapRef:
            name: envida-portal-config
        - configMapRef:
            name: portal-common-config
