apiVersion: v1
kind: ConfigMap
metadata:
  name: git-config
  namespace: dh-health-envida
data:
  GIT_BRANCH: PLACEHOLDER
---
apiVersion: batch/v1
kind: Job
metadata:
  name: populate-pvc-with-git-repo
  namespace: dh-health-envida
spec:
  template:
    spec:
      containers:
        - name: git-clone
          image: alpine/git:latest
          envFrom:
            - configMapRef:
                name: git-config
          command:
            - sh
            - -c
            - |
              set -e
              echo "Cleaning old repo..."
              rm -rf /repo/src
              echo "Cloning fresh repo into /repo/src"
              git clone https://github.com/MaastrichtUniversity/docker-health.git /repo/src
              cd /repo/src
              git checkout "$GIT_BRANCH"
          volumeMounts:
            - name: git-repo
              mountPath: /repo
      restartPolicy: Never
      volumes:
        - name: git-repo
          persistentVolumeClaim:
            claimName: git-repo-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: git-config
  namespace: dh-health-mumc
data:
  GIT_BRANCH: PLACEHOLDER
---
apiVersion: batch/v1
kind: Job
metadata:
  name: populate-pvc-with-git-repo
  namespace: dh-health-mumc
spec:
  template:
    spec:
      containers:
        - name: git-clone
          image: alpine/git:latest
          envFrom:
            - configMapRef:
                name: git-config
          command:
            - sh
            - -c
            - |
              set -e
              echo "Cleaning old repo..."
              rm -rf /repo/src
              echo "Cloning fresh repo into /repo/src"
              git clone https://github.com/MaastrichtUniversity/docker-health.git /repo/src
              cd /repo/src
              git checkout "$GIT_BRANCH"
          volumeMounts:
            - name: git-repo
              mountPath: /repo
      restartPolicy: Never
      volumes:
        - name: git-repo
          persistentVolumeClaim:
            claimName: git-repo-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: git-config
  namespace: dh-health-vitala
data:
  GIT_BRANCH: PLACEHOLDER
---
apiVersion: batch/v1
kind: Job
metadata:
  name: populate-pvc-with-git-repo
  namespace: dh-health-vitala
spec:
  template:
    spec:
      containers:
        - name: git-clone
          image: alpine/git:latest
          envFrom:
            - configMapRef:
                name: git-config
          command:
            - sh
            - -c
            - |
              set -e
              echo "Cleaning old repo..."
              rm -rf /repo/src
              echo "Cloning fresh repo into /repo/src"
              git clone https://github.com/MaastrichtUniversity/docker-health.git /repo/src
              cd /repo/src
              git checkout "$GIT_BRANCH"
          volumeMounts:
            - name: git-repo
              mountPath: /repo
      restartPolicy: Never
      volumes:
        - name: git-repo
          persistentVolumeClaim:
            claimName: git-repo-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: git-config
  namespace: dh-health-zio
data:
  GIT_BRANCH: PLACEHOLDER
---
apiVersion: batch/v1
kind: Job
metadata:
  name: populate-pvc-with-git-repo
  namespace: dh-health-zio
spec:
  template:
    spec:
      containers:
        - name: git-clone
          image: alpine/git:latest
          envFrom:
            - configMapRef:
                name: git-config
          command:
            - sh
            - -c
            - |
              set -e
              echo "Cleaning old repo..."
              rm -rf /repo/src
              echo "Cloning fresh repo into /repo/src"
              git clone https://github.com/MaastrichtUniversity/docker-health.git /repo/src
              cd /repo/src
              git checkout "$GIT_BRANCH"
          volumeMounts:
            - name: git-repo
              mountPath: /repo
      restartPolicy: Never
      volumes:
        - name: git-repo
          persistentVolumeClaim:
            claimName: git-repo-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: git-config
  namespace: dh-health-jupyter
data:
  GIT_BRANCH: PLACEHOLDER
---
apiVersion: batch/v1
kind: Job
metadata:
  name: populate-pvc-with-git-repo
  namespace: dh-health-jupyter
spec:
  template:
    spec:
      containers:
        - name: git-clone
          image: alpine/git:latest
          envFrom:
            - configMapRef:
                name: git-config
          command:
            - sh
            - -c
            - |
              set -e
              echo "Cleaning old repo..."
              rm -rf /repo/src
              echo "Cloning fresh repo into /repo/src"
              git clone https://github.com/MaastrichtUniversity/docker-health.git /repo/src
              cd /repo/src
              git checkout "$GIT_BRANCH"
          volumeMounts:
            - name: git-repo
              mountPath: /repo
      restartPolicy: Never
      volumes:
        - name: git-repo
          persistentVolumeClaim:
            claimName: git-repo-pvc
