apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: elk-gateway
  namespace: dh-health-ops
spec:
  gatewayClassName: traefik
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      hostname: elk-hdp.tst.dh.unimaas.nl
    #- name: https
    #  port: 443
    #  protocol: HTTPS
    #  hostname: elk-hdp.tst.dh.unimaas.nl
    #  Needs TLS configuration
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: elk-route
  namespace: dh-health-ops
spec:
  parentRefs:
    - name: elk-gateway
  hostnames:
    - elk-hdp.tst.dh.unimaas.nl
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: elk
          port: 5601
