apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dh-health-ops

resources:
- namespace.yaml
- secrets.yaml
- elk-gateway.yaml
- ../../../base-ops

images:
- name: registry.prod.dh.unimaas.nl/docker-health/elk
  newTag: '2026.1.1'

secretGenerator:
# Filebeat
  - name: filebeat-certificate-authorities
    files:
        -  certs/ca.crt
  - name: filebeat-certificate
    files:
        -  certs/filebeat.dh-health-ops.crt
  - name: filebeat-key
    files:
        -  certs/filebeat.dh-health-ops.key
# Logstash (ELK)
  - name: logstash-certificate-authorities
    files:
        -  certs/ca.crt
  - name: logstash-certificate
    files:
        -  certs/elk.dh-health-ops.crt
  - name: logstash-key
    files:
        -  certs/elk.dh-health-ops.key

patches:
  - path: filebeat-configmap-patch.yaml
    target:
      kind: ConfigMap
      name: filebeat-config
  # 'Global' patches that apply to all of one sort
  # Storage class patches
  - target:
      kind: PersistentVolume
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: local-path
  - target:
      kind: PersistentVolumeClaim
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: local-path
  # Image pull secret patches
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/imagePullSecrets
        value:
        - name: registry-credentials
  # imagePullPolicy patches
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
  # Proxy patches
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/envFrom/-"
        value:
          configMapRef:
            name: proxy-config

configMapGenerator:
- name: proxy-config
  literals:
    - HTTP_PROXY=http://proxy.unimaas.nl:3128
    - http_proxy=http://proxy.unimaas.nl:3128
    - HTTPS_PROXY=http://proxy.unimaas.nl:3128
    - https_proxy=http://proxy.unimaas.nl:3128
    - NO_PROXY=localhost,.dh.local,.dh-health,.unimaas.nl,.datahubmaastricht.nl,137.120.31.0/24,.cluster.local,10.42.0.0/12,10.43.0.0/12,10.43.0.10,10.43.0.1
    - no_proxy=localhost,.dh.local,.dh-health,.unimaas.nl,.datahubmaastricht.nl,137.120.31.0/24,.cluster.local,10.42.0.0/12,10.43.0.0/12,10.43.0.10,10.43.0.1