apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: registry-credentials
  namespace: dh-health-ops
spec:
  refreshInterval: 168h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: registry-credentials
    template:
      engineVersion: v2
      data:
        .dockerconfigjson: "{{ .dockerconfigjson }}"
  dataFrom:
    - extract:
        key: hdp-env/registry-credentials