apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: elk-tls-secret
  namespace: dh-health-ops
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: elk-tls-secret
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .elk_pem }}"
        tls.key: "{{ .elk_key }}"
  data:
  - secretKey: elk_pem
    remoteRef:
      key: fhml-srv018__tst-k3s-hdp
      property: elk-hdp.tst.dh.unimaas.nl.pem
  - secretKey: elk_key
    remoteRef:
      key: fhml-srv018__tst-k3s-hdp
      property: elk-hdp.tst.dh.unimaas.nl.key