apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: federation-tls-secret
  namespace: dh-health
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: prod-vault.dev-test
    kind: ClusterSecretStore
  target:
    name: federation-tls-secret
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .federation.tst.dh.unimaas.nl.crt }}"
        tls.key: "{{ .federation.tst.dh.unimaas.nl.key }}"

  data:
  - secretKey: federation.tst.dh.unimaas.nl.crt
    remoteRef:
      key: fhml-srv018__tst-k3s-hdp
      property: federation.tst.dh.unimaas.nl.crt
  - secretKey: federation.tst.dh.unimaas.nl.key
    remoteRef:
      key: fhml-srv018__tst-k3s-hdp
      property: federation.tst.dh.unimaas.nl.key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jupyter-tls-secret
  namespace: dh-health
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: prod-vault.dev-test
    kind: ClusterSecretStore
  target:
    name: jupyter-tls-secret
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .jupyter.tst.dh.unimaas.nl.crt }}"
        tls.key: "{{ .jupyter.tst.dh.unimaas.nl.key }}"

  data:
  - secretKey: jupyter.tst.dh.unimaas.nl.crt
    remoteRef:
      key: fhml-srv018__tst-k3s-hdp
      property: jupyter.tst.dh.unimaas.nl.crt
  - secretKey: jupyter.tst.dh.unimaas.nl.key
    remoteRef:
      key: fhml-srv018__tst-k3s-hdp
      property: jupyter.tst.dh.unimaas.nl.key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: transform-tls-secret
  namespace: dh-health
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: prod-vault.dev-test
    kind: ClusterSecretStore
  target:
    name: jupyter-tls-secret
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .transform.tst.dh.unimaas.nl.crt }}"
        tls.key: "{{ .transform.tst.dh.unimaas.nl.key }}"

  data:
  - secretKey: transform.tst.dh.unimaas.nl.crt
    remoteRef:
      key: fhml-srv018__tst-k3s-hdp
      property: transform.tst.dh.unimaas.nl.crt
  - secretKey: transform.tst.dh.unimaas.nl.key
    remoteRef:
      key: fhml-srv018__tst-k3s-hdp
      property: transform.tst.dh.unimaas.nl.key