apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: portal-envida-tls-secret
  namespace: dh-health
spec:
  refreshInterval: 1d
  secretStoreRef:
    name: prod-vault.tst
    kind: SecretStore
  target:
    name: portal-envida-tls-secret
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .portal_envida_crt }}"
        tls.key: "{{ .portal_envida_key }}"

  data:
  - secretKey: portal_envida_crt
    remoteRef:
      key: fhml-srv018__tst-k3s-hdp
      property: portal.envida.tst.dh.unimaas.nl.crt
  - secretKey: portal_envida_key
    remoteRef:
      key: fhml-srv018__tst-k3s-hdp
      property: portal.envida.tst.dh.unimaas.nl.key