apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: portal-mumc-tls-secret
  namespace: dh-health
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: SecretStore
  target:
    name: portal-mumc-tls-secret
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .portal_mumc_crt }}"
        tls.key: "{{ .portal_mumc_key }}"

  data:
  - secretKey: portal_mumc_crt
    remoteRef:
      key: fhml-srv018__tst-k3s-hdp
      property: portal.mumc.tst.dh.unimaas.nl.crt
  - secretKey: portal_mumc_key
    remoteRef:
      key: fhml-srv018__tst-k3s-hdp
      property: portal.mumc.tst.dh.unimaas.nl.key