apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terminology-server-proxy-creds
  labels:
    ehrnode: all
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: terminology-server-proxy-creds
    template:
      engineVersion: v2
      data:
        username: "datahub@maastrichtuniversity.nl"
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: hdp-env/terminology-server-proxy-creds
      property: datahub@maastrichtuniversity.nl