apiVersion: batch/v1
kind: Job
metadata:
  name: etl-zib-pipeline
spec:
  template:
    spec:
      containers:
        - name: etl-zib-pipeline
          volumeMounts:
            - name: data
              mountPath: /code/data/envida-demo-data
              $patch: delete
      volumes:
        - name: data
          $patch: delete