apiVersion: v1
kind: ConfigMap
metadata:
  name: zio-etl-config
  namespace: dh-health
data:
  NODENAME: zio
  DATASET_FOLDER_NAME: zio-demo-data
  SOURCE_SYSTEM_ID: Tetra
  INPUT_FORMAT: csv
  LOGGER_FILENAME: logs/zio/etl-zib.log
  EHRBASE_BASE_URL: http://zio-ehrbase.dh-health:8080/ehrbase/rest/openehr/v1
  TRANSFORM_SPRING_BASE_URL: http://zio-transform-rest.dh-health:8080
  WRITE_COMPOSITION: "true"
  # If SUBJECT_IDS is empty, extract subject_ids from dataset:
  SUBJECT_IDS: |
    []
  TEMPLATE_IDS: |
    [
      "DataHub-InformedConsent",
      "DataHub-Bloeddruk-2024",
      "DataHub-Lichaamsgewicht-2024",
      "DataHub-Lichaamslengte-2024",
      "DataHub-Patient-2024"
    ]
