apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pv-zio
  namespace: dh-health-zio
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: log-pvc-zio
    namespace: dh-health-zio
  hostPath:
    path: /usr/share/logs/zio
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pvc-zio
  namespace: dh-health-zio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: output-pv-zio
  namespace: dh-health-zio
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: output-pvc-zio
    namespace: dh-health-zio
  hostPath:
    path: /usr/share/outputs/zio
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-pvc-zio
  namespace: dh-health-zio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data-pv-zio
  namespace: dh-health-zio
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: postgresql-data-pvc-zio
    namespace: dh-health-zio
  hostPath:
    path: /usr/share/postgresql_data/zio
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data-pvc-zio
  namespace: dh-health-zio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi