apiVersion: v1
kind: Service
metadata:
  name: transform-rest
  namespace: dh-health
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: transform-rest