apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

configMapGenerator:
- name: test-openehrtool-config
  namespace: dh-health
  literals:
    - EHRBASESERVER_hostname=test-ehrbase.dh-health
    - EHRBASESERVER_nodename=test.server.dh.unimaas.nl