apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
  - name: ehrbase-creds
    literals:
      - username=user1
      - password=foobar1
  - name: ehrbase-admin-creds
    literals:
      - username=admin1
      - password=admin1
  - name: ehrbase-db-admin-creds
    literals:
      - username=ehrbase1
      - password=ehrbase1
  - name: ehrbase-db-creds
    literals:
      - username=ehrbase_restricted1
      - password=ehrbase_restricted1
  - name: portal-creds
    literals:
      - username=demo@mumc.nl
      - password=foobar
  - name: federation-key
    literals:
      - key=key1
  - name: federation-break-the-glass-key
    literals:
      - key=btgkey1
  - name: ehrbase-db-postgres-creds
    literals:
      - username=postgres
      - password=postgres
  - name: transform-creds
    literals:
      - username=transform1
      - password=transform1
