apiVersion: v1
kind: ConfigMap
metadata:
  name: zio-transform-rest-config
data:
  TERMINOLOGY_BASE_URL: http://zio-terminology-server-proxy.dh-health-zio:8080
  LOGGER_FILENAME: /var/log/zio/transform-rest.log
