apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../test-single-node

configMapGenerator:
  - name: proxy-config
    namespace: dh-health-test-single-node
    options:
      disableNameSuffixHash: true
    envs:
      - ../../../base-config/proxy.env

patches:
  - target:
      kind: Deployment
      name: .*terminology-server-proxy
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom/-
        value:
          configMapRef:
            name: proxy-config
  - target:
      kind: Job
      name: test-single-node
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom/-
        value:
          configMapRef:
            name: proxy-config
