apiVersion: batch/v1
kind: Job
metadata:
  name: test-federation
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-etl-jobs
          image: bitnamilegacy/kubectl:1.33.4 # TODO: Try not to use a third-party docker image
          imagePullPolicy: Never
          command:
                 - /bin/bash
                 - -c
                 - |                                                                                                                                                                                                                                                                                               
                   set -e                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                   
                   # -----------------------------------------------------------------                                                                                                                                                                                                                             
                   # Find every job in *any* namespace whose name ends with                                                                                                                                                                                                                                        
                   #   etl-zib-pipeline                                                                                                                                                                                                                                                                            
                   # -----------------------------------------------------------------                                                                                                                                                               
                   JOBS=$(kubectl get jobs -A -o jsonpath='{range .items[*]}{.metadata.namespace}{" "}{.metadata.name}{"\n"}{end}' |  grep 'etl-zib-pipeline$')   

                   if [[ -z "$JOBS" ]]; then                                                                                                                                                                                                                                                                       
                     echo "No matching etl‑zib‑pipeline jobs found in any namespace."                                                                                                                                                                                                                              
                     exit 0                                                                                                                                                                                                                                                                                        
                   fi                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                   
                   # -----------------------------------------------------------------                                                                                                                                                                                                                             
                   # Process each <namespace> <job> pair                                                                                                                                                                                                                                                           
                   # -----------------------------------------------------------------                                                                                                                                                                                                                             
                   while read -r ns job; do                                                                                                                                                                                                                                                                        
                     echo "Waiting for job $job in namespace $ns..."                                                                                                                                                                                                                                               
                                                                                                                                                                                                                           
                     # Wait until the job succeeds or fails                                                                                                                                                                                                                                                        
                     while true; do                                                                                                                                                                                                                                                                                
                       succeeded=$(kubectl get job "$job" -n "$ns" -o jsonpath='{.status.succeeded}')                                                                                                                                                                                                              
                       if [[ "$succeeded" == "1" ]]; then                                                                                                                                                                                                                                                          
                         echo "$job in $ns is complete"                                                                                                                                                                                                                                                            
                         break                                                                                                                                                                                                                                                                                     
                       fi                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                             
                       failed=$(kubectl get job "$job" -n "$ns" -o jsonpath='{.status.failed}')                                                                                                                                                                                                                    
                       if [ "$failed" != "" ] && [ "$failed" -ge 1 ]; then                                                                                                                                                                                                                                            
                         echo "❌  $job in $ns has failed. Exiting."                                                                                                                                                                                                                                                
                         exit 1                                                                                                                                                                                                                                                                                    
                       fi                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                               
                       echo "$job in $ns not completed yet, sleeping 10s..."                                                                                                                                                                                                                                       
                       sleep 10                                                                                                                                                                                                                                                                                    
                     done                                                                                                                                                                                                                                                                                          
                   done <<< "$JOBS"
                   exit 0
        - name: query-federation-services
          image: python:3.12-slim
          imagePullPolicy: IfNotPresent
          env:
            - name: X_API_KEY
              valueFrom:
                secretKeyRef:
                  name: federation-service-creds
                  key: key
          command:
            - /bin/bash
            - -c
            - |                                                                                                                
              pip install --quiet httpx   
              echo "Starting!"
              # -----------------------------------------------------------------                                                                                                       
              # Python query‑readiness check for each federation node                                                                                                                   
              # -----------------------------------------------------------------       
              time python - <<'PY'                                                                                                                                            
              import asyncio, time, os, httpx

              service_headers = {"X-API-Key": os.getenv("X_API_KEY")}
              
              
              async def wait_until_query_ready(client, node):
                  consecutive_successes = 0
                  max_retries = 20
                  while consecutive_successes < 2 and max_retries > 0:
                      started = time.monotonic()
                      try:
                          response = await client.get(
                              f"http://federation-rest.dh-health-{node}:8000/own-data/query",
                              params={"query": "SELECT COUNT(e/ehr_id/value) FROM EHR e"},
                              headers=service_headers,
                              timeout=5,
                          )
                          max_retries -= 1
                          duration = time.monotonic() - started
                          if response.status_code == 200 and duration < 2:
                              consecutive_successes += 1
                          else:
                              consecutive_successes = 0
                          print(f"consecutive_successes '{consecutive_successes}' for node {node}")
                      except httpx.HTTPError:
                          consecutive_successes = 0
                          print(f"HTTPError for node {node}")
                      if consecutive_successes < 2:
                          print(f"Sleep for node {node}")
                          await asyncio.sleep(2)
                  if max_retries == 0:
                      raise RuntimeError(f"Max number of retries reached")
 
              
              async def main():
                  nodes = ["envida", "mumc", "vitala", "zio"]
                  async with httpx.AsyncClient() as client:
                      for n in nodes:
                          await wait_until_query_ready(client, n)
              
              
              if __name__ == "__main__":
                  asyncio.run(main())                                                                                                                                                  
              PY
              echo "Done!"
      containers:
        - name: test-federation-runner
          image: registry.prod.dh.unimaas.nl/docker-health/federation-test:latest
          envFrom:
            - configMapRef:
                name: timezone-config
          env:
            # ENVIDA-node
            - name: ENVIDA__NODENAME
              valueFrom:
                configMapKeyRef:
                  name: envida-etl-config-node
                  key: NODENAME
            - name: ENVIDA__FEDERATION_KEY
              valueFrom:
                secretKeyRef:
                  name: envida-federation-key
                  key: key
            - name: ENVIDA__FEDERATION_BTG_KEY
              valueFrom:
                secretKeyRef:
                  name: envida-federation-break-the-glass-key
                  key: key
            - name: ENVIDA__FEDERATION_BASE_URL
              value: "http://federation-rest.dh-health-envida:8000"
            # MUMC-node
            - name: MUMC__NODENAME
              valueFrom:
                configMapKeyRef:
                  name: mumc-etl-config-node
                  key: NODENAME
            - name: MUMC__FEDERATION_KEY
              valueFrom:
                secretKeyRef:
                  name: mumc-federation-key
                  key: key
            - name: MUMC__FEDERATION_BTG_KEY
              valueFrom:
                secretKeyRef:
                  name: mumc-federation-break-the-glass-key
                  key: key
            - name: MUMC__FEDERATION_BASE_URL
              value: "http://federation-rest.dh-health-mumc:8000"
            # VITALA-node
            - name: VITALA__NODENAME
              valueFrom:
                configMapKeyRef:
                  name: vitala-etl-config-node
                  key: NODENAME
            - name: VITALA__FEDERATION_KEY
              valueFrom:
                secretKeyRef:
                  name: vitala-federation-key
                  key: key
            - name: VITALA__FEDERATION_BTG_KEY
              valueFrom:
                secretKeyRef:
                  name: vitala-federation-break-the-glass-key
                  key: key
            - name: VITALA__FEDERATION_BASE_URL
              value: "http://federation-rest.dh-health-vitala:8000"
            # ZIO-node
            - name: ZIO__NODENAME
              valueFrom:
                configMapKeyRef:
                  name: zio-etl-config-node
                  key: NODENAME
            - name: ZIO__FEDERATION_KEY
              valueFrom:
                secretKeyRef:
                  name: zio-federation-key
                  key: key
            - name: ZIO__FEDERATION_BTG_KEY
              valueFrom:
                secretKeyRef:
                  name: zio-federation-break-the-glass-key
                  key: key
            - name: ZIO__FEDERATION_BASE_URL
              value: "http://federation-rest.dh-health-zio:8000"