apiVersion: v1
kind: ConfigMap
metadata:
  name: vitala-transform-rest-config
data:
  TERMINOLOGY_BASE_URL: http://vitala-terminology-server-proxy.dh-health-vitala:8080
  LOGGER_FILENAME: /var/log/vitala/transform-rest.log
