apiVersion: apps/v1
kind: Deployment
metadata:
  name: transform-rest-vitala
  namespace: dh-health
  labels:
    app: transform-rest-vitala
spec:
  selector:
    matchLabels:
      app: transform-rest-vitala
  template:
    metadata:
      labels:
        app: transform-rest-vitala
    spec:
      containers:
      - name: transform-rest
        image: registry.prod.dh.unimaas.nl/docker-health/transform-rest:latest
        ports:
        - containerPort: 8080
        env:
          - name: TRANSFORM_SPRING_USERNAME
            valueFrom:
              secretKeyRef:
                name: vitala-transform-creds
                key: username
          - name: TRANSFORM_SPRING_PASSWORD
            valueFrom:
              secretKeyRef:
                name: vitala-transform-creds
                key: password
        envFrom:
        - configMapRef:
            name: timezone-config
        - configMapRef:
            name: vitala-transform-server-config
        - configMapRef:
            name: zib-templates-config
