apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- ../../../base/elk

patches:
# imagePullPolicy patches
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Never

# Individual ingress host patches
## ELK (Kibana)
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: elk-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: elk.local.dh.unimaas.nl
