apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dh-health-vitala

resources:
  - vault-auth.yaml
  - ../../../base-config/proxy
  - ../../../base/openehr-nodes/vitala/ehrbase
  - ../../../base/openehr-nodes/vitala/ehrdb
  - ../../../base/openehr-nodes/vitala/etl-zib
  - ../../../base/openehr-nodes/vitala/federation-rest
  - ../../../base/openehr-nodes/vitala/openehrtool
  - ../../../base/openehr-nodes/vitala/portal
  - ../../../base/openehr-nodes/vitala/terminology-server-proxy
  - ../../../base/openehr-nodes/vitala/transform-rest
  - volumes.yaml
  - config
  - service-discovery

components:
  - components
  - ../shared-components

patches:
  - target:
      group: batch
      version: v1
      kind: Job
      name: etl-zib-pipeline
    patch: |
      - op: replace
        path: /spec/template/spec/volumes/1/hostPath/path
        value: /mnt/demo-data/data/vitala-demo-data
      - op: replace
        path: /spec/template/spec/volumes/1/hostPath/type
        value: DirectoryOrCreate