---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pv-vitala
  namespace: dh-health-vitala
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nfs-vitala-logs
    volumeAttributes:
      server: fhml-srv017.unimaas.nl
      share: /bkp/tst-k3s/logs/vitala
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pvc-vitala
  namespace: dh-health-vitala
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi
  volumeName: log-pv-vitala
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: output-pv-vitala
  namespace: dh-health-vitala
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nfs-vitala-outputs
    volumeAttributes:
      server: fhml-srv017.unimaas.nl
      share: /bkp/tst-k3s/outputs/vitala
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-pvc-vitala
  namespace: dh-health-vitala
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi
  volumeName: output-pv-vitala
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data-pv-vitala
  namespace: dh-health-vitala
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-retain
  csi:
    driver: driver.longhorn.io
    volumeHandle: postgresql-data-vitala
    volumeAttributes:
      numberOfReplicas: "3"
      staleReplicaTimeout: "2880"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data-pvc-vitala
  namespace: dh-health-vitala
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-retain
  volumeName: postgresql-data-pv-vitala