apiVersion: apps/v1
kind: Deployment
metadata:
  name: vitala-openehrtool
  namespace: dh-health
  labels:
    app: vitala-openehrtool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vitala-openehrtool
  template:
    metadata:
      labels:
        app: vitala-openehrtool
    spec:
      containers:
      - name: vitala-openehrtool
        image: surfercrs4/openehrtool:latest
        ports:
        - containerPort: 9000
        env:
          - name: EHRBASEUSERS_adusername
            valueFrom:
              secretKeyRef:
                name: vitala-ehrbase-admin-creds
                key: username
          - name: EHRBASEUSERS_adpassword
            valueFrom:
              secretKeyRef:
                name: vitala-ehrbase-admin-creds
                key: password
          - name: EHRBASEUSERS_username
            valueFrom:
              secretKeyRef:
                name: vitala-ehrbase-creds
                key: username
          - name: EHRBASEUSERS_password
            valueFrom:
              secretKeyRef:
                name: vitala-ehrbase-creds
                key: password
        envFrom:
        - configMapRef:
            name: openehrtool-config
        - configMapRef:
            name: vitala-openehrtool-config