apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mumc-portal-ingress
  namespace: dh-health
spec:
  rules:
    - host: portal.mumc.tst.dh.unimaas.nl
  tls:
    - hosts:
        - portal.mumc.tst.dh.unimaas.nl
      secretName: portal-mumc-tls-secret