apiVersion: v1
kind: ConfigMap
metadata:
  name: zib-templates-config
  namespace: dh-health
data:
  ETL_PROJECT_NAME: "zib"
  SUBJECT_NAMESPACE: "bsn"
  LOGSTASH_TAGS: ETL_ZIB

  TEMPLATES__PATIENT2024__ID: "DataHub-Patient-2024"
  TEMPLATES__PATIENT2024__SEM_VER: "0.1.0"
  TEMPLATES__ALCOHOLGEBRUIK2023__ID: "DataHub-AlcoholGebruik-2023"
  TEMPLATES__ALCOHOLGEBRUIK2023__SEM_VER: "0.1.0"
  TEMPLATES__ALCOHOLGEBRUIK2017__ID: "DataHub-AlcoholGebruik-2017"
  TEMPLATES__ALCOHOLGEBRUIK2017__SEM_VER: "0.1.0"
  TEMPLATES__BURGERLIJKESTAAT2024__ID: "DataHub-BurgerlijkeStaat-2024"
  TEMPLATES__BURGERLIJKESTAAT2024__SEM_VER: "0.1.0"
  TEMPLATES__BURGERLIJKESTAAT2023__ID: "DataHub-BurgerlijkeStaat-2023"
  TEMPLATES__BURGERLIJKESTAAT2023__SEM_VER: "0.1.0"
  TEMPLATES__BURGERLIJKESTAAT2017__ID: "DataHub-BurgerlijkeStaat-2017"
  TEMPLATES__BURGERLIJKESTAAT2017__SEM_VER: "0.1.0"
  TEMPLATES__CONTACTPERSOON2017__ID: "DataHub-Contactpersoon-2017"
  TEMPLATES__CONTACTPERSOON2017__SEM_VER: "0.1.0"
  TEMPLATES__WOONSITUATIE2017__ID: "DataHub-Woonsituatie-2017"
  TEMPLATES__WOONSITUATIE2017__SEM_VER: "0.1.0"
  TEMPLATES__VERMOGENTOTZICHWASSEN2020__ID: "DataHub-VermogenTotZichWassen-2020"
  TEMPLATES__VERMOGENTOTZICHWASSEN2020__SEM_VER: "0.1.0"
  TEMPLATES__VERMOGENTOTZICHKLEDEN2020__ID: "DataHub-VermogenTotZichKleden-2020"
  TEMPLATES__VERMOGENTOTZICHKLEDEN2020__SEM_VER: "0.1.0"
  TEMPLATES__VERMOGENTOTUITERLIJKEVERZORGING2020__ID: "DataHub-VermogenTotUiterlijkeVerzorging-2020"
  TEMPLATES__VERMOGENTOTUITERLIJKEVERZORGING2020__SEM_VER: "0.1.0"
  TEMPLATES__VERMOGENTOTZELFSTANDIGMEDICATIEGEBRUIK2020__ID: "DataHub-VermogenTotZelfstandigMedicatiegebruik-2020"
  TEMPLATES__VERMOGENTOTZELFSTANDIGMEDICATIEGEBRUIK2020__SEM_VER: "0.1.0"
  TEMPLATES__VERMOGENTOTETEN2020__ID: "DataHub-VermogenTotEten-2020"
  TEMPLATES__VERMOGENTOTETEN2020__SEM_VER: "0.1.0"
  TEMPLATES__VERMOGENTOTDRINKEN2020__ID: "DataHub-VermogenTotDrinken-2020"
  TEMPLATES__VERMOGENTOTDRINKEN2020__SEM_VER: "0.1.0"
  TEMPLATES__VERMOGENTOTMONDVERZORGING2020__ID: "DataHub-VermogenTotMondverzorging-2020"
  TEMPLATES__VERMOGENTOTMONDVERZORGING2020__SEM_VER: "0.1.0"
  TEMPLATES__VERMOGENTOTTOILETGANG2020__ID: "DataHub-VermogenTotToiletgang-2020"
  TEMPLATES__VERMOGENTOTTOILETGANG2020__SEM_VER: "0.1.0"
  TEMPLATES__INFORMEDCONSENT__ID: "DataHub-InformedConsent"
  TEMPLATES__INFORMEDCONSENT__SEM_VER: "0.1.1"

  TEMPLATES__PATIENT2024__API_ROUTE: "zib/Patient2024"
  TEMPLATES__PATIENT2024__FILENAME: "data/templates/2024/DataHub-Patient-2024.opt"
  TEMPLATES__ALCOHOLGEBRUIK2023__API_ROUTE: "zib/AlcoholGebruik2023"
  TEMPLATES__ALCOHOLGEBRUIK2023__FILENAME: "data/templates/2023/DataHub-AlcoholGebruik-2023.opt"
  TEMPLATES__ALCOHOLGEBRUIK2017__API_ROUTE: "zib/AlcoholGebruik2017"
  TEMPLATES__ALCOHOLGEBRUIK2017__FILENAME: "data/templates/2017/DataHub-AlcoholGebruik-2017.opt"
  TEMPLATES__BURGERLIJKESTAAT2024__API_ROUTE: "zib/BurgerlijkeStaat2024"
  TEMPLATES__BURGERLIJKESTAAT2024__FILENAME: "data/templates/2024/DataHub-BurgerlijkeStaat-2024.opt"
  TEMPLATES__BURGERLIJKESTAAT2023__API_ROUTE: "zib/BurgerlijkeStaat2023"
  TEMPLATES__BURGERLIJKESTAAT2023__FILENAME: "data/templates/2023/DataHub-BurgerlijkeStaat-2023.opt"
  TEMPLATES__BURGERLIJKESTAAT2017__API_ROUTE: "zib/BurgerlijkeStaat2017"
  TEMPLATES__BURGERLIJKESTAAT2017__FILENAME: "data/templates/2017/DataHub-BurgerlijkeStaat-2017.opt"
  TEMPLATES__CONTACTPERSOON2017__API_ROUTE: "zib/Contactpersoon2017"
  TEMPLATES__CONTACTPERSOON2017__FILENAME: "data/templates/2017/DataHub-Contactpersoon-2017.opt"
  TEMPLATES__WOONSITUATIE2017__API_ROUTE: "zib/Woonsituatie2017"
  TEMPLATES__WOONSITUATIE2017__FILENAME: "data/templates/2017/DataHub-Woonsituatie-2017.opt"
  TEMPLATES__VERMOGENTOTZICHWASSEN2020__API_ROUTE: "zib/VermogenTotZichWassen2020"
  TEMPLATES__VERMOGENTOTZICHWASSEN2020__FILENAME: "data/templates/2020/DataHub-VermogenTotZichWassen-2020.opt"
  TEMPLATES__VERMOGENTOTZICHKLEDEN2020__API_ROUTE: "zib/VermogenTotZichKleden2020"
  TEMPLATES__VERMOGENTOTZICHKLEDEN2020__FILENAME: "data/templates/2020/DataHub-VermogenTotZichKleden-2020.opt"
  TEMPLATES__VERMOGENTOTUITERLIJKEVERZORGING2020__API_ROUTE: "zib/VermogenTotUiterlijkeVerzorging2020"
  TEMPLATES__VERMOGENTOTUITERLIJKEVERZORGING2020__FILENAME: "data/templates/2020/DataHub-VermogenTotUiterlijkeVerzorging-2020.opt"
  TEMPLATES__VERMOGENTOTZELFSTANDIGMEDICATIEGEBRUIK2020__API_ROUTE: "zib/VermogenTotZelfstandigMedicatiegebruik2020"
  TEMPLATES__VERMOGENTOTZELFSTANDIGMEDICATIEGEBRUIK2020__FILENAME: "data/templates/2020/DataHub-VermogenTotZelfstandigMedicatiegebruik-2020.opt"
  TEMPLATES__VERMOGENTOTETEN2020__API_ROUTE: "zib/VermogenTotEten2020"
  TEMPLATES__VERMOGENTOTETEN2020__FILENAME: "data/templates/2020/DataHub-VermogenTotEten-2020.opt"
  TEMPLATES__VERMOGENTOTDRINKEN2020__API_ROUTE: "zib/VermogenTotDrinken2020"
  TEMPLATES__VERMOGENTOTDRINKEN2020__FILENAME: "data/templates/2020/DataHub-VermogenTotDrinken-2020.opt"
  TEMPLATES__VERMOGENTOTMONDVERZORGING2020__API_ROUTE: "zib/VermogenTotMondverzorging2020"
  TEMPLATES__VERMOGENTOTMONDVERZORGING2020__FILENAME: "data/templates/2020/DataHub-VermogenTotMondverzorging-2020.opt"
  TEMPLATES__VERMOGENTOTTOILETGANG2020__API_ROUTE: "zib/VermogenTotToiletgang2020"
  TEMPLATES__VERMOGENTOTTOILETGANG2020__FILENAME: "data/templates/2020/DataHub-VermogenTotToiletgang-2020.opt"
  TEMPLATES__INFORMEDCONSENT__API_ROUTE: "zib/InformedConsent"
  TEMPLATES__INFORMEDCONSENT__FILENAME: "data/templates/DataHub-InformedConsent.opt"
