apiVersion: v1
kind: ConfigMap
metadata:
  name: zib-templates-config
  namespace: dh-health
data:
  ETL_PROJECT_NAME: "zib"
  SUBJECT_NAMESPACE: "bsn"
  LOGSTASH_TAGS: ETL_ZIB
  DRY_RUN: "False"

  TEMPLATES__ALCOHOLGEBRUIK2024__ID: "DataHub-AlcoholGebruik-2024"
  TEMPLATES__ALCOHOLGEBRUIK2024__SEM_VER: "0.1.0"
  TEMPLATES__ALCOHOLGEBRUIK2024__API_ROUTE: "zib/AlcoholGebruik2024"
  TEMPLATES__ALCOHOLGEBRUIK2024__FILENAME: "data/templates/DataHub-AlcoholGebruik-2024.opt"
  TEMPLATES__BLOEDDRUK2024__ID: "DataHub-Bloeddruk-2024"
  TEMPLATES__BLOEDDRUK2024__SEM_VER: "0.1.0"
  TEMPLATES__BLOEDDRUK2024__API_ROUTE: "zib/Bloeddruk2024"
  TEMPLATES__BLOEDDRUK2024__FILENAME: "data/templates/DataHub-Bloeddruk-2024.opt"
  TEMPLATES__BURGERLIJKESTAAT2024__ID: "DataHub-BurgerlijkeStaat-2024"
  TEMPLATES__BURGERLIJKESTAAT2024__SEM_VER: "0.1.0"
  TEMPLATES__BURGERLIJKESTAAT2024__API_ROUTE: "zib/BurgerlijkeStaat2024"
  TEMPLATES__BURGERLIJKESTAAT2024__FILENAME: "data/templates/DataHub-BurgerlijkeStaat-2024.opt"
  TEMPLATES__CONTACTPERSOON2024__ID: "DataHub-Contactpersoon-2024"
  TEMPLATES__CONTACTPERSOON2024__SEM_VER: "0.1.0"
  TEMPLATES__CONTACTPERSOON2024__API_ROUTE: "zib/Contactpersoon2024"
  TEMPLATES__CONTACTPERSOON2024__FILENAME: "data/templates/DataHub-Contactpersoon-2024.opt"
  TEMPLATES__GEZINSSITUATIE2024__ID: "DataHub-Gezinssituatie-2024"
  TEMPLATES__GEZINSSITUATIE2024__SEM_VER: "0.1.0"
  TEMPLATES__GEZINSSITUATIE2024__API_ROUTE: "zib/Gezinssituatie2024"
  TEMPLATES__GEZINSSITUATIE2024__FILENAME: "data/templates/DataHub-Gezinssituatie-2024.opt"
  TEMPLATES__INFORMEDCONSENT__ID: "DataHub-InformedConsent"
  TEMPLATES__INFORMEDCONSENT__SEM_VER: "0.1.1"
  TEMPLATES__INFORMEDCONSENT__API_ROUTE: "zib/InformedConsent"
  TEMPLATES__INFORMEDCONSENT__FILENAME: "data/templates/DataHub-InformedConsent.opt"
  TEMPLATES__LICHAAMSGEWICHT2024__ID: "DataHub-Lichaamsgewicht-2024"
  TEMPLATES__LICHAAMSGEWICHT2024__SEM_VER: "0.1.0"
  TEMPLATES__LICHAAMSGEWICHT2024__API_ROUTE: "zib/Lichaamsgewicht2024"
  TEMPLATES__LICHAAMSGEWICHT2024__FILENAME: "data/templates/DataHub-Lichaamsgewicht-2024.opt"
  TEMPLATES__LICHAAMSLENGTE2024__ID: "DataHub-Lichaamslengte-2024"
  TEMPLATES__LICHAAMSLENGTE2024__SEM_VER: "0.1.0"
  TEMPLATES__LICHAAMSLENGTE2024__API_ROUTE: "zib/Lichaamslengte2024"
  TEMPLATES__LICHAAMSLENGTE2024__FILENAME: "data/templates/DataHub-Lichaamslengte-2024.opt"
  TEMPLATES__MOBILITEIT2024__ID: "DataHub-Mobiliteit-2024"
  TEMPLATES__MOBILITEIT2024__SEM_VER: "0.1.0"
  TEMPLATES__MOBILITEIT2024__API_ROUTE: "zib/Mobiliteit2024"
  TEMPLATES__MOBILITEIT2024__FILENAME: "data/templates/DataHub-Mobiliteit-2024.opt"
  TEMPLATES__PATIENT2024__ID: "DataHub-Patient-2024"
  TEMPLATES__PATIENT2024__SEM_VER: "0.2.0"
  TEMPLATES__PATIENT2024__API_ROUTE: "zib/Patient2024"
  TEMPLATES__PATIENT2024__FILENAME: "data/templates/DataHub-Patient-2024.opt"
  TEMPLATES__TABAKGEBRUIK2024__ID: "DataHub-TabakGebruik-2024"
  TEMPLATES__TABAKGEBRUIK2024__SEM_VER: "0.1.0"
  TEMPLATES__TABAKGEBRUIK2024__API_ROUTE: "zib/TabakGebruik2024"
  TEMPLATES__TABAKGEBRUIK2024__FILENAME: "data/templates/DataHub-TabakGebruik-2024.opt"
  TEMPLATES__VERMOGENTOTDRINKEN2024__ID: "DataHub-VermogenTotDrinken-2024"
  TEMPLATES__VERMOGENTOTDRINKEN2024__SEM_VER: "0.1.0"
  TEMPLATES__VERMOGENTOTDRINKEN2024__API_ROUTE: "zib/VermogenTotDrinken2024"
  TEMPLATES__VERMOGENTOTDRINKEN2024__FILENAME: "data/templates/DataHub-VermogenTotDrinken-2024.opt"
  TEMPLATES__VERMOGENTOTETEN2024__ID: "DataHub-VermogenTotEten-2024"
  TEMPLATES__VERMOGENTOTETEN2024__SEM_VER: "0.1.0"
  TEMPLATES__VERMOGENTOTETEN2024__API_ROUTE: "zib/VermogenTotEten2024"
  TEMPLATES__VERMOGENTOTETEN2024__FILENAME: "data/templates/DataHub-VermogenTotEten-2024.opt"
  TEMPLATES__VERMOGENTOTMONDVERZORGING2024__ID: "DataHub-VermogenTotMondverzorging-2024"
  TEMPLATES__VERMOGENTOTMONDVERZORGING2024__SEM_VER: "0.1.0"
  TEMPLATES__VERMOGENTOTMONDVERZORGING2024__API_ROUTE: "zib/VermogenTotMondverzorging2024"
  TEMPLATES__VERMOGENTOTMONDVERZORGING2024__FILENAME: "data/templates/DataHub-VermogenTotMondverzorging-2024.opt"
  TEMPLATES__VERMOGENTOTTOILETGANG2024__ID: "DataHub-VermogenTotToiletgang-2024"
  TEMPLATES__VERMOGENTOTTOILETGANG2024__SEM_VER: "0.1.0"
  TEMPLATES__VERMOGENTOTTOILETGANG2024__API_ROUTE: "zib/VermogenTotToiletgang2024"
  TEMPLATES__VERMOGENTOTTOILETGANG2024__FILENAME: "data/templates/DataHub-VermogenTotToiletgang-2024.opt"
  TEMPLATES__VERMOGENTOTUITERLIJKEVERZORGING2024__ID: "DataHub-VermogenTotUiterlijkeVerzorging-2024"
  TEMPLATES__VERMOGENTOTUITERLIJKEVERZORGING2024__SEM_VER: "0.1.0"
  TEMPLATES__VERMOGENTOTUITERLIJKEVERZORGING2024__API_ROUTE: "zib/VermogenTotUiterlijkeVerzorging2024"
  TEMPLATES__VERMOGENTOTUITERLIJKEVERZORGING2024__FILENAME: "data/templates/DataHub-VermogenTotUiterlijkeVerzorging-2024.opt"
  TEMPLATES__VERMOGENTOTZELFSTANDIGMEDICATIEGEBRUIK2024__ID: "DataHub-VermogenTotZelfstandigMedicatiegebruik-2024"
  TEMPLATES__VERMOGENTOTZELFSTANDIGMEDICATIEGEBRUIK2024__SEM_VER: "0.1.0"
  TEMPLATES__VERMOGENTOTZELFSTANDIGMEDICATIEGEBRUIK2024__API_ROUTE: "zib/VermogenTotZelfstandigMedicatiegebruik2024"
  TEMPLATES__VERMOGENTOTZELFSTANDIGMEDICATIEGEBRUIK2024__FILENAME: "data/templates/DataHub-VermogenTotZelfstandigMedicatiegebruik-2024.opt"
  TEMPLATES__VERMOGENTOTZICHKLEDEN2024__ID: "DataHub-VermogenTotZichKleden-2024"
  TEMPLATES__VERMOGENTOTZICHKLEDEN2024__SEM_VER: "0.1.0"
  TEMPLATES__VERMOGENTOTZICHKLEDEN2024__API_ROUTE: "zib/VermogenTotZichKleden2024"
  TEMPLATES__VERMOGENTOTZICHKLEDEN2024__FILENAME: "data/templates/DataHub-VermogenTotZichKleden-2024.opt"
  TEMPLATES__VERMOGENTOTZICHWASSEN2024__ID: "DataHub-VermogenTotZichWassen-2024"
  TEMPLATES__VERMOGENTOTZICHWASSEN2024__SEM_VER: "0.1.0"
  TEMPLATES__VERMOGENTOTZICHWASSEN2024__API_ROUTE: "zib/VermogenTotZichWassen2024"
  TEMPLATES__VERMOGENTOTZICHWASSEN2024__FILENAME: "data/templates/DataHub-VermogenTotZichWassen-2024.opt"
  TEMPLATES__WOONSITUATIE2024__ID: "DataHub-Woonsituatie-2024"
  TEMPLATES__WOONSITUATIE2024__SEM_VER: "0.1.0"
  TEMPLATES__WOONSITUATIE2024__API_ROUTE: "zib/Woonsituatie2024"
  TEMPLATES__WOONSITUATIE2024__FILENAME: "data/templates/DataHub-Woonsituatie-2024.opt"