apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dh-health
  name: job-reader
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-jobs-binding
  namespace: dh-health
subjects:
- kind: ServiceAccount
  name: default
  namespace: dh-health
roleRef:
  kind: Role
  name: job-reader
  apiGroup: rbac.authorization.k8s.io