apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

configMapGenerator:
- name: test-ehrbase-config
  namespace: dh-health
  envs:
  - ehrbase.env