apiVersion: v1
kind: ConfigMap
metadata:
  name: mumc-portal-config
data:
  NEXT_PUBLIC_NODE_NAME: mumc
  ETL_SERVER_URL: http://mumc-etl-zib-rest.dh-health-mumc:8040
  FEDERATION_SERVER_URL: http://federation-rest:8000
