apiVersion: v1
kind: ConfigMap
metadata:
  name: staggered-startup-config
  namespace: dh-health
  labels:
      ehrnode: test-node
data:
  TEST_NODE_STARTUP_DELAY: "1"
  ENVIDA_NODE_STARTUP_DELAY: "5"
  MUMC_NODE_STARTUP_DELAY: "10"
  VITALA_NODE_STARTUP_DELAY: "15"
  ZIO_NODE_STARTUP_DELAY: "20"
