apiVersion: apps/v1
kind: Deployment
metadata:
  name: zio-init-container-patch
spec:
  template:
    spec:
      initContainers:
      - name: staggered-startup-delay
        image: busybox:1.28
        command: ["/bin/sh", "-c", "echo 'Sleeping for $(STAGGERED_STARTUP_DELAY)s ...' && sleep $(STAGGERED_STARTUP_DELAY)"]
        env:
        - name: STAGGERED_STARTUP_DELAY
          valueFrom:
            configMapKeyRef:
              name: staggered-startup-config
              key: ZIO_NODE_STARTUP_DELAY