apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dh-health

images:
- name: registry.prod.dh.unimaas.nl/docker-health/federation-rest
  newTag: '2024.1.7'
- name: registry.prod.dh.unimaas.nl/docker-health/federation-test
  newTag: '2024.1.7'
- name: registry.prod.dh.unimaas.nl/docker-health/etl-zib-rest
  newTag: '2024.1.7'
- name: registry.prod.dh.unimaas.nl/docker-health/etl-zib-test
  newTag: '2024.1.7'
- name: registry.prod.dh.unimaas.nl/docker-health/etl-zib-pipeline
  newTag: '2024.1.7'
- name: registry.prod.dh.unimaas.nl/docker-health/portal
  newTag: '2024.1.7'
- name: registry.prod.dh.unimaas.nl/docker-health/transform-rest
  newTag: '2024.1.7'
- name: registry.prod.dh.unimaas.nl/docker-health/jupyter-zib
  newTag: '2024.1.7'

resources:
- ./secrets.yaml
# Base resources
- ../../base/common
- ../../base/federation-rest
- ../../base/transform-rest
- ../../base/jupyter-zib
- ../../base/terminology-server-proxy
# Envida-node
- ../../base/openehr-nodes/envida/ehrbase
- ../../base/openehr-nodes/envida/ehrdb
- ../../base/openehr-nodes/envida/etl-config
- ../../base/openehr-nodes/envida/etl-zib-pipeline
- ../../base/openehr-nodes/envida/etl-zib-rest
- ../../base/openehr-nodes/envida/portal
# MUMC-node
- ../../base/openehr-nodes/mumc/ehrbase
- ../../base/openehr-nodes/mumc/ehrdb
- ../../base/openehr-nodes/mumc/etl-config
- ../../base/openehr-nodes/mumc/etl-zib-pipeline
- ../../base/openehr-nodes/mumc/etl-zib-rest
- ../../base/openehr-nodes/mumc/portal
# VITALA-node
- ../../base/openehr-nodes/vitala/ehrbase
- ../../base/openehr-nodes/vitala/ehrdb
- ../../base/openehr-nodes/vitala/etl-config
- ../../base/openehr-nodes/vitala/etl-zib-pipeline
- ../../base/openehr-nodes/vitala/etl-zib-rest
- ../../base/openehr-nodes/vitala/portal
# ZIO-node
- ../../base/openehr-nodes/zio/ehrbase
- ../../base/openehr-nodes/zio/ehrdb
- ../../base/openehr-nodes/zio/etl-config
- ../../base/openehr-nodes/zio/etl-zib-pipeline
- ../../base/openehr-nodes/zio/etl-zib-rest
- ../../base/openehr-nodes/zio/portal

patches:
# 'Global' patches that apply to all of one sort
# Storage class patches
- target:
    kind: PersistentVolume
  patch: |-
    - op: replace
      path: /spec/storageClassName
      value: local-path
- target:
    kind: PersistentVolumeClaim
  patch: |-
    - op: replace
      path: /spec/storageClassName
      value: local-path
# Image pull secret patches
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/imagePullSecrets
      value:
      - name: registry-credentials
- target:
    kind: Job
  patch: |-
    - op: replace
      path: /spec/template/spec/imagePullSecrets
      value:
      - name: registry-credentials
# imagePullPolicy patches
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Always
- target:
    kind: Job
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Always  


# Ingress patches
## Transform
- path: patches/ingress/common/transform.yaml
## Federation
- path: patches/ingress/common/federation.yaml
## Jupyter
- path: patches/ingress/common/jupyter.yaml
## Envida-node
- path: patches/ingress/envida/ehrbase.yaml
- path: patches/ingress/envida/etl-zib-rest.yaml
- path: patches/ingress/envida/portal.yaml
## MUMC-node
- path: patches/ingress/mumc/ehrbase.yaml
- path: patches/ingress/mumc/etl-zib-rest.yaml
- path: patches/ingress/mumc/portal.yaml
## VITALA-node
- path: patches/ingress/vitala/ehrbase.yaml
- path: patches/ingress/vitala/etl-zib-rest.yaml
- path: patches/ingress/vitala/portal.yaml
## ZIO-node
- path: patches/ingress/zio/ehrbase.yaml
- path: patches/ingress/zio/etl-zib-rest.yaml
- path: patches/ingress/zio/portal.yaml

# Patch the data mounts to use the GIT PVC
- path: patches/job/envida-etl-zib-delete-demo-data.yaml
- path: patches/job/envida-etl-zib-add-demo-data.yaml
- path: patches/job/vitala-etl-zib-delete-demo-data.yaml
- path: patches/job/vitala-etl-zib-add-demo-data.yaml
- path: patches/job/mumc-etl-zib-delete-demo-data.yaml
- path: patches/job/mumc-etl-zib-add-demo-data.yaml
- path: patches/job/zio-etl-zib-delete-demo-data.yaml
- path: patches/job/zio-etl-zib-add-demo-data.yaml
- path: patches/deployment/jupyter-delete-demo-data.yaml
- path: patches/deployment/jupyter-add-demo-data.yaml
# Delete TEST node configs
- path: patches/deployment/jupyter-delete-test-config.yaml

configMapGenerator:
- name: portal-common-config
  namespace: dh-health
  behavior: merge
  literals:
    - NEXT_PUBLIC_FEDERATION_BASE_URL=https://federation.fehr.amumc.nl