apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dh-health

resources:
- namespace.yaml
- common/log_volume.yaml
# include configmaps.yaml for additional configs
#- common/configmaps.yaml
- transform-rest/deployment.yaml
- transform-rest/service.yaml
- transform-rest/configmap.yaml
- transform-rest/ingress.yaml
- federation-api/deployment.yaml
- federation-api/service.yaml
- federation-api/configmap.yaml
- federation-api/ingress.yaml
- jupyter-zib/deployment.yaml
- jupyter-zib/service.yaml
- jupyter-zib/configmap.yaml
- jupyter-zib/ingress.yaml
- filebeat/
- redis/
- mumc-node/
- zio-node/
- envida-node/
- test-node/

configMapGenerator:
- name: timezone-config
  namespace: dh-health
  envs:
  - env_files/timezone.env

- name: transform-server-config
  namespace: dh-health
  envs:
  - env_files/transform_server.env

- name: zib-templates-config
  namespace: dh-health
  envs:
  - env_files/zib-templates.env

- name: federation-config
  namespace: dh-health
  envs:
  - env_files/federation.env

- name: portal-common-config
  namespace: dh-health
  envs:
  - env_files/portal_common.env

- name: openehrtool-config
  namespace: dh-health
  envs:
  - env_files/openEHR-tool.env
