apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- common
- transform-rest
- federation-api
- jupyter-zib
- mumc-node/
- zio-node/
- envida-node/
- test-node/

configMapGenerator:
- name: timezone-config
  namespace: dh-health
  literals:
  - TZ=Europe/Amsterdam

- name: portal-common-config
  namespace: dh-health
  literals:
    - FEDERATION_SERVER_URL=http://federation-api:8000

