apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- common
- transform-rest
- federation-api
- jupyter-zib
- redis/
- mumc-node/
- zio-node/
- envida-node/
- test-node/

configMapGenerator:
- name: timezone-config
  namespace: dh-health
  literals:
  - TZ=Europe/Amsterdam

- name: portal-common-config
  namespace: dh-health
  literals:
    - FEDERATION_SERVER_URL=http://federation-api:8000

- name: openehrtool-config
  namespace: dh-health
  literals:
    - REDISSERVER_hostname=redis.dh-health
    - REDISSERVER_port=6379
    - REDISSERVER_eventsrecorded=100
    - EHRBASESERVER_port=8080
    - FLASK_APP=app.py
    - FLASK_ENV=development
    - SEND_FILE_MAX_AGE_DEFAULT=0

