apiVersion: apps/v1
kind: Deployment
metadata:
  name: federation-api
  namespace: dh-health
  labels:
    app: federation-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: federation-api
  template:
    metadata:
      labels:
        app: federation-api
    spec:
      containers:
        - name: federation-api
          image: docker-health/federation-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: MUMC__FEDERATION_KEY
              valueFrom:
                secretKeyRef:
                  name: mumc-federation-key
                  key: key
            - name: MUMC__FEDERATION_BTG_KEY
              valueFrom:
                secretKeyRef:
                  name: mumc-federation-break-the-glass-key
                  key: key
            - name: MUMC__EHRBASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mumc-ehrbase-creds
                  key: username
            - name: MUMC__EHRBASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mumc-ehrbase-creds
                  key: password
            - name: ZIO__FEDERATION_KEY
              valueFrom:
                secretKeyRef:
                  name: zio-federation-key
                  key: key
            - name: ZIO__FEDERATION_BTG_KEY
              valueFrom:
                secretKeyRef:
                  name: zio-federation-break-the-glass-key
                  key: key
            - name: ZIO__EHRBASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: zio-ehrbase-creds
                  key: username
            - name: ZIO__EHRBASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zio-ehrbase-creds
                  key: password
            - name: ENVIDA__EHRBASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: envida-ehrbase-creds
                  key: username
            - name: ENVIDA__EHRBASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: envida-ehrbase-creds
                  key: password
            - name: ENVIDA__FEDERATION_KEY
              valueFrom:
                secretKeyRef:
                  name: envida-federation-key
                  key: key
            - name: ENVIDA__FEDERATION_BTG_KEY
              valueFrom:
                secretKeyRef:
                  name: envida-federation-break-the-glass-key
                  key: key
          envFrom:
            - configMapRef:
                name: timezone-config
            - configMapRef:
                name: federation-api-config
          volumeMounts:
            - name: logs
              mountPath: /code/logs/federation-api
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: log-pvc