apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dh-health-jupyter

resources:
  - namespace.yaml
  - jupyter-zib-gateway.yaml
  - ../../../base/jupyter-zib
  - ../node-envida/etl-config
  - ../node-mumc/etl-config
  - ../node-vitala/etl-config
  - ../node-zio/etl-config

components:
  - ../shared-components
