apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dh-health-envida

resources:
  - ../../../base/openehr-nodes/envida
  - ../shared
  - namespace.yaml
  - service-discovery
  - services-list-role-binding.yaml

components:
  - components

patches:
  # imagePullPolicy patches
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Job
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
