apiVersion: v1
kind: ConfigMap
metadata:
  name: elk-config
  namespace: dh-health-ops
data:
  NODE_OPTIONS: "--max-old-space-size=3072"
  ES_JAVA_OPTS: "-Dls.cgroup.cpuacct.path.override=/ -Dls.cgroup.cpu.path.override=/ -Xms1g -Xmx1g"
  ELASTIC_PASSWORD : foobar