apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dh-health

resources:
#- vault-auth.yaml # Disabled for now, because vault-auth service account is already created by Gitlab Manifests
- vault-store.yaml
- tls-secrets.yaml