apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: prod-vault.dev-test
spec:
  provider:
    vault:
      server: "https://vault.prod.dh.unimaas.nl" # URL of the Vault server
      path: "dev-test" # The mount path of the KV v2 secret engine
      version: "v2" # This will automatically handle the /data/ prefix
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: "vault-auth"
            namespace: "dh-health"    # This should be the ServiceAccount running the ExternalSecrets operator
