apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nedap-cert-pass
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: nedap-cert-pass
    template:
      engineVersion: v2
      data:
        password: "{{ .nedap_cert_pass }}"
  dataFrom:
    - extract:
        key: hdp-env/envida
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nedap-cert
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: nedap-cert
    template:
      engineVersion: v2
      data:
        envida_dabs-TE1002-development.pfx: "{{ .nedap_cert_pfx | b64dec }}"
  dataFrom:
    - extract:
        key: hdp-env/envida
