apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets
      value:
      - name: regcred

# Individual ingress host patches
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: zio-openehrtool-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: openehrtool.zio.tst.dh.unimaas.nl

- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: zio-portal-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: portal.zio.tst.dh.unimaas.nl

- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: envida-ehrbase-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: ehrbase.envida.tst.dh.unimaas.nl

- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: envida-openehrtool-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: openehrtool.envida.tst.dh.unimaas.nl

- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: envida-portal-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: portal.envida.tst.dh.unimaas.nl

- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: test-ehrbase-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: ehrbase.tst.dh.unimaas.nl

- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: test-openehrtool-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: openehrtool.tst.dh.unimaas.nl

configMapGenerator:
- name: portal-common-config
  namespace: dh-health
  behavior: merge
  literals:
    - NEXT_PUBLIC_FEDERATION_API_URL=http://federation.tst.dh.unimaas.nl