apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dh-health

images:
- name: registry.prod.dh.unimaas.nl/docker-health/federation-rest
  newTag: '2024.1.8'
- name: registry.prod.dh.unimaas.nl/docker-health/federation-test
  newTag: '2024.1.8'
- name: registry.prod.dh.unimaas.nl/docker-health/etl-zib-rest
  newTag: '2024.1.8'
- name: registry.prod.dh.unimaas.nl/docker-health/etl-zib-test
  newTag: '2024.1.8'
- name: registry.prod.dh.unimaas.nl/docker-health/etl-zib-pipeline
  newTag: '2024.1.8'
- name: registry.prod.dh.unimaas.nl/docker-health/portal
  newTag: '2024.1.8'
- name: registry.prod.dh.unimaas.nl/docker-health/transform-rest
  newTag: '2024.1.8'
- name: registry.prod.dh.unimaas.nl/docker-health/jupyter-zib
  newTag: '2024.1.8'

resources:
# NEW vault secret operator
- ./vault-operator
# Base resources
- ../../base/common
- ../../base/federation-rest
- ../../base/jupyter-zib
# EHR-nodes
- ../../base/openehr-nodes/envida
- ../../base/openehr-nodes/mumc
- ../../base/openehr-nodes/vitala
- ../../base/openehr-nodes/zio
# Gateway resources
- patches/gateway/common/federation.yaml
- patches/gateway/common/jupyter.yaml
- patches/gateway/envida/portal.yaml
- patches/gateway/mumc/portal.yaml
- patches/gateway/vitala/portal.yaml
- patches/gateway/zio/portal.yaml

patches:
# 'Global' patches that apply to all of one sort
# Storage class patches
- target:
    kind: PersistentVolume
  patch: |-
    - op: replace
      path: /spec/storageClassName
      value: local-path
- target:
    kind: PersistentVolumeClaim
  patch: |-
    - op: replace
      path: /spec/storageClassName
      value: local-path
# Image pull secret patches
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/imagePullSecrets
      value:
      - name: registry-credentials
- target:
    kind: Job
  patch: |-
    - op: replace
      path: /spec/template/spec/imagePullSecrets
      value:
      - name: registry-credentials
# imagePullPolicy patches
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: IfNotPresent
- target:
    kind: Job
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: IfNotPresent
# Proxy patches
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/envFrom/-"
      value:
        configMapRef:
          name: proxy-config


# Patch the data mounts to use the GIT PVC
- path: patches/job/envida-etl-zib-delete-demo-data.yaml
- path: patches/job/envida-etl-zib-add-demo-data.yaml
- path: patches/job/vitala-etl-zib-delete-demo-data.yaml
- path: patches/job/vitala-etl-zib-add-demo-data.yaml
- path: patches/job/mumc-etl-zib-delete-demo-data.yaml
- path: patches/job/mumc-etl-zib-add-demo-data.yaml
- path: patches/job/zio-etl-zib-delete-demo-data.yaml
- path: patches/job/zio-etl-zib-add-demo-data.yaml
- path: patches/deployment/jupyter-delete-demo-data.yaml
- path: patches/deployment/jupyter-add-demo-data.yaml
# Delete TEST node configs
- path: patches/deployment/jupyter-delete-test-config.yaml

# Docker Hub official repository secret patch
- target:
    kind: Job
    name: create-tls-secrets
  patch: |-
    - op: replace
      path: /spec/template/spec/imagePullSecrets
      value:
      - name: dockerhub-registry-credentials

configMapGenerator:
- name: proxy-config
  namespace: dh-health
  literals:
    - HTTP_PROXY=http://proxy.unimaas.nl:3128
    - http_proxy=http://proxy.unimaas.nl:3128
    - HTTPS_PROXY=http://proxy.unimaas.nl:3128
    - https_proxy=http://proxy.unimaas.nl:3128
    - NO_PROXY=localhost,.dh.local,.dh-health,.unimaas.nl,.datahubmaastricht.nl,137.120.31.0/24,.cluster.local,10.42.0.0/12,10.43.0.0/12,10.43.0.10,10.43.0.1
    - no_proxy=localhost,.dh.local,.dh-health,.unimaas.nl,.datahubmaastricht.nl,137.120.31.0/24,.cluster.local,10.42.0.0/12,10.43.0.0/12,10.43.0.10,10.43.0.1

- name: portal-common-config
  namespace: dh-health
  behavior: merge
  literals:
    - NEXT_PUBLIC_FEDERATION_BASE_URL=https://federation.tst.dh.unimaas.nl