apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dh-health

images:
- name: registry.prod.dh.unimaas.nl/docker-health/federation-rest
  newTag: '2024.1'
- name: registry.prod.dh.unimaas.nl/docker-health/federation-test
  newTag: '2024.1'
- name: registry.prod.dh.unimaas.nl/docker-health/etl-zib-rest
  newTag: '2024.1'
- name: registry.prod.dh.unimaas.nl/docker-health/etl-zib-test
  newTag: '2024.1'
- name: registry.prod.dh.unimaas.nl/docker-health/etl-zib-pipeline
  newTag: '2024.1'
- name: registry.prod.dh.unimaas.nl/docker-health/portal
  newTag: '2024.1'
- name: registry.prod.dh.unimaas.nl/docker-health/transform-rest
  newTag: '2024.1'
- name: registry.prod.dh.unimaas.nl/docker-health/jupyter-zib
  newTag: '2024.1'

resources:
- ./tls-secrets-patch.yaml
- ./secrets.yaml
- ./demo-data
#- ./registry-secret.yaml
- ../../base/common
- ../../base/federation-rest
- ../../base/transform-rest
- ../../base/jupyter-zib
- ../../base/terminology-server-proxy
# Envida-node
- ../../base/openehr-nodes/envida/ehrbase
- ../../base/openehr-nodes/envida/ehrdb
- ../../base/openehr-nodes/envida/etl-config
- ../../base/openehr-nodes/envida/etl-zib-pipeline
- ../../base/openehr-nodes/envida/etl-zib-rest
- ../../base/openehr-nodes/envida/portal
# MUMC-node
- ../../base/openehr-nodes/mumc/ehrbase
- ../../base/openehr-nodes/mumc/ehrdb
- ../../base/openehr-nodes/mumc/etl-config
- ../../base/openehr-nodes/mumc/etl-zib-pipeline
- ../../base/openehr-nodes/mumc/etl-zib-rest
- ../../base/openehr-nodes/mumc/portal
# VITALA-node
- ../../base/openehr-nodes/vitala/ehrbase
- ../../base/openehr-nodes/vitala/ehrdb
- ../../base/openehr-nodes/vitala/etl-config
- ../../base/openehr-nodes/vitala/etl-zib-pipeline
- ../../base/openehr-nodes/vitala/etl-zib-rest
- ../../base/openehr-nodes/vitala/portal
# ZIO-node
- ../../base/openehr-nodes/zio/ehrbase
- ../../base/openehr-nodes/zio/ehrdb
- ../../base/openehr-nodes/zio/etl-config
- ../../base/openehr-nodes/zio/etl-zib-pipeline
- ../../base/openehr-nodes/zio/etl-zib-rest
- ../../base/openehr-nodes/zio/portal

patches:
# Storage class patches
- target:
    kind: PersistentVolume
  patch: |-
    - op: replace
      path: /spec/storageClassName
      value: local-storage
- target:
    kind: PersistentVolumeClaim
  patch: |-
    - op: replace
      path: /spec/storageClassName
      value: local-storage
# Image pull secret
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/imagePullSecrets
      value:
      - name: registry-credentials
- target:
    kind: Job
  patch: |-
    - op: replace
      path: /spec/template/spec/imagePullSecrets
      value:
      - name: registry-credentials

# imagePullPolicy patches
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Always
- target:
    kind: Job
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Always  

# Proxy patches
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: http_proxy
        value: "http://proxy.unimaas.nl:3128"
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: https_proxy
        value: "http://proxy.unimaas.nl:3128"
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: no_proxy
        value: "localhost,.dh.local,.dh-health,.unimaas.nl,.datahubmaastricht.nl,137.120.31.0/16,.cluster.local,10.96.0.0/12,10.244.0.0/16,10.96.0.10"
# Individual ingress host patches
## Transform
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: transform-rest-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: transform.tst.dh.unimaas.nl
    - op: add
      path: /spec/tls
      value:
      - hosts:
        - transform.tst.dh.unimaas.nl
        secretName: transform-tls-secret
## Federation
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: federation-rest-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: federation.tst.dh.unimaas.nl
    - op: add
      path: /spec/tls
      value:
      - hosts:
        - federation.tst.dh.unimaas.nl
        secretName: federation-tls-secret
## Jupyter
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: jupyter-zib-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: jupyter.tst.dh.unimaas.nl
    - op: add
      path: /spec/tls
      value:
      - hosts:
        - jupyter.tst.dh.unimaas.nl
        secretName: jupyter-tls-secret
## Envida-node
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: envida-ehrbase-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: ehrbase.envida.tst.dh.unimaas.nl
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: envida-etl-zib-rest-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: etl.envida.tst.dh.unimaas.nl
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: envida-portal-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: portal.envida.tst.dh.unimaas.nl
    - op: add
      path: /spec/tls
      value:
      - hosts:
        - portal.envida.tst.dh.unimaas.nl
        secretName: portal-envida-tls-secret
## MUMC-node
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: mumc-ehrbase-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: ehrbase.mumc.tst.dh.unimaas.nl
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: mumc-etl-zib-rest-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: etl.mumc.tst.dh.unimaas.nl
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: mumc-portal-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: portal.mumc.tst.dh.unimaas.nl
    - op: add
      path: /spec/tls
      value:
      - hosts:
        - portal.mumc.tst.dh.unimaas.nl
        secretName: portal-mumc-tls-secret
## VITALA-node
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: vitala-ehrbase-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: ehrbase.vitala.tst.dh.unimaas.nl
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: vitala-etl-zib-rest-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: etl.vitala.tst.dh.unimaas.nl
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: vitala-portal-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: portal.vitala.tst.dh.unimaas.nl
    - op: add
      path: /spec/tls
      value:
      - hosts:
        - portal.vitala.tst.dh.unimaas.nl
        secretName: portal-vitala-tls-secret
## ZIO-node
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: zio-ehrbase-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: ehrbase.zio.tst.dh.unimaas.nl
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: zio-etl-zib-rest-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: etl.zio.tst.dh.unimaas.nl
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: zio-portal-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: portal.zio.tst.dh.unimaas.nl
    - op: add
      path: /spec/tls
      value:
      - hosts:
        - portal.zio.tst.dh.unimaas.nl
        secretName: portal-zio-tls-secret

configMapGenerator:
- name: portal-common-config
  namespace: dh-health
  behavior: merge
  literals:
    - NEXT_PUBLIC_FEDERATION_BASE_URL=https://federation.tst.dh.unimaas.nl
- name: git-config
  namespace: dh-health
  literals:
    - GIT_BRANCH=PLACEHOLDER