apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
- name: env-config
  namespace: dh-health
  literals:
  - RIT_ENV=tst
  - ENV_TAG=2024.1
  behavior: merge