apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- job.yaml
- role.yaml
- ../../../base/common
- ../../../base/federation-rest
- ../../../base/terminology-server-proxy
# Envida-node
- ../../../base/openehr-nodes/envida/ehrbase
- ../../../base/openehr-nodes/envida/ehrdb
- ../../../base/openehr-nodes/envida/etl-config
- ../../../base/openehr-nodes/envida/etl-zib-pipeline
- ../../../base/openehr-nodes/envida/transform-rest
# MUMC-node
- ../../../base/openehr-nodes/mumc/ehrbase
- ../../../base/openehr-nodes/mumc/ehrdb
- ../../../base/openehr-nodes/mumc/etl-config
- ../../../base/openehr-nodes/mumc/etl-zib-pipeline
- ../../../base/openehr-nodes/mumc/transform-rest
# VITALA-node
- ../../../base/openehr-nodes/vitala/ehrbase
- ../../../base/openehr-nodes/vitala/ehrdb
- ../../../base/openehr-nodes/vitala/etl-config
- ../../../base/openehr-nodes/vitala/etl-zib-pipeline
- ../../../base/openehr-nodes/vitala/transform-rest
# ZIO-node
- ../../../base/openehr-nodes/zio/ehrbase
- ../../../base/openehr-nodes/zio/ehrdb
- ../../../base/openehr-nodes/zio/etl-config
- ../../../base/openehr-nodes/zio/etl-zib-pipeline
- ../../../base/openehr-nodes/zio/transform-rest

components:
  - ../ingress/terminology-server-proxy/
  - ../ingress/federation-rest/
  - ../ingress/openehr-nodes/envida/
  - ../ingress/openehr-nodes/mumc/
  - ../ingress/openehr-nodes/vitala/
  - ../ingress/openehr-nodes/zio/

patches:
# imagePullPolicy patches
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Never
- target:
    kind: Job
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Never
