apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dh-health-test-federation

resources:
  - namespace.yaml
  - ../../../base/common
  - job.yaml
  - job-reader-role.yaml
  - services-list-role-binding.yaml
  - ../node-envida/prefix
  - ../node-mumc/prefix
  - ../node-vitala/prefix
  - ../node-zio/prefix
#  # ENVIDA-node
#  - ../../../base/openehr-nodes/envida/ehrbase
#  - ../../../base/openehr-nodes/envida/ehrdb
#  - ../../../base/openehr-nodes/envida/etl-zib/etl-config
#  - ../../../base/openehr-nodes/envida/etl-zib/etl-zib-pipeline
#  - ../../../base/openehr-nodes/envida/federation-rest
#  - ../../../base/openehr-nodes/envida/terminology-server-proxy
#  - ../../../base/openehr-nodes/envida/transform-rest
#  # MUMC-node
#  - ../../../base/openehr-nodes/mumc/ehrbase
#  - ../../../base/openehr-nodes/mumc/ehrdb
#  - ../../../base/openehr-nodes/mumc/etl-zib/etl-config
#  - ../../../base/openehr-nodes/mumc/etl-zib/etl-zib-pipeline
#  - ../../../base/openehr-nodes/mumc/federation-rest
#  - ../../../base/openehr-nodes/mumc/terminology-server-proxy
#  - ../../../base/openehr-nodes/mumc/transform-rest
#  # VITALA-node
#  - ../../../base/openehr-nodes/vitala/ehrbase
#  - ../../../base/openehr-nodes/vitala/ehrdb
#  - ../../../base/openehr-nodes/vitala/etl-zib/etl-config
#  - ../../../base/openehr-nodes/vitala/etl-zib/etl-zib-pipeline
#  - ../../../base/openehr-nodes/vitala/federation-rest
#  - ../../../base/openehr-nodes/vitala/terminology-server-proxy
#  - ../../../base/openehr-nodes/vitala/transform-rest
#  # ZIO-node
#  - ../../../base/openehr-nodes/zio/ehrbase
#  - ../../../base/openehr-nodes/zio/ehrdb
#  - ../../../base/openehr-nodes/zio/etl-zib/etl-config
#  - ../../../base/openehr-nodes/zio/etl-zib/etl-zib-pipeline
#  - ../../../base/openehr-nodes/zio/federation-rest
#  - ../../../base/openehr-nodes/zio/terminology-server-proxy
#  - ../../../base/openehr-nodes/zio/transform-rest

#components:
#  # ENVIDA-node
#  - ../node-envida/components/ehrbase-gateway
#  - ../node-envida/components/federation-rest-gateway
#  - ../node-envida/components/transform-rest-gateway
#  - ../node-envida/components/terminology-server-proxy-gateway
#  - ../node-envida/components/secrets
#  # MUMC-node
#  - ../node-mumc/components/ehrbase-gateway
#  - ../node-mumc/components/federation-rest-gateway
#  - ../node-mumc/components/transform-rest-gateway
#  - ../node-mumc/components/terminology-server-proxy-gateway
#  - ../node-mumc/components/secrets
#  # VITALA-node
#  - ../node-vitala/components/ehrbase-gateway
#  - ../node-vitala/components/federation-rest-gateway
#  - ../node-vitala/components/transform-rest-gateway
#  - ../node-vitala/components/terminology-server-proxy-gateway
#  - ../node-vitala/components/secrets
#  # ZIO-node
#  - ../node-zio/components/ehrbase-gateway
#  - ../node-zio/components/federation-rest-gateway
#  - ../node-zio/components/transform-rest-gateway
#  - ../node-zio/components/terminology-server-proxy-gateway
#  - ../node-zio/components/secrets

patches:
  # imagePullPolicy patches
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Job
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
