apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
  - name: vitala-ehrbase-creds
    namespace: dh-health
    literals:
      - username=user4
      - password=foobar4
  - name: vitala-ehrbase-admin-creds
    namespace: dh-health
    literals:
      - username=admin4
      - password=admin4
  - name: vitala-ehrbase-db-admin-creds
    namespace: dh-health
    literals:
      - username=ehrbase4
      - password=ehrbase4
  - name: vitala-ehrbase-db-creds
    namespace: dh-health
    literals:
      - username=ehrbase_restricted4
      - password=ehrbase_restricted4
  - name: vitala-portal-creds
    namespace: dh-health
    literals:
      - username=demo@vitala.nl
      - password=foobar
  - name: vitala-federation-key
    namespace: dh-health
    literals:
      - key=key4
  - name: vitala-federation-break-the-glass-key
    namespace: dh-health
    literals:
      - key=btgkey4
  - name: vitala-ehrbase-db-postgres-creds
    namespace: dh-health
    literals:
      - username=postgres
      - password=postgres
  - name: vitala-transform-creds
    namespace: dh-health
    options:
      labels:
        ehrnode: vitala-node
    literals:
      - username=transform4
      - password=transform4
