apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
  - name: ehrbase-creds
    literals:
      - username=user4
      - password=foobar4
  - name: ehrbase-admin-creds
    literals:
      - username=admin4
      - password=admin4
  - name: ehrbase-db-admin-creds
    literals:
      - username=ehrbase4
      - password=ehrbase4
  - name: ehrbase-db-creds
    literals:
      - username=ehrbase_restricted4
      - password=ehrbase_restricted4
  - name: portal-creds
    literals:
      - username=demo@vitala.nl
      - password=foobar
  - name: federation-key
    literals:
      - key=key4
  - name: federation-break-the-glass-key
    literals:
      - key=btgkey4
  - name: ehrbase-db-postgres-creds
    literals:
      - username=postgres
      - password=postgres
  - name: transform-creds
    literals:
      - username=transform4
      - password=transform4
