apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: vitala-etl-zib-rest-gateway
  namespace: dh-health
spec:
  gatewayClassName: traefik
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      hostname: etl.vitala.local.dh.unimaas.nl
    - name: http
      port: 80
      protocol: HTTP
      hostname: etl.vitala.local.dh.unimaas.nl
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vitala-etl-zib-rest-route
  namespace: dh-health
spec:
  parentRefs:
    - name: vitala-etl-zib-rest-gateway
  hostnames:
    - etl.vitala.local.dh.unimaas.nl
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: vitala-etl-zib-rest
          port: 8040
