apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vitala-portal-ingress
  namespace: dh-health
spec:
  rules:
    - host: portal.vitala.tst.dh.unimaas.nl
  tls:
    - hosts:
        - portal.vitala.tst.dh.unimaas.nl
      secretName: portal-vitala-tls-secret