apiVersion: batch/v1
kind: Job
metadata:
  name: populate-pvc-with-git-repo
  namespace: dh-health
spec:
  template:
    spec:
      containers:
        - name: git-clone
          image: alpine/git:latest
          envFrom:
            - configMapRef:
                name: git-config
          command:
            - sh
            - -c
            - |
              git clone https://github.com/MaastrichtUniversity/docker-health.git /repo
              cd /repo
              git checkout "$GIT_BRANCH"
          volumeMounts:
            - name: git-repo
              mountPath: /repo
      restartPolicy: Never
      volumes:
        - name: git-repo
          persistentVolumeClaim:
            claimName: git-repo-pvc