apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: populate-pvc-with-git-repo
  namespace: dh-health
spec:
  selector:
    matchLabels:
      app: git-repo-sync
  template:
    metadata:
      labels:
        app: git-repo-sync
    spec:
      containers:
        - name: git-clone
          image: alpine/git:latest
          envFrom:
            - configMapRef:
                name: git-config
          env:
            - name: http_proxy
              value: "http://proxy.unimaas.nl:3128"
            - name: https_proxy
              value: "http://proxy.unimaas.nl:3128"
            - name: no_proxy
              value: "localhost,.dh.local,.dh-health,.unimaas.nl,.datahubmaastricht.nl,137.120.31.0/16,.cluster.local,10.42.0.0/16,10.43.0.10"        
          command:
            - sh
            - -c
            - |
              set -e
              echo "Cleaning old repo..."
              rm -rf /repo/src
              echo "Cloning fresh repo into /repo/src"
              git clone https://github.com/MaastrichtUniversity/docker-health.git /repo/src
              cd /repo/src
              git checkout "$GIT_BRANCH"
              echo "Sync complete, keeping pod alive to satisfy DaemonSet"
              sleep infinity
          volumeMounts:
            - name: git-repo
              mountPath: /repo
      restartPolicy: Always
      volumes:
        - name: git-repo
          persistentVolumeClaim:
            claimName: git-repo-pvc
