apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dh-health

generatorOptions:
  disableNameSuffixHash: true

resources:
- pvc.yaml
- job.yaml

patches:
# Patch the data mounts to use the GIT PVC
- target:
    kind: Job
    name: envida-etl-zib-pipeline
  patch: |-
    - op: replace
      path: /spec/template/spec/volumes/1  # assuming 'data' is the 2nd volume in the array
      value:
        name: data
        persistentVolumeClaim:
          claimName: git-repo-pvc
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/1/subPath
      value: data/envida-demo-data
- target:
    kind: Job
    name: zio-etl-zib-pipeline
  patch: |-
    - op: replace
      path: /spec/template/spec/volumes/1  # assuming 'data' is the 2nd volume in the array
      value:
        name: data
        persistentVolumeClaim:
          claimName: git-repo-pvc
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/1/subPath
      value: data/zio-demo-data
- target:
    kind: Job
    name: vitala-etl-zib-pipeline
  patch: |-
    - op: replace
      path: /spec/template/spec/volumes/1  # assuming 'data' is the 2nd volume in the array
      value:
        name: data
        persistentVolumeClaim:
          claimName: git-repo-pvc
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/1/subPath
      value: data/vitala-demo-data
- target:
    kind: Job
    name: mumc-etl-zib-pipeline
  patch: |-
    - op: replace
      path: /spec/template/spec/volumes/1  # assuming 'data' is the 2nd volume in the array
      value:
        name: data
        persistentVolumeClaim:
          claimName: git-repo-pvc
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/1/subPath
      value: data/mumc-demo-data
- target:
    kind: Deployment
    name: jupyter-zib
  patch: |-
    - op: remove
      path: /spec/template/spec/volumes/0
    - op: remove
      path: /spec/template/spec/containers/0/volumeMounts/0
    - op: add
      path: /spec/template/spec/volumes/0
      value:
        name: demo-data
        persistentVolumeClaim:
          claimName: git-repo-pvc
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/0
      value:
        name: demo-data
        mountPath: /home/jovyan/data
        subPath: data

configMapGenerator:
- name: git-config
  namespace: dh-health
  literals:
    - GIT_BRANCH=PLACEHOLDER