apiVersion: v1
kind: PersistentVolume
metadata:
  name: git-repo-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: git-demo-data
    name: git-repo-pvc
  storageClassName: local-path
  hostPath:
    path: /mnt/demo-data
    type: DirectoryOrCreate
