---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-repo-pvc
  namespace: dh-health
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn
