apiVersion: v1
kind: ConfigMap
metadata:
  name: mumc-transform-rest-config
data:
  TERMINOLOGY_BASE_URL: http://mumc-terminology-server-proxy.dh-health-mumc:8080
  LOGGER_FILENAME: /var/log/mumc/transform-rest.log
