apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base-config/proxy-namespaces/dh-health-envida
  - ../../../base-config/proxy-namespaces/dh-health-mumc
  - ../../../base-config/proxy-namespaces/dh-health-vitala
  - ../../../base-config/proxy-namespaces/dh-health-zio
  - ../test-federation

patches:
  - target:
      kind: Deployment
      name: .*terminology-server-proxy
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom/-
        value:
          configMapRef:
            name: proxy-config
  - target:
      kind: Job
      name: .*etl-zib-pipeline
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom/-
        value:
          configMapRef:
            name: proxy-config
