apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebeat-log-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-csi
  volumeName: pv-filebeat-logs
