apiVersion: v1
kind: Service
metadata:
  name: zio-federation-rest
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: zio-federation-rest