apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dh-health-test-federation

images:
  - name: registry.prod.dh.unimaas.nl/docker-health/federation-test
    newTag: "2026.2.0"

resources:
  - namespace.yaml
  - job.yaml
  - job-reader-role.yaml
  - services-list-role-binding.yaml
  - vault-auth.yaml
  - secrets

generatorOptions:
  disableNameSuffixHash: true

patches:
  - target:
      kind: Job
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
  - target:
      kind: Job
    patch: |-
      - op: replace
        path: /spec/template/spec/imagePullSecrets
        value:
        - name: registry-credentials
