apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dh-health-test-federation

resources:
  - namespace.yaml
  - ../../../../base/base-config
  - job.yaml
  - job-reader-role.yaml
  - ../../node-envida/etl-config_secrets
  - ../../node-mumc/etl-config_secrets
  - ../../node-vitala/etl-config_secrets
  - ../../node-zio/etl-config_secrets

patches:
  - target:
      kind: Job
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
  - target:
      kind: Job
    patch: |-
      - op: replace
        path: /spec/template/spec/imagePullSecrets
        value:
        - name: registry-credentials
  # Patch the data mounts to use the GIT PVC
  - path: patches/job/envida-etl-zib-delete-demo-data.yaml
  - path: patches/job/envida-etl-zib-add-demo-data.yaml
  - path: patches/job/vitala-etl-zib-delete-demo-data.yaml
  - path: patches/job/vitala-etl-zib-add-demo-data.yaml
  - path: patches/job/mumc-etl-zib-delete-demo-data.yaml
  - path: patches/job/mumc-etl-zib-add-demo-data.yaml
  - path: patches/job/zio-etl-zib-delete-demo-data.yaml
  - path: patches/job/zio-etl-zib-add-demo-data.yaml