apiVersion: v1
kind: ConfigMap
metadata:
  name: mumc-federation-rest-config
  namespace: dh-health
data:
  FEDERATION_LOGGER_FILENAME: "logs/mumc/federation-rest.log"
  FEDERATION_SERVER_URL: https://federation.mumc.local.dh.unimaas.nl:8443