apiVersion: v1
kind: ConfigMap
metadata:
  name: mumc-federation-rest-config
data:
  FEDERATION_LOGGER_FILENAME: "logs/mumc/federation-rest.log"
  FEDERATION_SERVER_URL: http://mumc-federation-rest.dh-health-mumc:8000