apiVersion: v1
kind: ConfigMap
metadata:
  name: mumc-federation-rest-config
  namespace: dh-health
data:
  LOGSTASH_TAGS: "FEDERATION_REST_MUMC"
  FEDERATION_LOGGER_FILENAME: "logs/federation-rest/federation-rest-mumc.log"
  FEDERATION_BASE_URL: http://federation.mumc.local.dh.unimaas.nl