apiVersion: apps/v1
kind: Deployment
metadata:
  name: mumc-federation-rest
  namespace: dh-health
  labels:
    app: mumc-federation-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mumc-federation-rest
  template:
    metadata:
      labels:
        app: mumc-federation-rest
    spec:
      containers:
        - name: mumc-federation-rest
          image: registry.prod.dh.unimaas.nl/docker-health/federation-rest:latest
          ports:
            - containerPort: 8000
          env:
            # EHRBASE
            - name: EHRBASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mumc-ehrbase-creds
                  key: username
            - name: EHRBASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mumc-ehrbase-creds
                  key: password
            - name: EHRBASE_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: mumc-etl-config
                  key: EHRBASE_BASE_URL
            # Service
            - name: NODENAME
              valueFrom:
                configMapKeyRef:
                  name: mumc-etl-config
                  key: NODENAME
            - name: FEDERATION_CLIENT_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: mumc-federation-key
                  key: key
            - name: FEDERATION_CLIENT_ACCOUNT_BTG_KEY
              valueFrom:
                secretKeyRef:
                  name: mumc-federation-break-the-glass-key
                  key: key
            - name: FEDERATION_SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: federation-service-creds
                  key: key
          envFrom:
            - configMapRef:
                name: timezone-config
            - configMapRef:
                name: mumc-federation-rest-config
          volumeMounts:
            - name: logs
              mountPath: /code/logs/mumc
              subPath: mumc/federation-rest
            - name: mumc-mtls-federation
              mountPath: /etc/mtls/federation
              readOnly: true
            - name: mumc-mtls-ca
              mountPath: /etc/mtls/ca
              readOnly: true
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: log-pvc
        - name: mumc-mtls-federation
          secret:
            secretName: mumc-mtls-federation
        - name: mumc-mtls-ca
          secret:
            secretName: mumc-mtls-ca