apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
  - name: test-ehrbase-creds
    literals:
      - username=user0
      - password=foobar0
  - name: test-ehrbase-admin-creds   
    literals:
      - username=admin0
      - password=admin0
  - name: test-ehrbase-db-admin-creds
    literals:
      - username=ehrbase0
      - password=ehrbase0
  - name: test-ehrbase-db-creds
    literals:
      - username=ehrbase_restricted0
      - password=ehrbase_restricted0
  - name: test-ehrbase-db-postgres-creds
    literals:
      - username=postgres
      - password=postgres
  - name: test-transform-creds
    literals:
      - username=transform0
      - password=transform0
