filter {
    if "EHRBASE" in [tags] {

        mutate {
            add_field => { "logtrail" => "hdp-ehrbase" }
            add_tag => [ "CP24_MUT01" ]
        }

        grok {
            break_on_match => true
            # Exclude static fields: trace_id=1, service=ehrbase
            match => { "message" => "^%{TIMESTAMP_ISO8601:timestamp} +%{DATA:level} +%{NUMBER} +--- +\[%{DATA}\] +\[%{DATA:ehrbase.thread}\] +%{DATA:ehrbase.logger_name} +: +%{GREEDYDATA:log_message}" }
            add_tag => [ "CP24_GRO01" ]
        }

        date {
            timezone => "Europe/Amsterdam"
            match => [ "timestamp" ,
                       "ISO8601",
                       "yyyy/MM/dd HH:mm:ss.SSSZ",
                       "yyyy-MM-dd HH:mm:ss.SSSZ"
                     ]
            remove_field => [ "timestamp" ]       # cleanup, data is available in @timestamp
            add_tag => [ "CP24_DAT01" ]
        }
    }
}
