output {

    elasticsearch {
        hosts => ["https://localhost:9200"]
        index => "filebeat-%{+YYYY.MM}"

        user => "elastic"
        # WORKAROUND It seems like the user logstash doesn't access to the env var "${ELASTIC_PASSWORD}"
        # so "ELASTIC_PASSWORD" replaced in elk/start.sh
        password => "ELASTIC_PASSWORD"

        ssl_enabled => true
        ssl_certificate_authorities => ['/etc/logstash/config/certs/http_ca.crt']
    }

    # Enable the part below to write out useful logstash debug information
#    file {
#        path => "/tmp/logstashdebug.txt"
#        codec => rubydebug
#    }

}
