output {

    elasticsearch {
        hosts => ["localhost"]
        index => "idx-%{+YYYY.MM}"

        # Enforce no SSL between logstash and elasticsearch
        # Both service are in the same container, the traffic is all internal.
        ssl_enabled => false
        ssl_verification_mode => none
    }

    # Enable the part below to write out useful logstash debug information
#    file {
#        path => "/tmp/logstashdebug.txt"
#        codec => rubydebug
#    }

}
