output {

    elasticsearch {
        hosts => ["localhost"]
        index => "idx-%{+YYYY.MM}"

        ssl_enabled => false
        ssl_verification_mode => none
    }

    # Enable the part below to write out useful logstash debug information
#    file {
#        path => "/tmp/logstashdebug.txt"
#        codec => rubydebug
#    }

}
