apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dh-health-zio

resources:
  - vault-auth.yaml
  - ../../../base/openehr-nodes/zio
  - config
  - service-discovery

components:
  - components
  - ../shared-components

patches:
  - target:
      group: batch
      version: v1
      kind: Job
      name: etl-zib-pipeline
    patch: |
      - op: replace
        path: /spec/template/spec/volumes/1/hostPath/path
        value: /mnt/demo-data/data/zio-demo-data
      - op: replace
        path: /spec/template/spec/volumes/1/hostPath/type
        value: DirectoryOrCreate

configMapGenerator:
- name: proxy-config
  envs:
    - ../../../base-config/proxy.env
