apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terminology-server-proxy-creds
  namespace: dh-health
  labels:
    ehrnode: all
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: SecretStore
  target:
    name: terminology-server-proxy-creds
    template:
      engineVersion: v2
      data:
        username: "datahub@maastrichtuniversity.nl"
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: hdp-env/terminology-server-proxy-creds
      property: datahub@maastrichtuniversity.nl
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: transform-creds
  namespace: dh-health
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: SecretStore
  target:
    name: transform-creds
    template:
      engineVersion: v2
      data:
        username: "user"
        password: "{{ .user }}"
  dataFrom:
    - extract:
        key: hdp-env/transform-creds
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jupyter-zib-creds
  namespace: dh-health
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: SecretStore
  target:
    name: jupyter-zib-creds
    template:
      engineVersion: v2
      data:
        SERVER_APP_TOKEN: "{{ .SERVER_APP_TOKEN }}"
  dataFrom:
    - extract:
        key: hdp-env/jupyter-zib-creds