apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vitala-transform-rest-ingress
  namespace: dh-health
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: transform.vitala.local.dh.unimaas.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vitala-transform-rest
            port:
              number: 8080
