apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - jupyter-ingress.yaml

secretGenerator:
  - name: jupyter-zib-creds
    namespace: dh-health
    literals:
      - SERVER_APP_TOKEN=aa3ca297f81ed69a3fcab71ff886d5cf3207be09960f6de7
