apiVersion: v1
kind: ConfigMap
metadata:
  name: envida-federation-rest-config
  namespace: dh-health
data:
  LOGSTASH_TAGS: "FEDERATION_REST_ENVIDA"
  FEDERATION_LOGGER_FILENAME: "logs/federation-rest/federation-rest-envida.log"
  FEDERATION_SERVER_URL: http://envida-federation-rest.dh-health:8000