apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: vitala-openehrtool-gateway 
spec:
  gatewayClassName: traefik
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      hostname: openehrtool.vitala.local.dh.unimaas.nl
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vitala-openehrtool-route 
spec:
  parentRefs:
    - name: vitala-openehrtool-gateway
  hostnames:
    - openehrtool.vitala.local.dh.unimaas.nl
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: openehrtool
          port: 9000
