apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dh-health-vitala

resources:
  # VITALA-node
  - ../../../../../base/openehr-nodes/vitala/ehrbase
  - ../../../../../base/openehr-nodes/vitala/ehrdb
  - ../../../../../base/openehr-nodes/vitala/etl-zib
  - ../../../../../base/openehr-nodes/vitala/federation-rest
  - ../../../../../base/openehr-nodes/vitala/terminology-server-proxy
  - ../../../../../base/openehr-nodes/vitala/transform-rest
  - ../../../../../base/openehr-nodes/vitala/volumes
  - ../../../node-vitala/service-discovery
  - ../../../node-vitala/config

components:
  - ../../../shared-components
  # VITALA-node
  - ../../../node-vitala/components/ehrbase-gateway
  - ../../../node-vitala/components/federation-rest-gateway
  - ../../../node-vitala/components/transform-rest-gateway
  - ../../../node-vitala/components/terminology-server-proxy-gateway
  - ../../../node-vitala/components/secrets
