apiVersion: batch/v1
kind: Job
metadata:
  name: etl-zib-pipeline
spec:
  template:
    spec:
      containers:
        - name: etl-zib-pipeline
          volumeMounts:
            - name: demo-data
              mountPath: /code/data/vitala-demo-data
              subPath: src/data/vitala-demo-data
      volumes:
        - name: demo-data
          persistentVolumeClaim:
            claimName: git-repo-pvc
