apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-zib
spec:
  template:
    spec:
      initContainers:
        - name: git-clone
          image: bitnami/git:latest
          envFrom:
            - configMapRef:
                name: git-config
          command:
            - sh
            - -c
            - |
              git clone https://github.com/MaastrichtUniversity/docker-health.git /repo
              ls /repo
              cd /repo
              git checkout "$GIT_BRANCH"
          volumeMounts:
            - name: git-repo
              mountPath: /repo
      containers:
        - name: jupyter-zib
          volumeMounts:
            - name: git-repo
              mountPath: /home/jovyan/data
              subPath: data
      volumes:
        - name: git-repo
          emptyDir:
            sizeLimit: 500Mi