apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Never

# Individual ingress host patches
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: transform-rest-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: transform.local.dh.unimaas.nl

- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: federation-api-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: federation.local.dh.unimaas.nl

- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: jupyter-zib-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: jupyter.local.dh.unimaas.nl

- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: test-ehrbase-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: ehrbase.test.local.dh.unimaas.nl

- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: mumc-ehrbase-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: ehrbase.mumc.local.dh.unimaas.nl

- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: zio-ehrbase-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: ehrbase.zio.local.dh.unimaas.nl

- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: envida-ehrbase-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: ehrbase.envida.local.dh.unimaas.nl

- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: mumc-etl-zib-rest-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: etl.mumc.local.dh.unimaas.nl

- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: zio-etl-zib-rest-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: etl.zio.local.dh.unimaas.nl

- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: envida-etl-zib-rest-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: etl.envida.local.dh.unimaas.nl

- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: mumc-portal-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: portal.mumc.local.dh.unimaas.nl

- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: zio-portal-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: portal.zio.local.dh.unimaas.nl

- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: envida-portal-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: portal.envida.local.dh.unimaas.nl

- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: test-openehrtool-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: openehrtool.test.local.dh.unimaas.nl

- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: mumc-openehrtool-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: openehrtool.mumc.local.dh.unimaas.nl

- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: zio-openehrtool-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: openehrtool.zio.local.dh.unimaas.nl

- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: envida-openehrtool-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: openehrtool.envida.local.dh.unimaas.nl

secretGenerator:
# Envida-node
  - name: envida-ehrbase-creds
    namespace: dh-health
    literals:
    - username=user3
    - password=foobar3
  - name: envida-ehrbase-admin-creds
    namespace: dh-health
    literals:
    - username=admin3
    - password=admin3
  - name: envida-ehrbase-db-admin-creds
    namespace: dh-health
    literals:
    - username=ehrbase3
    - password=ehrbase3
  - name: envida-ehrbase-db-creds
    namespace: dh-health
    literals:
    - username=ehrbase_restricted3
    - password=ehrbase_restricted3
  - name: envida-portal-creds
    namespace: dh-health
    literals:
    - username=demo@envida.nl
    - password=foobar
  - name: envida-federation-key
    namespace: dh-health
    literals:
      - key=key3
  - name: envida-federation-break-the-glass-key
    namespace: dh-health
    literals:
      - key=btgkey3
# MUMC-node
  - name: mumc-ehrbase-creds
    namespace: dh-health
    literals:
      - username=user1
      - password=foobar1
  - name: mumc-ehrbase-admin-creds
    namespace: dh-health
    literals:
      - username=admin1
      - password=admin1
  - name: mumc-ehrbase-db-admin-creds
    namespace: dh-health
    literals:
      - username=ehrbase1
      - password=ehrbase1
  - name: mumc-ehrbase-db-creds
    namespace: dh-health
    literals:
      - username=ehrbase_restricted1
      - password=ehrbase_restricted1
  - name: mumc-portal-creds
    namespace: dh-health
    literals:
      - username=demo@mumc.nl
      - password=foobar
  - name: mumc-federation-key
    namespace: dh-health
    literals:
      - key=key1
  - name: mumc-federation-break-the-glass-key
    namespace: dh-health
    literals:
      - key=btgkey1
# ZIO-node
  - name: zio-ehrbase-creds
    namespace: dh-health
    literals:
      - username=user2
      - password=foobar2
  - name: zio-ehrbase-admin-creds
    namespace: dh-health
    literals:
      - username=admin2
      - password=admin2
  - name: zio-ehrbase-db-admin-creds
    namespace: dh-health
    literals:
      - username=ehrbase2
      - password=ehrbase2
  - name: zio-ehrbase-db-creds
    namespace: dh-health
    literals:
      - username=ehrbase_restricted2
      - password=ehrbase_restricted2
  - name: zio-portal-creds
    namespace: dh-health
    literals:
      - username=demo@zio.nl
      - password=foobar
  - name: zio-federation-key
    namespace: dh-health
    literals:
      - key=key2
  - name: zio-federation-break-the-glass-key
    namespace: dh-health
    literals:
      - key=btgkey2
# TEST-node
  - name: test-ehrbase-creds
    namespace: dh-health
    literals:
      - username=user0
      - password=foobar0
  - name: test-ehrbase-admin-creds
    namespace: dh-health
    literals:
      - username=admin0
      - password=admin0
  - name: test-ehrbase-db-admin-creds
    namespace: dh-health
    literals:
      - username=ehrbase0
      - password=ehrbase0
  - name: test-ehrbase-db-creds
    namespace: dh-health
    literals:
      - username=ehrbase_restricted0
      - password=ehrbase_restricted0
# transform
  - name: transform-creds
    namespace: dh-health
    literals:
      - username=user
      - password=foobar

configMapGenerator:
- name: portal-common-config
  namespace: dh-health
  behavior: merge
  literals:
    - NEXT_PUBLIC_FEDERATION_API_URL=http://federation.local.dh.unimaas.nl
