apiVersion: apps/v1
kind: Deployment
metadata:
  name: envida-transform-rest
  namespace: dh-health
  labels:
    app: envida-transform-rest
spec:
  selector:
    matchLabels:
      app: envida-transform-rest
  template:
    metadata:
      labels:
        app: envida-transform-rest
    spec:
      containers:
      - name: envida-transform-rest
        image: registry.prod.dh.unimaas.nl/docker-health/transform-rest:latest
        ports:
        - containerPort: 8080
        env:
          - name: TRANSFORM_SPRING_USERNAME
            valueFrom:
              secretKeyRef:
                name: envida-transform-creds
                key: username
          - name: TRANSFORM_SPRING_PASSWORD
            valueFrom:
              secretKeyRef:
                name: envida-transform-creds
                key: password
        envFrom:
        - configMapRef:
            name: dry-run-config
        - configMapRef:
            name: timezone-config
        - configMapRef:
            name: transform-rest-config
        - configMapRef:
            name: envida-transform-rest-config
        - configMapRef:
            name: zib-templates-config
        volumeMounts:
        - name: transform-rest-logs
          mountPath: /var/log/envida
          subPath: envida/transform-rest
      volumes:
      - name: transform-rest-logs
        persistentVolumeClaim:
          claimName: log-pvc
