apiVersion: v1
kind: Service
metadata:
  name: envida-transform-rest
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: envida-transform-rest
