apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dh-health

resources:
- job.yaml
- role.yaml
- secrets.yaml
- ../demo-data
- ../../../base/common
- ../../../base/federation-rest
- ../../../base/transform-rest
- ../../../base/terminology-server-proxy
# Envida-node
- ../../../base/openehr-nodes/envida/ehrbase
- ../../../base/openehr-nodes/envida/ehrdb
- ../../../base/openehr-nodes/envida/etl-config
- ../../../base/openehr-nodes/envida/etl-zib-pipeline
# MUMC-node
- ../../../base/openehr-nodes/mumc/ehrbase
- ../../../base/openehr-nodes/mumc/ehrdb
- ../../../base/openehr-nodes/mumc/etl-config
- ../../../base/openehr-nodes/mumc/etl-zib-pipeline
# VITALA-node
- ../../../base/openehr-nodes/vitala/ehrbase
- ../../../base/openehr-nodes/vitala/ehrdb
- ../../../base/openehr-nodes/vitala/etl-config
- ../../../base/openehr-nodes/vitala/etl-zib-pipeline
# ZIO-node
- ../../../base/openehr-nodes/zio/ehrbase
- ../../../base/openehr-nodes/zio/ehrdb
- ../../../base/openehr-nodes/zio/etl-config
- ../../../base/openehr-nodes/zio/etl-zib-pipeline

images:
- name: registry.prod.dh.unimaas.nl/docker-health/federation-test
  newTag: '2024.1.3'
- name: registry.prod.dh.unimaas.nl/docker-health/etl-zib-pipeline
  newTag: '2024.1.3'
- name: registry.prod.dh.unimaas.nl/docker-health/transform-rest
  newTag: '2024.1.3'
- name: registry.prod.dh.unimaas.nl/docker-health/terminology-server-proxy
  newTag: '2024.1.3'

patches:
# imagePullPolicy patches
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: IfNotPresent
- target:
    kind: Job
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: IfNotPresent

# Image pull secret
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/imagePullSecrets
      value:
      - name: registry-credentials
- target:
    kind: Job
  patch: |-
    - op: replace
      path: /spec/template/spec/imagePullSecrets
      value:
      - name: registry-credentials

# Storage class patches
- target:
    kind: PersistentVolume
  patch: |-
    - op: replace
      path: /spec/storageClassName
      value: local-path
- target:
    kind: PersistentVolumeClaim
  patch: |-
    - op: replace
      path: /spec/storageClassName
      value: local-path

# Proxy patches
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: http_proxy
        value: "http://proxy.unimaas.nl:3128"
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: https_proxy
        value: "http://proxy.unimaas.nl:3128"
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: no_proxy
        value: "localhost,.dh.local,.dh-health,.unimaas.nl,.datahubmaastricht.nl,137.120.31.0/16,.cluster.local,10.42.0.0/16,10.43.0.1,10.43.0.10"

# Individual ingress host patches
## Transform
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: transform-rest-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: transform.tst.dh.unimaas.nl
## Federation
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: federation-rest-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: federation.tst.dh.unimaas.nl
## Envida-node
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: envida-ehrbase-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: ehrbase.envida.tst.dh.unimaas.nl
## MUMC-node
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: mumc-ehrbase-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: ehrbase.mumc.tst.dh.unimaas.nl
## VITALA-node
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: vitala-ehrbase-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: ehrbase.vitala.tst.dh.unimaas.nl
## ZIO-node
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: zio-ehrbase-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: ehrbase.zio.tst.dh.unimaas.nl

# Patch the data mounts to use the GIT PVC
- target:
    kind: Job
    name: envida-etl-zib-pipeline
  patch: |-
    - op: replace
      path: /spec/template/spec/volumes/1  # assuming 'data' is the 2nd volume in the array
      value:
        name: data
        persistentVolumeClaim:
          claimName: git-repo-pvc
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/1/subPath
      value: src/data/envida-demo-data
- target:
    kind: Job
    name: zio-etl-zib-pipeline
  patch: |-
    - op: replace
      path: /spec/template/spec/volumes/1  # assuming 'data' is the 2nd volume in the array
      value:
        name: data
        persistentVolumeClaim:
          claimName: git-repo-pvc
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/1/subPath
      value: src/data/zio-demo-data
- target:
    kind: Job
    name: vitala-etl-zib-pipeline
  patch: |-
    - op: replace
      path: /spec/template/spec/volumes/1  # assuming 'data' is the 2nd volume in the array
      value:
        name: data
        persistentVolumeClaim:
          claimName: git-repo-pvc
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/1/subPath
      value: src/data/vitala-demo-data
- target:
    kind: Job
    name: mumc-etl-zib-pipeline
  patch: |-
    - op: replace
      path: /spec/template/spec/volumes/1  # assuming 'data' is the 2nd volume in the array
      value:
        name: data
        persistentVolumeClaim:
          claimName: git-repo-pvc
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/1/subPath
      value: src/data/mumc-demo-data
- target:
    kind: Deployment
    name: jupyter-zib
  patch: |-
    - op: remove
      path: /spec/template/spec/volumes/0
    - op: remove
      path: /spec/template/spec/containers/0/volumeMounts/0
    - op: add
      path: /spec/template/spec/volumes/0
      value:
        name: demo-data
        persistentVolumeClaim:
          claimName: git-repo-pvc
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/0
      value:
        name: demo-data
        mountPath: /home/jovyan/data
        subPath: src/data
