apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dh-health

resources:
- secrets.yaml
- job.yaml
- role.yaml
- ../../../base/common
- ../../../base/federation-rest
- ../../../base/transform-rest
- ../../../base/terminology-server-proxy
# Envida-node
- ../../../base/openehr-nodes/envida/ehrbase
- ../../../base/openehr-nodes/envida/ehrdb
- ../../../base/openehr-nodes/envida/etl-config
- ../../../base/openehr-nodes/envida/etl-zib-pipeline
# MUMC-node
- ../../../base/openehr-nodes/mumc/ehrbase
- ../../../base/openehr-nodes/mumc/ehrdb
- ../../../base/openehr-nodes/mumc/etl-config
- ../../../base/openehr-nodes/mumc/etl-zib-pipeline
# VITALA-node
- ../../../base/openehr-nodes/vitala/ehrbase
- ../../../base/openehr-nodes/vitala/ehrdb
- ../../../base/openehr-nodes/vitala/etl-config
- ../../../base/openehr-nodes/vitala/etl-zib-pipeline
# ZIO-node
- ../../../base/openehr-nodes/zio/ehrbase
- ../../../base/openehr-nodes/zio/ehrdb
- ../../../base/openehr-nodes/zio/etl-config
- ../../../base/openehr-nodes/zio/etl-zib-pipeline

images:
- name: registry.prod.dh.unimaas.nl/docker-health/federation-test
  newTag: '2024.1.3'
- name: registry.prod.dh.unimaas.nl/docker-health/etl-zib-pipeline
  newTag: '2024.1.3'
- name: registry.prod.dh.unimaas.nl/docker-health/transform-rest
  newTag: '2024.1.3'
- name: registry.prod.dh.unimaas.nl/docker-health/terminology-server-proxy
  newTag: '2024.1.3'

patches:
# imagePullPolicy patches
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: IfNotPresent
- target:
    kind: Job
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: IfNotPresent

# Image pull secret
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/imagePullSecrets
      value:
      - name: registry-credentials
- target:
    kind: Job
  patch: |-
    - op: replace
      path: /spec/template/spec/imagePullSecrets
      value:
      - name: registry-credentials

# Storage class patches
- target:
    kind: PersistentVolume
  patch: |-
    - op: replace
      path: /spec/storageClassName
      value: local-path
- target:
    kind: PersistentVolumeClaim
  patch: |-
    - op: replace
      path: /spec/storageClassName
      value: local-path

# Proxy patches
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: http_proxy
        value: "http://proxy.unimaas.nl:3128"
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: https_proxy
        value: "http://proxy.unimaas.nl:3128"
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: no_proxy
        value: "localhost,.dh.local,.dh-health,.unimaas.nl,.datahubmaastricht.nl,137.120.31.0/16,.cluster.local,10.42.0.0/16,10.43.0.1,10.43.0.10"

# Ingress patches
## Transform
- path: patches/ingress/common/transform.yaml
## Federation
- path: patches/ingress/common/federation.yaml
## Envida-node
- path: patches/ingress/envida/ehrbase.yaml
## MUMC-node
- path: patches/ingress/mumc/ehrbase.yaml
## VITALA-node
- path: patches/ingress/vitala/ehrbase.yaml
## ZIO-node
- path: patches/ingress/zio/ehrbase.yaml

# Patch the data mounts to use the GIT PVC
- path: patches/job/envida-etl-zib-delete-demo-data.yaml
- path: patches/job/envida-etl-zib-add-demo-data.yaml
- path: patches/job/vitala-etl-zib-delete-demo-data.yaml
- path: patches/job/vitala-etl-zib-add-demo-data.yaml
- path: patches/job/mumc-etl-zib-delete-demo-data.yaml
- path: patches/job/mumc-etl-zib-add-demo-data.yaml
- path: patches/job/zio-etl-zib-delete-demo-data.yaml
- path: patches/job/zio-etl-zib-add-demo-data.yaml