apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nodes
  - job

patches:
  # imagePullPolicy patches
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
  # Image pull secret
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/imagePullSecrets
        value:
        - name: registry-credentials
  # Storage class patches
  - target:
      kind: PersistentVolume
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: local-path
  - target:
      kind: PersistentVolumeClaim
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: local-path
