# Envida secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: envida-ehrbase-creds
  namespace: dh-health
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: SecretStore
  target:
    name: envida-ehrbase-creds
    template:
      engineVersion: v2
      data:
        username: "user3"
        password: "{{ .envida_ehrbase_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/envida
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: envida-federation-key
  namespace: dh-health
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: SecretStore
  target:
    name: envida-federation-key
    template:
      engineVersion: v2
      data:
        key: "{{ .envida_federation_key }}"
  dataFrom:
    - extract:
        key: hdp-env/envida
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: envida-federation-break-the-glass-key
  namespace: dh-health
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: SecretStore
  target:
    name: envida-federation-break-the-glass-key
    template:
      engineVersion: v2
      data:
        key: "{{ .envida_federation_break_the_glass_key }}"
  dataFrom:
    - extract:
        key: hdp-env/envida
---
# MUMC secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mumc-ehrbase-creds
  namespace: dh-health
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: SecretStore
  target:
    name: mumc-ehrbase-creds
    template:
      engineVersion: v2
      data:
        username: "user1"
        password: "{{ .mumc_ehrbase_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/mumc
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mumc-federation-key
  namespace: dh-health
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: SecretStore
  target:
    name: mumc-federation-key
    template:
      engineVersion: v2
      data:
        key: "{{ .mumc_federation_key }}"
  dataFrom:
    - extract:
        key: hdp-env/mumc
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mumc-federation-break-the-glass-key
  namespace: dh-health
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: SecretStore
  target:
    name: mumc-federation-break-the-glass-key
    template:
      engineVersion: v2
      data:
        key: "{{ .mumc_federation_break_the_glass_key }}"
  dataFrom:
    - extract:
        key: hdp-env/mumc
---
# Vitala secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vitala-ehrbase-creds
  namespace: dh-health
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: SecretStore
  target:
    name: vitala-ehrbase-creds
    template:
      engineVersion: v2
      data:
        username: "user4"
        password: "{{ .vitala_ehrbase_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/vitala
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vitala-federation-key
  namespace: dh-health
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: SecretStore
  target:
    name: vitala-federation-key
    template:
      engineVersion: v2
      data:
        key: "{{ .vitala_federation_key }}"
  dataFrom:
    - extract:
        key: hdp-env/vitala
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vitala-federation-break-the-glass-key
  namespace: dh-health
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: SecretStore
  target:
    name: vitala-federation-break-the-glass-key
    template:
      engineVersion: v2
      data:
        key: "{{ .vitala_federation_break_the_glass_key }}"
  dataFrom:
    - extract:
        key: hdp-env/vitala
---
# Zio secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zio-ehrbase-creds
  namespace: dh-health
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: SecretStore
  target:
    name: zio-ehrbase-creds
    template:
      engineVersion: v2
      data:
        username: "user2"
        password: "{{ .zio_ehrbase_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/zio
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zio-federation-key
  namespace: dh-health
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: SecretStore
  target:
    name: zio-federation-key
    template:
      engineVersion: v2
      data:
        key: "{{ .zio_federation_key }}"
  dataFrom:
    - extract:
        key: hdp-env/zio
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zio-federation-break-the-glass-key
  namespace: dh-health
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: SecretStore
  target:
    name: zio-federation-break-the-glass-key
    template:
      engineVersion: v2
      data:
        key: "{{ .zio_federation_break_the_glass_key }}"
  dataFrom:
    - extract:
        key: hdp-env/zio