apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: portal-creds
  labels:
    ehrnode: all
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: portal-creds
    template:
      engineVersion: v2
      data:
        username: "demo@zio.nl"
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: hdp-env/zio
      property: demo@zio.nl
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ehrbase-creds
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: ehrbase-creds
    template:
      engineVersion: v2
      data:
        username: "user2"
        password: "{{ .zio_ehrbase_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/zio
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ehrbase-admin-creds
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: ehrbase-admin-creds
    template:
      engineVersion: v2
      data:
        username: "admin2"
        password: "{{ .zio_ehrbase_admin_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/zio
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ehrbase-db-admin-creds
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: ehrbase-db-admin-creds
    template:
      engineVersion: v2
      data:
        username: "ehrbase2"
        password: "{{ .zio_ehrbase_db_admin_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/zio
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ehrbase-db-creds
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: ehrbase-db-creds
    template:
      engineVersion: v2
      data:
        username: "ehrbase_restricted2"
        password: "{{ .zio_ehrbase_db_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/zio
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ehrbase-db-postgres-creds
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: ehrbase-db-postgres-creds
    template:
      engineVersion: v2
      data:
        username: "postgres"
        password: "{{ .zio_ehrbase_db_postgres_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/zio
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: federation-key
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: federation-key
    template:
      engineVersion: v2
      data:
        key: "{{ .zio_federation_key }}"
  dataFrom:
    - extract:
        key: hdp-env/zio
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: federation-break-the-glass-key
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: federation-break-the-glass-key
    template:
      engineVersion: v2
      data:
        key: "{{ .zio_federation_break_the_glass_key }}"
  dataFrom:
    - extract:
        key: hdp-env/zio
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: transform-creds
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: transform-creds
    template:
      engineVersion: v2
      data:
        username: "transform2"
        password: "{{ .zio_transform_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/zio