apiVersion: batch/v1
kind: Job
metadata:
  name: vitala-etl-zib-pipeline
  namespace: dh-health
  labels:
    app: vitala-etl-zib-pipeline
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: vitala-etl-zib-pipeline
    spec:
      restartPolicy: Never
      initContainers:
      - name: wait-terminology-proxy
        image: registry.prod.dh.unimaas.nl/docker-health/init-container:latest
        imagePullPolicy: IfNotPresent
        command:
          - "/wait-for-service.sh"
          - "http://terminology-server-proxy.dh-health:8080/management/health"
          - "Terminology server proxy"
      - name: wait-ehrbase
        image: registry.prod.dh.unimaas.nl/docker-health/init-container:latest
        imagePullPolicy: IfNotPresent
        command:
          - "/wait-for-service.sh"
          - "http://vitala-ehrbase.dh-health:8080/ehrbase/management/health"
          - "EHRbase"
      - name: wait-transform-rest
        image: registry.prod.dh.unimaas.nl/docker-health/init-container:latest
        imagePullPolicy: IfNotPresent
        command:
          - "/wait-for-service.sh"
          - "http://vitala-transform-rest.dh-health:8080/management/health"
          - "Transform REST"
      containers:
      - name: vitala-etl-zib-pipeline
        image: registry.prod.dh.unimaas.nl/docker-health/etl-zib-pipeline:latest
        envFrom:
        - configMapRef:
            name: dry-run-config
        - configMapRef:
            name: timezone-config
        - configMapRef:
            name: zib-templates-config
        - configMapRef:
            name: etl-config
        - configMapRef:
            name: vitala-etl-config
        env:
        - name: EHRBASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: vitala-ehrbase-creds
              key: username
        - name: EHRBASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vitala-ehrbase-creds
              key: password
        - name: TRANSFORM_SPRING_USERNAME
          valueFrom:
            secretKeyRef:
              name: vitala-transform-creds
              key: username
        - name: TRANSFORM_SPRING_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vitala-transform-creds
              key: password
        volumeMounts:
        - name: outputs
          mountPath: /code/outputs
          subPath: vitala/pipeline
        - name: data
          mountPath: /code/data/vitala-demo-data
        - name: etl-logs
          mountPath: /code/logs/vitala
          subPath: vitala/pipeline
      volumes:
      - name: outputs
        persistentVolumeClaim:
            claimName: output-pvc
      - name: data
        hostPath:
          path: /mnt/data/vitala-demo-data
          type: Directory
      - name: etl-logs
        persistentVolumeClaim:
          claimName: log-pvc
