apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - data-encryption-secret
  - federation-secret
# Remove "service-discovery" in the shared components list to avoid name collision
# Only one ClusterRole can exist with the same name inside the cluster (across all namespace)
# It will avoid that each node will try to create the services-list ClusterRole
#  - service-discovery
  - terminology-server-proxy-secret
