apiVersion: v1
kind: ConfigMap
metadata:
  name: envida-etl-config
  namespace: dh-health
data:
  NODENAME: envida
  DATASET_FOLDER_NAME: envida-demo-data
  SOURCE_SYSTEM_ID: "Nedap Ons"
  LOGGER_FILENAME: logs/envida/etl-zib.log
  EHRBASE_BASE_URL: http://envida-ehrbase.dh-health:8080/ehrbase/rest/openehr/v1
  WRITE_COMPOSITION: "True"
  # If SUBJECT_IDS is empty, extract subject_ids from dataset:
  SUBJECT_IDS: |
    []
  TEMPLATE_IDS: |
    [
      "DataHub-AlcoholGebruik-2024",
      "DataHub-Bloeddruk-2024",
      "DataHub-BurgerlijkeStaat-2024",
      "DataHub-Contactpersoon-2024",
      "DataHub-Gezinssituatie-2024",
      "DataHub-InformedConsent",
      "DataHub-Lichaamsgewicht-2024",
      "DataHub-Lichaamslengte-2024",
      "DataHub-Patient-2024",
      "DataHub-TabakGebruik-2024",
      "DataHub-VermogenTotZichWassen-2024",
      "DataHub-VermogenTotZichKleden-2024",
      "DataHub-VermogenTotUiterlijkeVerzorging-2024",
      "DataHub-VermogenTotZelfstandigMedicatiegebruik-2024",
      "DataHub-VermogenTotDrinken-2024",
      "DataHub-VermogenTotEten-2024",
      "DataHub-VermogenTotMondverzorging-2024",
      "DataHub-VermogenTotToiletgang-2024",
      "DataHub-Woonsituatie-2024"
    ]
