apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namePrefix field prepends a string to the names of all resources, including configMapGenerator and secretGenerator.
namePrefix: zio-

resources:
  - ../../../../base/openehr-nodes/zio/etl-zib/etl-config

components:
  - ../components/secrets