apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-zib
  namespace: dh-health
  labels:
    app: jupyter-zib
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-zib
  template:
    metadata:
      labels:
        app: jupyter-zib
    spec:
      containers:
      - name: jupyter-zib
        image: docker-health/jupyter-zib:latest
        command: ["start-notebook.sh", "--ServerApp.token=aa3ca297f81ed69a3fcab71ff886d5cf3207be09960f6de7"]
        ports:
          - containerPort: 8888
        env:
          - name: TRANSFORM_SPRING_USERNAME
            valueFrom:
              secretKeyRef:
                name: transform-creds
                key: username
          - name: TRANSFORM_SPRING_PASSWORD
            valueFrom:
              secretKeyRef:
                name: transform-creds
                key:
                  password
        envFrom:
          - configMapRef:
              name: timezone-config
          - configMapRef:
              name: transform-server-config
          - configMapRef:
              name: zib-templates-config
          - configMapRef:
              name: jupyter-zib-config
        volumeMounts:
          - name: demo-data
            mountPath: /home/jovyan/data
          - name: notebooks
            mountPath: /home/jovyan/notebooks
          - name: etl
            mountPath: /home/jovyan/etl.py
          - name: requirements
            mountPath: /home/jovyan/requirements.txt
          - name: src
            mountPath: /home/jovyan/src
      volumes:
        - name: demo-data
          hostPath:
            path: /mnt/data
            type: Directory
        - name: notebooks
          hostPath:
            path: /mnt/externals/dh-hdp-notebooks
            type: Directory
        - name: etl
          hostPath:
            path: /mnt/externals/dh-hdp-etl/etl.py
            type: File
        - name: requirements
          hostPath:
            path: /mnt/externals/dh-hdp-etl/requirements.txt
            type: File
        - name: src
          hostPath:
            path: /mnt/externals/dh-hdp-etl/src
            type: Directory
            