apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-zib
  namespace: dh-health
  labels:
    app: jupyter-zib
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-zib
  template:
    metadata:
      labels:
        app: jupyter-zib
    spec:
      securityContext:
        runAsUser: 0 # Run as Root to avoid permission issue with volume mount
      initContainers:
        # WORKAROUND to give ownership of the volume-mount log file to the "ehrbase" user
        # The EHRbase container runs as a non-root user "ehrbase"
        # The files in a volume-mount are owned by root
        - name: init-log-dir
          image: busybox:1.28
          command: [ "/bin/sh", "-c" ]
          args:
            # uid=1000(jovyan) gid=100(users) groups=100(users)
            - mkdir -p /var/log/jupyter && chown 1000:100 /var/log/jupyter
          volumeMounts:
            - name: jupyter-logs
              mountPath: /var/log/jupyter
              subPath: jupyter
      containers:
      - name: jupyter-zib
        image: registry.prod.dh.unimaas.nl/docker-health/jupyter-zib:latest
        command: ["start-notebook.sh", "--ServerApp.token=$(APP_TOKEN)"]
        ports:
          - containerPort: 8888
        env:
          # Jupyter configuration
          - name: CHOWN_HOME # https://jupyter-docker-stacks.readthedocs.io/en/latest/using/troubleshooting.html#permission-denied-when-mounting-volumes
            value: 'yes'
          - name: CHOWN_HOME_OPTS # Ensure all the subfolders below "/home/jovyan" are owned by the user "jovyan", including the volume folder "/home/jovyan/work"
            value: '-R'
          - name: APP_TOKEN
            valueFrom:
              secretKeyRef:
                name: jupyter-zib-creds
                key: SERVER_APP_TOKEN
          # Envida-node
          - name: ENVIDA__EHRBASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: envida-ehrbase-creds
                key: username
          - name: ENVIDA__EHRBASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: envida-ehrbase-creds
                key: password
          - name: ENVIDA__EHRBASE_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: envida-etl-config
                key: EHRBASE_BASE_URL
          - name: ENVIDA__DATASET_FOLDER_NAME
            valueFrom:
              configMapKeyRef:
                name: envida-etl-config
                key: DATASET_FOLDER_NAME
          - name: ENVIDA__SOURCE_SYSTEM_ID
            valueFrom:
              configMapKeyRef:
                name: envida-etl-config
                key: SOURCE_SYSTEM_ID
          - name: ENVIDA__LOGGER_FILENAME
            valueFrom:
              configMapKeyRef:
                name: envida-etl-config
                key: LOGGER_FILENAME
          - name: ENVIDA__TRANSFORM_SPRING_USERNAME
            valueFrom:
              secretKeyRef:
                name: envida-transform-creds
                key: username
          - name: ENVIDA__TRANSFORM_SPRING_PASSWORD
            valueFrom:
              secretKeyRef:
                name: envida-transform-creds
                key:
                  password
          - name: ENVIDA__TRANSFORM_SPRING_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: envida-etl-config
                key: TRANSFORM_SPRING_BASE_URL
          # MUMC-node
          - name: MUMC__EHRBASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: mumc-ehrbase-creds
                key: username
          - name: MUMC__EHRBASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mumc-ehrbase-creds
                key: password
          - name: MUMC__EHRBASE_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: mumc-etl-config
                key: EHRBASE_BASE_URL
          - name: MUMC__DATASET_FOLDER_NAME
            valueFrom:
              configMapKeyRef:
                name: mumc-etl-config
                key: DATASET_FOLDER_NAME
          - name: MUMC__SOURCE_SYSTEM_ID
            valueFrom:
              configMapKeyRef:
                name: mumc-etl-config
                key: SOURCE_SYSTEM_ID
          - name: MUMC__LOGGER_FILENAME
            valueFrom:
              configMapKeyRef:
                name: mumc-etl-config
                key: LOGGER_FILENAME
          - name: MUMC__TRANSFORM_SPRING_USERNAME
            valueFrom:
              secretKeyRef:
                name: mumc-transform-creds
                key: username
          - name: MUMC__TRANSFORM_SPRING_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mumc-transform-creds
                key:
                  password
          - name: MUMC__TRANSFORM_SPRING_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: mumc-etl-config
                key: TRANSFORM_SPRING_BASE_URL
          # VITALA-node
          - name: VITALA__EHRBASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: vitala-ehrbase-creds
                key: username
          - name: VITALA__EHRBASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: vitala-ehrbase-creds
                key: password
          - name: VITALA__EHRBASE_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: vitala-etl-config
                key: EHRBASE_BASE_URL
          - name: VITALA__DATASET_FOLDER_NAME
            valueFrom:
              configMapKeyRef:
                name: vitala-etl-config
                key: DATASET_FOLDER_NAME
          - name: VITALA__SOURCE_SYSTEM_ID
            valueFrom:
              configMapKeyRef:
                name: vitala-etl-config
                key: SOURCE_SYSTEM_ID
          - name: VITALA__LOGGER_FILENAME
            valueFrom:
              configMapKeyRef:
                name: vitala-etl-config
                key: LOGGER_FILENAME
          - name: VITALA__TRANSFORM_SPRING_USERNAME
            valueFrom:
              secretKeyRef:
                name: vitala-transform-creds
                key: username
          - name: VITALA__TRANSFORM_SPRING_PASSWORD
            valueFrom:
              secretKeyRef:
                name: vitala-transform-creds
                key:
                  password
          - name: VITALA__TRANSFORM_SPRING_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: vitala-etl-config
                key: TRANSFORM_SPRING_BASE_URL
          # ZIO-node
          - name: ZIO__EHRBASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: zio-ehrbase-creds
                key: username
          - name: ZIO__EHRBASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zio-ehrbase-creds
                key: password
          - name: ZIO__EHRBASE_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: zio-etl-config
                key: EHRBASE_BASE_URL
          - name: ZIO__DATASET_FOLDER_NAME
            valueFrom:
              configMapKeyRef:
                name: zio-etl-config
                key: DATASET_FOLDER_NAME
          - name: ZIO__SOURCE_SYSTEM_ID
            valueFrom:
              configMapKeyRef:
                name: zio-etl-config
                key: SOURCE_SYSTEM_ID
          - name: ZIO__LOGGER_FILENAME
            valueFrom:
              configMapKeyRef:
                name: zio-etl-config
                key: LOGGER_FILENAME
          - name: ZIO__TRANSFORM_SPRING_USERNAME
            valueFrom:
              secretKeyRef:
                name: zio-transform-creds
                key: username
          - name: ZIO__TRANSFORM_SPRING_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zio-transform-creds
                key:
                  password
          - name: ZIO__TRANSFORM_SPRING_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: zio-etl-config
                key: TRANSFORM_SPRING_BASE_URL
          # Test-node
          - name: TEST__EHRBASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: test-ehrbase-creds
                key: username
          - name: TEST__EHRBASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: test-ehrbase-creds
                key: password
          - name: TEST__EHRBASE_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: test-etl-config
                key: EHRBASE_BASE_URL
          - name: TEST__DATASET_FOLDER_NAME
            valueFrom:
              configMapKeyRef:
                name: test-etl-config
                key: DATASET_FOLDER_NAME
          - name: TEST__SOURCE_SYSTEM_ID
            valueFrom:
              configMapKeyRef:
                name: test-etl-config
                key: SOURCE_SYSTEM_ID
          - name: TEST__LOGGER_FILENAME
            valueFrom:
              configMapKeyRef:
                name: test-etl-config
                key: LOGGER_FILENAME
          - name: TEST__TRANSFORM_SPRING_USERNAME
            valueFrom:
              secretKeyRef:
                name: test-transform-creds
                key: username
          - name: TEST__TRANSFORM_SPRING_PASSWORD
            valueFrom:
              secretKeyRef:
                name: test-transform-creds
                key:
                  password
          - name: TEST__TRANSFORM_SPRING_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: test-etl-config
                key: TRANSFORM_SPRING_BASE_URL
        envFrom:
          - configMapRef:
              name: dry-run-config
          - configMapRef:
              name: timezone-config
          - configMapRef:
              name: zib-templates-config
          - configMapRef:
              name: etl-config
        volumeMounts:
          - name: demo-data
            mountPath: /home/jovyan/data
          - name: notebooks
            mountPath: /home/jovyan/work
          - name: jupyter-logs
            mountPath: /var/log/jupyter
            subPath: jupyter
      volumes:
        - name: demo-data
          hostPath:
            path: /mnt/data
            type: Directory
        - name: notebooks
          persistentVolumeClaim:
              claimName: notebooks-pvc
        - name: jupyter-logs
          persistentVolumeClaim:
            claimName: log-pvc
            