apiVersion: v1
kind: Service
metadata:
  name: jupyter-zib
  namespace: dh-health
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    app: jupyter-zib