apiVersion: v1
kind: PersistentVolume
metadata:
  name: notebooks-pv
  namespace: dh-health
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
     namespace: dh-health
     name: notebooks-pvc
  storageClassName: local
  hostPath:
    path: /usr/share/notebooks
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notebooks-pvc
  namespace: dh-health
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  resources:
    requests:
      storage: 1Gi