apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Append a suffix to services-list ClusterRole to avoid name collision
nameSuffix: -zio

components:
  - ../../shared-components/service-discovery