apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: envida-portal-creds
  labels:
    ehrnode: all
spec:
  refreshInterval: 24h
  SecretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: envida-portal-creds
    template:
      engineVersion: v2
      data:
        username: "demo@envida.nl"
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: hdp-env/envida
      property: demo@envida.nl
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: envida-ehrbase-creds
spec:
  refreshInterval: 24h
  SecretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: envida-ehrbase-creds
    template:
      engineVersion: v2
      data:
        username: "user3"
        password: "{{ .envida_ehrbase_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/envida
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: envida-ehrbase-admin-creds
spec:
  refreshInterval: 24h
  SecretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: envida-ehrbase-admin-creds
    template:
      engineVersion: v2
      data:
        username: "admin3"
        password: "{{ .envida_ehrbase_admin_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/envida
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: envida-ehrbase-db-admin-creds
spec:
  refreshInterval: 24h
  SecretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: envida-ehrbase-db-admin-creds
    template:
      engineVersion: v2
      data:
        username: "ehrbase3"
        password: "{{ .envida_ehrbase_db_admin_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/envida
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: envida-ehrbase-db-creds
spec:
  refreshInterval: 24h
  SecretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: envida-ehrbase-db-creds
    template:
      engineVersion: v2
      data:
        username: "ehrbase_restricted3"
        password: "{{ .envida_ehrbase_db_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/envida
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: envida-ehrbase-db-postgres-creds
spec:
  refreshInterval: 24h
  SecretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: envida-ehrbase-db-postgres-creds
    template:
      engineVersion: v2
      data:
        username: "postgres"
        password: "{{ .envida_ehrbase_db_postgres_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/envida
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: envida-federation-key
spec:
  refreshInterval: 24h
  SecretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: envida-federation-key
    template:
      engineVersion: v2
      data:
        key: "{{ .envida_federation_key }}"
  dataFrom:
    - extract:
        key: hdp-env/envida
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: envida-federation-break-the-glass-key
spec:
  refreshInterval: 24h
  SecretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: envida-federation-break-the-glass-key
    template:
      engineVersion: v2
      data:
        key: "{{ .envida_federation_break_the_glass_key }}"
  dataFrom:
    - extract:
        key: hdp-env/envida
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: envida-transform-creds
spec:
  refreshInterval: 24h
  SecretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: envida-transform-creds
    template:
      engineVersion: v2
      data:
        username: "transform3"
        password: "{{ .envida_transform_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/envida