apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vault-auth.yaml
  - jupyter-secrets.yaml
  - envida
  - mumc
  - vitala
  - zio

generatorOptions:
  disableNameSuffixHash: true
