apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mumc-portal-creds
  labels:
    ehrnode: all
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: mumc-portal-creds
    template:
      engineVersion: v2
      data:
        username: "demo@mumc.nl"
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: hdp-env/mumc
      property: demo@mumc.nl
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mumc-ehrbase-creds
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: mumc-ehrbase-creds
    template:
      engineVersion: v2
      data:
        username: "user1"
        password: "{{ .mumc_ehrbase_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/mumc
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mumc-ehrbase-admin-creds
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: mumc-ehrbase-admin-creds
    template:
      engineVersion: v2
      data:
        username: "admin1"
        password: "{{ .mumc_ehrbase_admin_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/mumc
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mumc-ehrbase-db-admin-creds
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: mumc-ehrbase-db-admin-creds
    template:
      engineVersion: v2
      data:
        username: "ehrbase1"
        password: "{{ .mumc_ehrbase_db_admin_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/mumc
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mumc-ehrbase-db-creds
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: mumc-ehrbase-db-creds
    template:
      engineVersion: v2
      data:
        username: "ehrbase_restricted3"
        password: "{{ .mumc_ehrbase_db_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/mumc
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mumc-ehrbase-db-postgres-creds
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: mumc-ehrbase-db-postgres-creds
    template:
      engineVersion: v2
      data:
        username: "postgres"
        password: "{{ .mumc_ehrbase_db_postgres_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/mumc
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mumc-federation-key
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: mumc-federation-key
    template:
      engineVersion: v2
      data:
        key: "{{ .mumc_federation_key }}"
  dataFrom:
    - extract:
        key: hdp-env/mumc
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mumc-federation-break-the-glass-key
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: mumc-federation-break-the-glass-key
    template:
      engineVersion: v2
      data:
        key: "{{ .mumc_federation_break_the_glass_key }}"
  dataFrom:
    - extract:
        key: hdp-env/mumc
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mumc-transform-creds
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: mumc-transform-creds
    template:
      engineVersion: v2
      data:
        username: "transform1"
        password: "{{ .mumc_transform_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/mumc