apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vitala-portal-creds
  labels:
    ehrnode: all
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: vitala-portal-creds
    template:
      engineVersion: v2
      data:
        username: "demo@vitala.nl"
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: hdp-env/vitala
      property: demo@vitala.nl
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vitala-ehrbase-creds
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: vitala-ehrbase-creds
    template:
      engineVersion: v2
      data:
        username: "user4"
        password: "{{ .vitala_ehrbase_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/vitala
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vitala-ehrbase-admin-creds
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: vitala-ehrbase-admin-creds
    template:
      engineVersion: v2
      data:
        username: "admin4"
        password: "{{ .vitala_ehrbase_admin_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/vitala
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vitala-ehrbase-db-admin-creds
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: vitala-ehrbase-db-admin-creds
    template:
      engineVersion: v2
      data:
        username: "ehrbase4"
        password: "{{ .vitala_ehrbase_db_admin_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/vitala
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vitala-ehrbase-db-creds
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: vitala-ehrbase-db-creds
    template:
      engineVersion: v2
      data:
        username: "ehrbase_restricted4"
        password: "{{ .vitala_ehrbase_db_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/vitala
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vitala-ehrbase-db-postgres-creds
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: vitala-ehrbase-db-postgres-creds
    template:
      engineVersion: v2
      data:
        username: "postgres"
        password: "{{ .vitala_ehrbase_db_postgres_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/vitala
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vitala-federation-key
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: vitala-federation-key
    template:
      engineVersion: v2
      data:
        key: "{{ .vitala_federation_key }}"
  dataFrom:
    - extract:
        key: hdp-env/vitala
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vitala-federation-break-the-glass-key
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: vitala-federation-break-the-glass-key
    template:
      engineVersion: v2
      data:
        key: "{{ .vitala_federation_break_the_glass_key }}"
  dataFrom:
    - extract:
        key: hdp-env/vitala
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vitala-transform-creds
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: vitala-transform-creds
    template:
      engineVersion: v2
      data:
        username: "transform4"
        password: "{{ .vitala_transform_creds }}"
  dataFrom:
    - extract:
        key: hdp-env/vitala