apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - federation-rest/
  - jupyter-zib/
  - terminology-server-proxy/
  - openehr-nodes/envida/
  - openehr-nodes/mumc/
  - openehr-nodes/vitala/
  - openehr-nodes/zio/
  - openehr-nodes/test/
