apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dh-health-jupyter

resources:
  - namespace.yaml
  - secrets
  - pvc.yaml
  - tls.yaml
  - jupyter-zib-gateway.yaml
  - ../../../base/jupyter-zib

components:
  - ../shared-components

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: jupyter-zib
      namespace: dh-health-jupyter
    path: patches/deployment/jupyter-delete-test-config.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: jupyter-zib
      namespace: dh-health-jupyter
    path: patches/deployment/jupyter-delete-demo-data.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: jupyter-zib
      namespace: dh-health-jupyter
    path: patches/deployment/jupyter-add-demo-data.yaml