apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dh-health-jupyter

images:
- name: registry.prod.dh.unimaas.nl/docker-health/jupyter-zib
  newTag: '2026.2.0'

resources:
  - namespace.yaml
  - ../../../base-config/proxy
  - secrets
  - tls.yaml
  - jupyter-zib-gateway.yaml
  - ../../../base/jupyter-zib
  - ../node-envida/etl-config
  - ../node-mumc/etl-config
  - ../node-vitala/etl-config
  - ../node-zio/etl-config

components:
  - ../shared-components

patches:
  - target:
      kind: Deployment
      name: jupyter-zib
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
        - name: registry-credentials
  # Patch the Jupyter Deployment to use /mnt/demo-data
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: jupyter-zib
    patch: |
      - op: replace
        path: /spec/template/spec/volumes/0/hostPath/path
        value: /mnt/demo-data
