apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: portal-zio-tls-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: prod-vault.tst
    kind: ClusterSecretStore
  target:
    name: portal-zio-tls-secret
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .portal_zio_crt }}"
        tls.key: "{{ .portal_zio_key }}"

  data:
  - secretKey: portal_zio_crt
    remoteRef:
      key: fhml-srv018__tst-k3s-hdp
      property: portal.zio.tst.dh.unimaas.nl.crt
  - secretKey: portal_zio_key
    remoteRef:
      key: fhml-srv018__tst-k3s-hdp
      property: portal.zio.tst.dh.unimaas.nl.key