apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dh-health-envida

resources:
  - vault-auth.yaml
  - ../../../base-config/proxy
  - ../../../base/openehr-nodes/envida/ehrbase
  - ../../../base/openehr-nodes/envida/ehrdb
  - ../../../base/openehr-nodes/envida/etl-zib
  - ../../../base/openehr-nodes/envida/federation-rest
  - ../../../base/openehr-nodes/envida/openehrtool
  - ../../../base/openehr-nodes/envida/portal
  - ../../../base/openehr-nodes/envida/terminology-server-proxy
  - ../../../base/openehr-nodes/envida/transform-rest
  - volumes.yaml
  - config
  - service-discovery

components:
  - components
  - ../shared-components

patches:
  - target:
      group: batch
      version: v1
      kind: Job
      name: etl-zib-pipeline
    patch: |
      - op: replace
        path: /spec/template/spec/volumes/1/hostPath/path
        value: /mnt/demo-data/data/envida-demo-data