apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: dh-health
  labels:
    app: filebeat
    kubernetes.io/cluster-service: "true"
data:
  filebeat.yml: |-
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true
          include_labels: ["app.kubernetes.io/name"]
          labels.dedot: true
          annotations.dedot: true
          hints.default_config:
            type: filestream
            id: kubernetes-container-logs-${data.kubernetes.pod.name}-${data.kubernetes.container.id}
            paths:
            - /var/logs/containers/*-${data.kubernetes.container.id}.log
            parsers:
            - container: ~
            prospector:
             scanner:
               fingerprint.enabled: true
               symlinks: true
            file_identity.fingerprint: ~
    
    processors:
      - add_cloud_metadata: ~
      - add_host_metadata:

    output.logstash:
      hosts: ["elk.tst.dh.unimaas.nl:5044"]
