apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: dh-health-ops
  labels:
    k8s-app: filebeat
    # Terminology
    # Jupyter
    # ETL rest
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: filestream
      id: kubernetes-container-logs
      paths:
        - /var/log/containers/*.log
      parsers:
        - container: ~
      prospector:
        scanner:
          fingerprint.enabled: true
          symlinks: true
      file_identity.fingerprint: ~
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
    - type: log
      enabled: true
      allow_deprecated_use: true
      paths:
        - /usr/share/logs/mumc/pipeline/etl-zib.log
      multiline:
        pattern: '^\['
        negate: true
        match: after
      tags: ["MUMC","ETL_ZIB"]
    - type: log
      enabled: true
      allow_deprecated_use: true
      paths:
        - /usr/share/logs/mumc/ehrdb/postgresql.log
      multiline:
        pattern: '^\['
        negate: true
        match: after
      tags: ["MUMC","POSTGRESQL"]
    - type: filestream
      id: mumc-transform-rest-logs
      paths:
        - /usr/share/logs/mumc/transform-rest/transform-rest.log
      tags: ["MUMC","TRANSFORM_REST"]
    - type: log
      enabled: true
      allow_deprecated_use: true
      paths:
        - /usr/share/logs/envida/pipeline/etl-zib.log
      multiline:
        pattern: '^\['
        negate: true
        match: after
      tags: ["ENVIDA","ETL_ZIB"]
    - type: log
      enabled: true
      allow_deprecated_use: true
      paths:
        - /usr/share/logs/envida/ehrdb/postgresql.log
      multiline:
        pattern: '^\['
        negate: true
        match: after
      tags: ["ENVIDA","POSTGRESQL"]
    - type: filestream
      id: envida-transform-rest-logs
      paths:
        - /usr/share/logs/envida/transform-rest/transform-rest.log
      tags: ["ENVIDA","TRANSFORM_REST"]
    - type: log
      enabled: true
      allow_deprecated_use: true
      paths:
        - /usr/share/logs/zio/pipeline/etl-zib.log
      multiline:
        pattern: '^\['
        negate: true
        match: after
      tags: ["ZIO","ETL_ZIB"]
    - type: log
      enabled: true
      allow_deprecated_use: true
      paths:
        - /usr/share/logs/zio/ehrdb/postgresql.log
      multiline:
        pattern: '^\['
        negate: true
        match: after
      tags: ["ZIO","POSTGRESQL"]
    - type: filestream
      id: zio-transform-rest-logs
      paths:
        - /usr/share/logs/zio/transform-rest/transform-rest.log
      tags: ["ZIO","TRANSFORM_REST"]
    - type: log
      enabled: true
      allow_deprecated_use: true
      paths:
        - /usr/share/logs/test/pipeline/etl-zib.log
      multiline:
        pattern: '^\['
        negate: true
        match: after
      tags: ["TEST","ETL_ZIB"]
    - type: log
      enabled: true
      allow_deprecated_use: true
      paths:
        - /usr/share/logs/test/ehrdb/postgresql.log
      multiline:
        pattern: '^\['
        negate: true
        match: after
      tags: ["TEST","POSTGRESQL"]
    - type: filestream
      id: test-ehrbase-logs
      paths:
         - /usr/share/logs/test/ehrbase/ehrbase.log
      parsers:
         - multiline:
             pattern: '^\['
             negate: true
             match: after
      tags: ["TEST","EHRBASE"]
    - type: filestream
      id: test-transform-rest-logs
      paths:
        - /usr/share/logs/test/transform-rest/transform-rest.log
      tags: ["TEST","TRANSFORM_REST"]
    - type: log
      enabled: true
      allow_deprecated_use: true
      paths:
        - /usr/share/logs/vitala/pipeline/etl-zib.log
      multiline:
        pattern: '^\['
        negate: true
        match: after
      tags: ["VITALA","ETL_ZIB"]
    - type: log
      enabled: true
      allow_deprecated_use: true
      paths:
        - /usr/share/logs/vitala/ehrdb/postgresql.log
      multiline:
        pattern: '^\['
        negate: true
        match: after
      tags: ["VITALA","POSTGRESQL"]
    - type: filestream
      id: vitala-transform-rest-logs
      paths:
        - /usr/share/logs/vitala/transform-rest/transform-rest.log
      tags: [ "VITALA","TRANSFORM_REST" ]
    - type: log
      enabled: true
      allow_deprecated_use: true
      paths:
        - /usr/share/logs/federation/federation-rest.log
      multiline:
        pattern: '^\['
        negate: true
        match: after
      tags: ["FEDERATION_REST"]
    processors:
      - add_cloud_metadata:
      - add_host_metadata:
    output.logstash:
      hosts: ["elk.dh-health-ops:5044"]
      ssl.enabled: true
      ssl.certificate_authorities: [ "/etc/filebeat_ssl/ca.crt" ]
      ssl.certificate: "/etc/filebeat_ssl/filebeat.dh-health-ops.crt"
      ssl.key: "/etc/filebeat_ssl/filebeat.dh-health-ops.key"