apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: dh-health-ops
  labels:
    k8s-app: filebeat
    # Terminology
    # Jupyter
    # ETL rest
data:
  filebeat.yml: |-
    multiline-parser: &multiline_parser
      pattern: '^\['
      negate: true
      match: after
    filebeat.inputs:
    - type: filestream
      id: kubernetes-container-logs
      paths:
        - /var/log/containers/*.log
      parsers:
        - container: ~
      prospector:
        scanner:
          fingerprint.enabled: true
          symlinks: true
      file_identity.fingerprint: ~
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
    # ENVIDA node
    - type: filestream
      id: envida-etl-zib-logs
      paths:
        - /usr/share/logs/envida/pipeline/etl-zib.log
      parsers:
        - multiline: *multiline_parser
      tags: ["ENVIDA","ETL_ZIB"]
    - type: filestream
      id: envida-ehrdb-logs
      paths:
        - /usr/share/logs/envida/ehrdb/postgresql.log
      parsers:
        - multiline: *multiline_parser
      tags: ["ENVIDA","POSTGRESQL","EHRDB"]
    - type: filestream
      id: envida-transform-rest-logs
      paths:
        - /usr/share/logs/envida/transform-rest/transform-rest.log
      tags: ["ENVIDA","TRANSFORM_REST"]
    # MUMC node
    - type: filestream
      id: mumc-etl-zib-logs
      paths:
        - /usr/share/logs/mumc/pipeline/etl-zib.log
      parsers:
        - multiline: *multiline_parser
      tags: ["MUMC","ETL_ZIB"]
    - type: filestream
      id: mumc-ehrdb-logs
      paths:
        - /usr/share/logs/mumc/ehrdb/postgresql.log
      parsers:
        - multiline: *multiline_parser
      tags: ["MUMC","POSTGRESQL","EHRDB"]
    - type: filestream
      id: mumc-transform-rest-logs
      paths:
        - /usr/share/logs/mumc/transform-rest/transform-rest.log
      tags: ["MUMC","TRANSFORM_REST"]
    # VITALA node
    - type: filestream
      id: vitala-etl-zib-logs
      paths:
        - /usr/share/logs/vitala/pipeline/etl-zib.log
      parsers:
        - multiline: *multiline_parser
      tags: ["VITALA","ETL_ZIB"]
    - type: filestream
      id: vitala-ehrdb-logs
      paths:
        - /usr/share/logs/vitala/ehrdb/postgresql.log
      parsers:
        - multiline: *multiline_parser
      tags: ["VITALA","POSTGRESQL","EHRDB"]
    - type: filestream
      id: vitala-transform-rest-logs
      paths:
        - /usr/share/logs/vitala/transform-rest/transform-rest.log
      tags: [ "VITALA","TRANSFORM_REST" ]
    # ZIO node
    - type: filestream
      id: zio-etl-zib-logs
      paths:
        - /usr/share/logs/zio/pipeline/etl-zib.log
      parsers:
        - multiline: *multiline_parser
      tags: ["ZIO","ETL_ZIB"]
    - type: filestream
      id: zio-ehrdb-logs
      paths:
        - /usr/share/logs/zio/ehrdb/postgresql.log
      parsers:
        - multiline: *multiline_parser
      tags: ["ZIO","POSTGRESQL","EHRDB"]
    - type: filestream
      id: zio-transform-rest-logs
      paths:
        - /usr/share/logs/zio/transform-rest/transform-rest.log
      tags: ["ZIO","TRANSFORM_REST"]
    # TEST node
    - type: filestream
      id: test-etl-zib-logs
      paths:
        - /usr/share/logs/test/pipeline/etl-zib.log
      parsers:
        - multiline: *multiline_parser
      tags: ["TEST","ETL_ZIB"]
    - type: filestream
      id: test-ehrdb-logs
      paths:
        - /usr/share/logs/test/ehrdb/postgresql.log
      parsers:
        - multiline: *multiline_parser
      tags: ["TEST","POSTGRESQL","EHRDB"]
    - type: filestream
      id: test-ehrbase-logs
      paths:
        - /usr/share/logs/test/ehrbase/ehrbase.log
      parsers:
        - multiline: *multiline_parser
      tags: ["TEST","EHRBASE"]
    - type: filestream
      id: test-transform-rest-logs
      paths:
        - /usr/share/logs/test/transform-rest/transform-rest.log
      tags: ["TEST","TRANSFORM_REST"]
    # Federation
    - type: filestream
      id: federation-rest-logs
      paths:
        - /usr/share/logs/federation/federation-rest.log
      parsers:
        - multiline: *multiline_parser
      tags: ["FEDERATION_REST"]
    processors:
      - add_cloud_metadata:
      - add_host_metadata:
    output.logstash:
      hosts: ["elk.dh-health-ops:5044"]
      ssl.enabled: true
      ssl.certificate_authorities: [ "/etc/filebeat_ssl/ca.crt" ]
      ssl.certificate: "/etc/filebeat_ssl/filebeat.dh-health-ops.crt"
      ssl.key: "/etc/filebeat_ssl/filebeat.dh-health-ops.key"
