apiVersion: batch/v1
kind: Job
metadata:
  name: test-single-node
  namespace: dh-health
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: wait-test-ehrbase-healthy
        image: busybox:1.28
        imagePullPolicy: Never
        command:
          - sh
          - -c
          - |
            N_ATTEMPTS_EHRBASE=20
            N_SLEEP_EHRBASE=10
            N_ATTEMPTS_TRANSFORM=10
            N_SLEEP_TRANSFORM=5
            
            # Step 1: Wait for EHRbase
            for i in $(seq 1 $N_ATTEMPTS_EHRBASE); do
              echo "Waiting for EHRbase"
              sleep $N_SLEEP_EHRBASE
              if wget -T5 -qO- -Y off test-ehrbase.dh-health:8080/ehrbase/management/health | grep UP; then
                echo "EHRbase is healthy!"
            
                # Step 2: Wait for Transform REST
                for j in $(seq 1 $N_ATTEMPTS_TRANSFORM); do
                  echo "Waiting for Transform REST"
                  sleep $N_SLEEP_TRANSFORM
                  if wget -T5 -qO- -Y off test-transform-rest.dh-health:8080/management/health | grep UP; then
                    echo "Transform REST is healthy!"
                    exit 0
                  fi
                done
            
                echo "Transform REST failed health check after $N_ATTEMPTS_TRANSFORM attempts"
                exit 1
              fi
            done
            
            echo "EHRbase failed health check after $N_ATTEMPTS_EHRBASE attempts"
            exit 1
      containers:
      - name: test-single-node-runner
        image: registry.prod.dh.unimaas.nl/docker-health/etl-zib-test:latest
        # Uncomment the following lines to overwrite the Test Docker image command, and execute the test with different
        # options of your choice and/or execute only one test file.
#        command: ["pytest"]
#        args:
#          - -s
#          - -o
#          - log_cli=true
#          - --log-cli-level=INFO
#          - --verbose
#          - /code/tests/test_vermogen_tot_zich_kleden.py
        envFrom:
        - configMapRef:
            name: dry-run-config
        - configMapRef:
            name: timezone-config
        - configMapRef:
            name: zib-templates-config
        - configMapRef:
            name: etl-config
        - configMapRef:
            name: test-etl-config
        env:
        - name: EHRBASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: test-ehrbase-creds
              key: username
        - name: EHRBASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-ehrbase-creds
              key: password
        - name: EHRBASE_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: test-ehrbase-admin-creds
              key: username
        - name: EHRBASE_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-ehrbase-admin-creds
              key: password
        - name: TRANSFORM_SPRING_USERNAME
          valueFrom:
            secretKeyRef:
              name: test-transform-creds
              key: username
        - name: TRANSFORM_SPRING_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-transform-creds
              key: password
        volumeMounts:
        - name: data
          mountPath: /code/data/test-demo-data
        - name: etl-logs
          mountPath: /code/logs/test
          subPath: test/etl-test-single-node
      volumes:
      - name: data
        hostPath:
          path: /mnt/data/test-demo-data
          type: Directory
      - name: etl-logs
        persistentVolumeClaim:
          claimName: log-pvc
