apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - job.yaml
  - ../../../base/common
  - ../../../base/terminology-server-proxy
  # TEST-node
  - ../../../base/openehr-nodes/test/ehrbase
  - ../../../base/openehr-nodes/test/ehrdb
  - ../../../base/openehr-nodes/test/etl-zib/etl-config
  - ../../../base/openehr-nodes/test/transform-rest

components:
  - ../components/terminology-server-proxy-ingress
  - ../test/components/ehrbase-ingress
  - ../test/components/transform-rest-ingress
  - ../test/components/secrets

patches:
  # imagePullPolicy patches
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Job
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never

configMapGenerator:
  # Set ADMIN_API_ACTIVE: "true" and ADMIN_BASE_URL for development purposes while running the tests teardown.
  - name: test-ehrbase-config
    namespace: dh-health
    behavior: merge
    literals:
      - ADMIN_API_ACTIVE=true
  - name: test-etl-config
    namespace: dh-health
    behavior: merge
    literals:
      - EHRBASE_ADMIN_BASE_URL=http://test-ehrbase.dh-health:8080/ehrbase/rest/admin
