apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dh-health-test-single-node

resources:
  - job.yaml
  - volumes.yaml
  - namespace.yaml
  # TEST-node
  - ../../../base/openehr-nodes/test/ehrbase
  - ../../../base/openehr-nodes/test/ehrdb
  - ../../../base/openehr-nodes/test/etl-zib/etl-config
  - ../../../base/openehr-nodes/test/terminology-server-proxy
  - ../../../base/openehr-nodes/test/transform-rest

components:
  - ../shared-components
  - ../certificates/nedap-certificate-secret
  # TEST-node
  - ../node-test/components/ehrbase-gateway
  - ../node-test/components/transform-rest-gateway
  - ../node-test/components/terminology-server-proxy-gateway
  - ../node-test/components/secrets

patches:
  # imagePullPolicy patches
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Job
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never

configMapGenerator:
  - name: etl-config-node
    behavior: merge
    literals:
      - EHRBASE_ADMIN_BASE_URL=http://ehrbase:8080/ehrbase/rest/admin