apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

configMapGenerator:
- name: transform-server-config
  namespace: dh-health
  literals:
      - TRANSFORM_SPRING_BASE_URL=http://transform-rest.dh-health:8080
