apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-zib
spec:
  selector:
    matchLabels:
      app: jupyter-zib
  template:
    spec:
      containers:
        - name: jupyter-zib
          env:
            - name: TEST__EHRBASE_USERNAME
              $patch: delete
            - name: TEST__EHRBASE_PASSWORD
              $patch: delete
            - name: TEST__EHRBASE_BASE_URL
              $patch: delete
            - name: TEST__DATASET_FOLDER_NAME
              $patch: delete
            - name: TEST__SOURCE_SYSTEM_ID
              $patch: delete
            - name: TEST__LOGGER_FILENAME
              $patch: delete